import { getPool,sql } from '../../config/database';
import { AppError } from '../../middleware/errorHandler';
import { normalizeBrandName } from '../../utils/brand-normalization';
import type { BrandRequestFilters,BrandRequestInput,BrandRequestStatus } from './brand-requests.types';

const columns=`br.id,br.requester_user_id requesterUserId,br.shop_id shopId,br.requested_name requestedName,
br.normalized_name normalizedName,br.website_url websiteUrl,br.description,br.status,br.resolved_brand_id resolvedBrandId,
br.review_reason reviewReason,br.reviewed_by_user_id reviewedByUserId,br.reviewed_at reviewedAt,
br.created_at createdAt,br.updated_at updatedAt,b.name resolvedBrandName,b.slug resolvedBrandSlug,b.is_generic resolvedBrandGeneric`;
const map=(r:any)=>({...r,id:Number(r.id),requesterUserId:Number(r.requesterUserId),shopId:Number(r.shopId),
resolvedBrandId:r.resolvedBrandId==null?null:Number(r.resolvedBrandId),resolvedBrand:r.resolvedBrandId==null?null:{id:Number(r.resolvedBrandId),name:r.resolvedBrandName,slug:r.resolvedBrandSlug,isGeneric:Boolean(r.resolvedBrandGeneric)}});
async function history(request:sql.Request,id:number){const result=await request.input('historyId',sql.Int,id).query(`SELECT h.id,h.from_status fromStatus,h.to_status toStatus,h.actor_user_id actorUserId,h.reason,h.created_at createdAt,u.name actorName FROM dbo.BrandRequestStatusHistory h LEFT JOIN dbo.Users u ON u.id=h.actor_user_id WHERE h.brand_request_id=@historyId ORDER BY h.created_at,h.id`);return result.recordset;}
async function audit(tx:sql.Transaction,actor:number,id:number,action:string,before:unknown,after:unknown){await tx.request().input('auditActor',sql.Int,actor).input('auditId',sql.Int,id).input('auditAction',sql.NVarChar(100),action).input('auditBefore',sql.NVarChar(sql.MAX),before?JSON.stringify(before):null).input('auditAfter',sql.NVarChar(sql.MAX),JSON.stringify(after)).query(`INSERT dbo.AuditLogs(user_id,action,entity_type,entity_id,old_value,new_value,timestamp) VALUES(@auditActor,@auditAction,N'BrandRequest',@auditId,@auditBefore,@auditAfter,SYSUTCDATETIME())`);}
async function addHistory(tx:sql.Transaction,id:number,from:BrandRequestStatus|null,to:BrandRequestStatus,actor:number,reason:string|null){await tx.request().input('historyRequest',sql.Int,id).input('historyFrom',sql.NVarChar(20),from).input('historyTo',sql.NVarChar(20),to).input('historyActor',sql.Int,actor).input('historyReason',sql.NVarChar(1000),reason).query(`INSERT dbo.BrandRequestStatusHistory(brand_request_id,from_status,to_status,actor_user_id,reason) VALUES(@historyRequest,@historyFrom,@historyTo,@historyActor,@historyReason)`);}
function slugify(name:string,id:number){const base=name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'brand';return `${base}-${id}`;}

export const brandRequestsService={
async listSeller(userId:number,f:BrandRequestFilters){const pool=await getPool();const req=pool.request().input('owner',sql.Int,userId).input('offset',sql.Int,(f.page-1)*f.limit).input('limit',sql.Int,f.limit);const clauses=['s.owner_user_id=@owner'];if(f.status){req.input('status',sql.NVarChar(20),f.status);clauses.push('br.status=@status');}const result=await req.query(`SELECT ${columns},COUNT_BIG(*) OVER() total FROM dbo.Shops s JOIN dbo.BrandRequests br ON br.shop_id=s.id LEFT JOIN dbo.Brands b ON b.id=br.resolved_brand_id WHERE ${clauses.join(' AND ')} ORDER BY br.created_at DESC,br.id DESC OFFSET @offset ROWS FETCH NEXT @limit ROWS ONLY`);return{items:result.recordset.map(map),page:f.page,limit:f.limit,total:Number(result.recordset[0]?.total??0)};},
async detailSeller(userId:number,id:number){const pool=await getPool();const result=await pool.request().input('owner',sql.Int,userId).input('id',sql.Int,id).query(`SELECT ${columns} FROM dbo.BrandRequests br LEFT JOIN dbo.Brands b ON b.id=br.resolved_brand_id JOIN dbo.Shops s ON s.id=br.shop_id WHERE br.id=@id AND s.owner_user_id=@owner`);if(!result.recordset[0])throw new AppError(404,'Brand request not found');return{...map(result.recordset[0]),history:await history(pool.request(),id)};},
async create(userId:number,input:BrandRequestInput){const requestedName=input.requestedName.trim();const normalizedName=normalizeBrandName(requestedName);const pool=await getPool();const tx=pool.transaction();let begun=false;try{await tx.begin();begun=true;
const shop=(await tx.request().input('owner',sql.Int,userId).query(`SELECT id,status FROM dbo.Shops WITH(UPDLOCK,HOLDLOCK) WHERE owner_user_id=@owner`)).recordset[0];if(!shop)throw new AppError(409,'Seller account has no Shop');if(shop.status!=='ACTIVE')throw new AppError(409,'Suspended Shop cannot create Brand requests');
const brand=(await tx.request().input('normalized',sql.NVarChar(200),normalizedName).query('SELECT id,name,is_active,is_generic FROM dbo.Brands WITH(UPDLOCK,HOLDLOCK) WHERE normalized_name=@normalized')).recordset[0];if(brand){if(brand.is_generic)throw new AppError(409,'Use the existing Generic Brand');throw new AppError(409,brand.is_active?`Brand already exists: ${brand.name}`:'Brand exists but is inactive; contact an administrator');}
const pending=(await tx.request().input('pendingName',sql.NVarChar(200),normalizedName).query(`SELECT id FROM dbo.BrandRequests WITH(UPDLOCK,HOLDLOCK) WHERE normalized_name=@pendingName AND status=N'PENDING'`)).recordset[0];if(pending)throw new AppError(409,'A pending request already exists for this Brand name');
const inserted=await tx.request().input('requester',sql.Int,userId).input('shop',sql.Int,shop.id).input('name',sql.NVarChar(200),requestedName).input('normalizedCreate',sql.NVarChar(200),normalizedName).input('website',sql.NVarChar(500),input.websiteUrl||null).input('description',sql.NVarChar(2000),input.description||null).query<{id:number}>(`INSERT dbo.BrandRequests(requester_user_id,shop_id,requested_name,normalized_name,website_url,description,status) OUTPUT INSERTED.id VALUES(@requester,@shop,@name,@normalizedCreate,@website,@description,N'PENDING')`);const id=Number(inserted.recordset[0].id);await addHistory(tx,id,null,'PENDING',userId,null);await audit(tx,userId,id,'brand_request.created',null,{status:'PENDING',normalizedName});await tx.commit();begun=false;return this.detailSeller(userId,id);
}catch(e){if(begun)await tx.rollback();if([2601,2627].includes((e as {number?:number}).number??0))throw new AppError(409,'A pending request already exists for this Brand name');throw e;}},
async listAdmin(f:BrandRequestFilters){const pool=await getPool();const req=pool.request().input('offset',sql.Int,(f.page-1)*f.limit).input('limit',sql.Int,f.limit);const clauses:string[]=[];if(f.status){req.input('status',sql.NVarChar(20),f.status);clauses.push('br.status=@status');}if(f.search){req.input('search',sql.NVarChar(202),`%${f.search}%`);clauses.push('(br.requested_name LIKE @search OR u.email LIKE @search OR s.name LIKE @search)');}const direction=f.sortOrder==='asc'?'ASC':'DESC';const result=await req.query(`SELECT ${columns},u.name requesterName,u.email requesterEmail,s.name shopName,s.slug shopSlug,reviewer.name reviewerName,COUNT_BIG(*) OVER() total FROM dbo.BrandRequests br JOIN dbo.Users u ON u.id=br.requester_user_id JOIN dbo.Shops s ON s.id=br.shop_id LEFT JOIN dbo.Users reviewer ON reviewer.id=br.reviewed_by_user_id LEFT JOIN dbo.Brands b ON b.id=br.resolved_brand_id ${clauses.length?'WHERE '+clauses.join(' AND '):''} ORDER BY br.created_at ${direction},br.id ${direction} OFFSET @offset ROWS FETCH NEXT @limit ROWS ONLY`);return{items:result.recordset.map(map),page:f.page,limit:f.limit,total:Number(result.recordset[0]?.total??0)};},
async detailAdmin(id:number){const pool=await getPool();const result=await pool.request().input('id',sql.Int,id).query(`SELECT ${columns},u.name requesterName,u.email requesterEmail,s.name shopName,s.slug shopSlug,reviewer.name reviewerName,mb.id matchingBrandId,mb.name matchingBrandName,mb.is_active matchingBrandActive FROM dbo.BrandRequests br JOIN dbo.Users u ON u.id=br.requester_user_id JOIN dbo.Shops s ON s.id=br.shop_id LEFT JOIN dbo.Users reviewer ON reviewer.id=br.reviewed_by_user_id LEFT JOIN dbo.Brands b ON b.id=br.resolved_brand_id LEFT JOIN dbo.Brands mb ON mb.normalized_name=br.normalized_name WHERE br.id=@id`);if(!result.recordset[0])throw new AppError(404,'Brand request not found');return{...map(result.recordset[0]),history:await history(pool.request(),id)};},
async approve(id:number,adminId:number){const pool=await getPool();const tx=pool.transaction();let begun=false;try{await tx.begin();begun=true;const row=(await tx.request().input('id',sql.Int,id).query(`SELECT * FROM dbo.BrandRequests WITH(UPDLOCK,HOLDLOCK) WHERE id=@id`)).recordset[0];if(!row)throw new AppError(404,'Brand request not found');if(row.status!=='PENDING')throw new AppError(409,'Brand request has already been reviewed');
let brand=(await tx.request().input('normalized',sql.NVarChar(200),row.normalized_name).query('SELECT id,name FROM dbo.Brands WITH(UPDLOCK,HOLDLOCK) WHERE normalized_name=@normalized')).recordset[0];let created=false;if(!brand){const inserted=await tx.request().input('name',sql.NVarChar(200),String(row.requested_name).trim()).input('slug',sql.NVarChar(100),slugify(String(row.requested_name),id)).input('normalizedCreate',sql.NVarChar(200),row.normalized_name).query<{id:number}>(`INSERT dbo.Brands(name,slug,normalized_name,is_generic,is_active,created_at,updated_at) OUTPUT INSERTED.id VALUES(@name,@slug,@normalizedCreate,0,1,SYSUTCDATETIME(),SYSUTCDATETIME())`);brand={id:Number(inserted.recordset[0].id),name:row.requested_name};created=true;}
await tx.request().input('id2',sql.Int,id).input('brand',sql.Int,brand.id).input('reviewer',sql.Int,adminId).query(`UPDATE dbo.BrandRequests SET status=N'APPROVED',resolved_brand_id=@brand,reviewed_by_user_id=@reviewer,reviewed_at=SYSUTCDATETIME(),updated_at=SYSUTCDATETIME() WHERE id=@id2`);
const linked=(await tx.request().input('linkedRequest',sql.Int,id).query(`SELECT id,moderation_status FROM dbo.Products WITH(UPDLOCK,HOLDLOCK) WHERE brand_request_id=@linkedRequest AND moderation_status IN(N'DRAFT',N'REJECTED')`)).recordset;
await tx.request().input('linkedRequestUpdate',sql.Int,id).input('linkedBrand',sql.Int,brand.id).query(`UPDATE dbo.Products SET brand_id=@linkedBrand,brand_request_id=NULL,updated_at=SYSUTCDATETIME() WHERE brand_request_id=@linkedRequestUpdate AND moderation_status IN(N'DRAFT',N'REJECTED')`);
for(const product of linked)await tx.request().input('productActor',sql.Int,adminId).input('productId',sql.Int,product.id).input('productOld',sql.NVarChar(sql.MAX),JSON.stringify({brandRequestId:id,moderationStatus:product.moderation_status})).input('productNew',sql.NVarChar(sql.MAX),JSON.stringify({brandId:Number(brand.id),moderationStatus:product.moderation_status})).query(`INSERT dbo.AuditLogs(user_id,action,entity_type,entity_id,old_value,new_value,timestamp) VALUES(@productActor,N'product.brand_request_resolved',N'Product',@productId,@productOld,@productNew,SYSUTCDATETIME())`);
await addHistory(tx,id,'PENDING','APPROVED',adminId,null);await audit(tx,adminId,id,created?'brand_request.approved_brand_created':'brand_request.approved_brand_resolved',{status:'PENDING'},{status:'APPROVED',brandId:Number(brand.id),linkedProducts:linked.length});await tx.commit();begun=false;return this.detailAdmin(id);
}catch(e){if(begun)await tx.rollback();if([2601,2627].includes((e as {number?:number}).number??0))throw new AppError(409,'Concurrent Brand approval conflict');throw e;}},
async reject(id:number,adminId:number,reasonValue:string){const reason=reasonValue.trim();const pool=await getPool();const tx=pool.transaction();let begun=false;try{await tx.begin();begun=true;const row=(await tx.request().input('id',sql.Int,id).query('SELECT id,status FROM dbo.BrandRequests WITH(UPDLOCK,HOLDLOCK) WHERE id=@id')).recordset[0];if(!row)throw new AppError(404,'Brand request not found');if(row.status!=='PENDING')throw new AppError(409,'Brand request has already been reviewed');await tx.request().input('id2',sql.Int,id).input('reviewer',sql.Int,adminId).input('reason',sql.NVarChar(1000),reason).query(`UPDATE dbo.BrandRequests SET status=N'REJECTED',review_reason=@reason,reviewed_by_user_id=@reviewer,reviewed_at=SYSUTCDATETIME(),updated_at=SYSUTCDATETIME() WHERE id=@id2`);await addHistory(tx,id,'PENDING','REJECTED',adminId,reason);await audit(tx,adminId,id,'brand_request.rejected',{status:'PENDING'},{status:'REJECTED',reason});await tx.commit();begun=false;return this.detailAdmin(id);}catch(e){if(begun)await tx.rollback();throw e;}}
};
