import * as bcrypt from 'bcryptjs';
import { closePool, query } from '../config/database';
import { todayInTimeZone } from '../utils/timezone';

if (process.env.COACH_ACCEPTANCE !== '1' || !process.env.DB_NAME?.startsWith('GYMFIT_DB_COACH_ACCEPTANCE_')) throw new Error('Coach acceptance requires COACH_ACCEPTANCE=1 and an isolated GYMFIT_DB_COACH_ACCEPTANCE_* database');
const base = process.env.COACH_API_BASE || 'http://localhost:5000/api';
const suffix = '20260803';
const password = 'CoachAccept#20260803';
const assignmentStart = todayInTimeZone('Asia/Ho_Chi_Minh');
const addDays = (value:string, days:number) => { const date = new Date(`${value}T00:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0,10); };
const emails = { coachA:`coach-a-${suffix}@example.test`, coachB:`coach-b-${suffix}@example.test`, memberA:`member-a-${suffix}@example.test`, memberB:`member-b-${suffix}@example.test` };
type Account = { id:number; email:string; password:string; token?:string };
const accounts:Record<keyof typeof emails,Account> = Object.fromEntries(Object.entries(emails).map(([key,email])=>[key,{id:0,email,password}])) as Record<keyof typeof emails,Account>;
const check = (value:boolean,message:string) => { if (!value) throw new Error(`ASSERTION_FAILED ${message}`); console.log(`PASS ${message}`); };

async function cleanup() {
  const users = await query<{ id:number }>('SELECT id FROM dbo.Users WHERE email IN (@coachA,@coachB,@memberA,@memberB)', { coachA:emails.coachA,coachB:emails.coachB,memberA:emails.memberA,memberB:emails.memberB });
  const ids = users.recordset.map(row=>Number(row.id)); if (!ids.length) return;
  const csv = ids.join(',');
  await query(`DELETE FROM dbo.CoachProgramSchedules WHERE assignment_id IN (SELECT id FROM dbo.CoachProgramAssignments WHERE member_id IN (${ids.filter((_,index)=>index>=2).join(',')||'-1'}))`);
  await query(`DELETE FROM dbo.CoachProgramAssignments WHERE member_id IN (${ids.filter((_,index)=>index>=2).join(',')||'-1'}) OR coach_id IN (${ids.slice(0,2).join(',')||'-1'})`);
  await query(`DELETE FROM dbo.WorkoutProgramExercises WHERE program_day_id IN (SELECT id FROM dbo.WorkoutProgramDays WHERE program_id IN (SELECT id FROM dbo.WorkoutPrograms WHERE owner_coach_id IN (${ids.slice(0,2).join(',')||'-1'})))`);
  await query(`DELETE FROM dbo.WorkoutProgramDays WHERE program_id IN (SELECT id FROM dbo.WorkoutPrograms WHERE owner_coach_id IN (${ids.slice(0,2).join(',')||'-1'}))`);
  await query(`DELETE FROM dbo.WorkoutPrograms WHERE owner_coach_id IN (${ids.slice(0,2).join(',')||'-1'})`);
  await query(`DELETE FROM dbo.Exercises WHERE slug=@slug`, { slug:`coach-acceptance-exercise-${suffix}` });
  await query(`DELETE FROM dbo.WorkoutSessions WHERE user_id IN (${csv}) OR workout_id IN (SELECT id FROM dbo.Workouts WHERE coach_id IN (${ids.slice(0,2).join(',')||'-1'}))`);
  await query(`DELETE FROM dbo.WorkoutExercises WHERE workout_id IN (SELECT id FROM dbo.Workouts WHERE coach_id IN (${ids.slice(0,2).join(',')||'-1'}))`);
  await query(`DELETE FROM dbo.Workouts WHERE coach_id IN (${ids.slice(0,2).join(',')||'-1'})`);
  await query(`DELETE FROM dbo.CRMCustomers WHERE user_id IN (${csv})`);
  await query(`DELETE FROM dbo.Notifications WHERE user_id IN (${csv})`);
  await query(`DELETE FROM dbo.AuthSessions WHERE user_id IN (${csv})`);
  await query(`DELETE FROM dbo.Points WHERE user_id IN (${csv})`);
  await query(`DELETE FROM dbo.Users WHERE id IN (${csv})`);
}

async function seed() {
  await cleanup(); const hash = await bcrypt.hash(password, 10);
  for (const [key,email] of Object.entries(emails)) { const role = key.startsWith('coach')?'coach':'member'; const result = await query<{id:number}>(`INSERT dbo.Users(email,password,name,role,is_active,email_verified,token_version) OUTPUT INSERTED.id VALUES(@email,@password,@name,@role,1,1,0)`, { email,password:hash,name:key==='coachA'?'Coach Acceptance A':key==='coachB'?'Coach Acceptance B':key==='memberA'?'Member Acceptance A':'Member Acceptance B',role }); accounts[key as keyof typeof emails].id = Number(result.recordset[0].id); }
  await query(`INSERT dbo.CRMCustomers(user_id,assigned_coach_id) VALUES(@memberA,@coachA),(@memberB,@coachB)`, { memberA:accounts.memberA.id,memberB:accounts.memberB.id,coachA:accounts.coachA.id,coachB:accounts.coachB.id });
  let exercise = await query<{id:number}>('SELECT TOP 1 id FROM dbo.Exercises WHERE is_active=1 ORDER BY id');
  if (!exercise.recordset[0]) exercise = await query<{id:number}>(`INSERT dbo.Exercises(name,slug,description,instructions,muscle_group,equipment,difficulty,is_active) OUTPUT INSERTED.id VALUES(N'Coach Acceptance Exercise',@slug,N'Acceptance-only active Exercise',N'Use controlled form.',N'full_body',N'bodyweight',N'intermediate',1)`, { slug:`coach-acceptance-exercise-${suffix}` });
  check(Boolean(exercise.recordset[0]),'active exercise seed exists');
  const workout = await query<{id:number}>(`INSERT dbo.Workouts(name,description,coach_id,difficulty,is_active) OUTPUT INSERTED.id VALUES(N'Coach acceptance legacy workout',N'Read-only acceptance workout',@coach,N'intermediate',1)`, { coach:accounts.coachA.id });
  await query(`INSERT dbo.WorkoutExercises(workout_id,name,sets,reps,rest_seconds,sort_order) VALUES(@workout,N'Acceptance Exercise',3,10,60,1)`, { workout:workout.recordset[0].id });
  await query(`INSERT dbo.WorkoutSessions(user_id,workout_id,started_at,completed_at,status,notes) VALUES(@member,@workout,DATEADD(day,-2,SYSUTCDATETIME()),DATEADD(minute,45,DATEADD(day,-2,SYSUTCDATETIME())),N'completed',N'Coach read-only acceptance session')`, { member:accounts.memberA.id,workout:workout.recordset[0].id });
  return Number(exercise.recordset[0].id);
}

async function call(method:string,path:string,account?:Account,body?:unknown) { const response = await fetch(`${base}${path}`, { method, headers:{ 'Content-Type':'application/json', ...(account?.token?{Authorization:`Bearer ${account.token}`}:{}) }, body:body===undefined?undefined:JSON.stringify(body) }); const text = await response.text(); let data:unknown=null; try{data=JSON.parse(text);}catch{} return { status:response.status,data:data as {data:any;message?:string} }; }
async function login(account:Account) { const result=await call('POST','/auth/login',undefined,{email:account.email,password:account.password}); check(result.status===200,`${account.email} login`); account.token=String(result.data.data.accessToken); }

async function run() {
  const exerciseId = await seed(); await login(accounts.coachA); await login(accounts.coachB); await login(accounts.memberA);
  check((await call('GET','/coach/dashboard')).status===401,'guest cannot access Coach API');
  check((await call('GET','/coach/dashboard',accounts.memberA)).status===403,'Member cannot access Coach API');
  const initialDashboard=await call('GET','/coach/dashboard',accounts.coachA); check(initialDashboard.status===200,'Coach dashboard access'); check(initialDashboard.data.data.attentionQueueAvailable===true&&Array.isArray(initialDashboard.data.data.attentionQueue)&&initialDashboard.data.data.attentionQueue.length<=10&&initialDashboard.data.data.attentionQueue.every((item:any)=>typeof item.actionUrl==='string'&&item.actionUrl.startsWith('/coach/')),'Dashboard attention queue is bounded and actionable');
  const ownerSpoof = await call('POST','/coach/workout-programs',accounts.coachA,{name:'Spoof',goal:'GENERAL_FITNESS',difficulty:'BEGINNER',durationWeeks:4,daysPerWeek:3,owner_coach_id:accounts.coachB.id}); check(ownerSpoof.status===400,'owner_coach_id rejected from body');
  const programA = await call('POST','/coach/workout-programs',accounts.coachA,{name:'Coach A Program',description:'Acceptance program',goal:'STRENGTH',difficulty:'INTERMEDIATE',durationWeeks:4,daysPerWeek:1}); check(programA.status===201,'Coach A creates owned Program'); const programAId=Number(programA.data.data.id);
  const programB = await call('POST','/coach/workout-programs',accounts.coachB,{name:'Coach B Program',description:'Private program',goal:'MOBILITY',difficulty:'BEGINNER',durationWeeks:1,daysPerWeek:1}); check(programB.status===201,'Coach B creates owned Program'); const programBId=Number(programB.data.data.id);
  check((await call('GET',`/coach/workout-programs/${programBId}`,accounts.coachA)).status===404,'Coach A cannot read Coach B Program'); check((await call('PATCH',`/coach/workout-programs/${programBId}`,accounts.coachA,{name:'IDOR',goal:'GENERAL_FITNESS',difficulty:'BEGINNER',durationWeeks:1,daysPerWeek:1})).status===404,'Coach A cannot edit Coach B Program');
  const day = await call('POST',`/coach/workout-programs/${programAId}/days`,accounts.coachA,{weekNumber:1,dayNumber:1,title:'Acceptance Day'}); const weekTwoDay = await call('POST',`/coach/workout-programs/${programAId}/days`,accounts.coachA,{weekNumber:2,dayNumber:1,title:'Acceptance Week Two Day'}); check(day.status===201&&weekTwoDay.status===201,'Coach creates Program Days across weeks'); const dayId=Number(day.data.data.id); check((await call('POST',`/coach/workout-programs/${programAId}/days`,accounts.coachA,{weekNumber:1,dayNumber:1,title:'Duplicate Day'})).status===409,'Duplicate Program Day position returns 409'); check((await call('POST',`/coach/workout-programs/${programAId}/days`,accounts.coachA,{weekNumber:1,dayNumber:8,title:'Invalid Day'})).status===400,'Program Day 8 is rejected');
  const programExercise = await call('POST',`/coach/workout-program-days/${dayId}/exercises`,accounts.coachA,{exerciseId,targetSets:3,targetRepsMin:8,targetRepsMax:12,restSeconds:60}); const weekTwoExercise = await call('POST',`/coach/workout-program-days/${Number(weekTwoDay.data.data.id)}/exercises`,accounts.coachA,{exerciseId,targetSets:3,targetRepsMin:8,targetRepsMax:12,restSeconds:60}); check(programExercise.status===201&&weekTwoExercise.status===201,'Coach adds active Exercises to every publishable Program Day');
  check((await call('POST',`/coach/workout-programs/${programAId}/days/reorder`,accounts.coachA,{ids:[dayId,dayId]})).status===400,'duplicate Day reorder rejected'); check((await call('POST',`/coach/workout-programs/${programAId}/publish`,accounts.coachA,{})).status===200,'Coach publishes Program before Assignment');
  check((await call('GET',`/coach/members/${accounts.memberB.id}`,accounts.coachA)).status===404,'Coach A cannot read Member B'); check((await call('GET','/coach/members',accounts.coachA)).data.data.items.every((item:any)=>Number(item.id)!==accounts.memberB.id),'Member list excludes Member B');
  const assignmentBody={memberId:accounts.memberA.id,programId:programAId,startDate:assignmentStart,scheduleTimezone:'Asia/Ho_Chi_Minh',note:'Acceptance'};
  check((await call('POST','/coach/assignments',accounts.coachA,{...assignmentBody,coach_id:accounts.coachB.id})).status===400,'coach_id rejected from Assignment body');
  const assignments=await Promise.all([call('POST','/coach/assignments',accounts.coachA,assignmentBody),call('POST','/coach/assignments',accounts.coachA,assignmentBody)]); check(assignments.map(item=>item.status).sort().join(',')==='201,409','duplicate active Assignment concurrency protected'); const assignment=assignments.find(item=>item.status===201)!; const assignmentId=Number(assignment.data.data.id);
  check((await call('POST','/coach/assignments',accounts.coachA,{...assignmentBody,memberId:accounts.memberB.id})).status===404,'Coach A cannot assign Member B');
  const generated=await call('POST',`/coach/assignments/${assignmentId}/schedules/generate`,accounts.coachA,{fromDate:assignmentStart,horizonDays:7}); check(generated.status===200 && Number(generated.data.data.inserted)>=1 && generated.data.data.fromDate===assignmentStart && generated.data.data.toDate===addDays(assignmentStart,6),'bounded schedule generation returns effective range'); const queueAfterGeneration=await call('GET','/coach/dashboard',accounts.coachA); check(queueAfterGeneration.status===200&&Array.isArray(queueAfterGeneration.data.data.attentionQueue)&&queueAfterGeneration.data.data.attentionQueue.length<=10&&queueAfterGeneration.data.data.attentionQueue.every((item:any)=>typeof item.actionUrl==='string'&&item.actionUrl.startsWith('/coach/')),'Dashboard attention queue remains scoped and bounded after schedule generation'); check((await call('PATCH',`/coach/workout-program-days/${dayId}`,accounts.coachA,{weekNumber:2,dayNumber:1,title:'Moved after schedule'})).status===409,'Published Program Day position remains locked'); check((await call('PATCH',`/coach/workout-program-days/${dayId}`,accounts.coachA,{weekNumber:1,dayNumber:1,title:'Updated Acceptance Day',description:'Safe metadata edit'})).status===409,'Published Program Day metadata is immutable');
  const supplementalDate=addDays(assignmentStart,7); const supplemental=await call('POST',`/coach/assignments/${assignmentId}/schedules/generate`,accounts.coachA,{fromDate:supplementalDate,horizonDays:7}); const supplementalWeek=await query<{week_number:number}>(`SELECT TOP 1 d.week_number FROM dbo.CoachProgramSchedules s JOIN dbo.WorkoutProgramDays d ON d.id=s.program_day_id WHERE s.assignment_id=@assignmentId AND s.scheduled_date>=@scheduledDate ORDER BY s.scheduled_date,s.id`,{assignmentId,scheduledDate:supplementalDate}); check(supplemental.status===200&&Number(supplemental.data.data.inserted)===1&&Number(supplementalWeek.recordset[0]?.week_number)===2,'supplemental generation preserves assignment-relative program week');
  const duplicateGeneration=await Promise.all([call('POST',`/coach/assignments/${assignmentId}/schedules/generate`,accounts.coachA,{fromDate:assignmentStart,horizonDays:7}),call('POST',`/coach/assignments/${assignmentId}/schedules/generate`,accounts.coachA,{fromDate:assignmentStart,horizonDays:7})]); check(duplicateGeneration.every(item=>item.status===200) && duplicateGeneration.every(item=>Number(item.data.data.inserted)===0),'duplicate schedule generation idempotent under concurrency');
  const scheduleList=await call('GET','/coach/schedules?limit=50',accounts.coachA); check(scheduleList.status===200 && scheduleList.data.data.items.length>=1,'Coach reads scoped schedules');
  const dashboardBefore=await call('GET','/coach/dashboard',accounts.coachA); check(dashboardBefore.status===200 && dashboardBefore.data.data.counts.assignedMembers===1 && dashboardBefore.data.data.counts.activeMembers===1 && dashboardBefore.data.data.upcomingSchedules.length>=1 && dashboardBefore.data.data.upcomingSchedules.every((item:any)=>item.scheduled_date>=assignmentStart),'Dashboard separates assigned/active members and filters future schedules in SQL');
  const pauseAttempts=await Promise.all([call('POST',`/coach/assignments/${assignmentId}/pause`,accounts.coachA,{}),call('POST',`/coach/assignments/${assignmentId}/pause`,accounts.coachA,{})]); check(pauseAttempts.map(item=>item.status).sort((a,b)=>a-b).join(',')==='200,409','Concurrent pause has one winner'); check((await call('POST',`/coach/assignments/${assignmentId}/pause`,accounts.coachA,{})).status===409,'Terminally repeated pause is rejected'); const resumeAttempts=await Promise.all([call('POST',`/coach/assignments/${assignmentId}/resume`,accounts.coachA,{}),call('POST',`/coach/assignments/${assignmentId}/resume`,accounts.coachA,{})]); check(resumeAttempts.map(item=>item.status).sort((a,b)=>a-b).join(',')==='200,409','Concurrent resume has one winner'); const completeAttempts=await Promise.all([call('POST',`/coach/assignments/${assignmentId}/complete`,accounts.coachA,{}),call('POST',`/coach/assignments/${assignmentId}/complete`,accounts.coachA,{})]); check(completeAttempts.map(item=>item.status).sort((a,b)=>a-b).join(',')==='200,409','Concurrent complete has one winner'); const scheduleState=await query<{scheduled_count:number}>(`SELECT COUNT(*) AS scheduled_count FROM dbo.CoachProgramSchedules WHERE assignment_id=@assignmentId AND status=N'SCHEDULED'`,{assignmentId}); check(Number(scheduleState.recordset[0].scheduled_count)===0,'Completing an Assignment closes remaining scheduled items');
  const dashboardAfter=await call('GET','/coach/dashboard',accounts.coachA); check(dashboardAfter.status===200 && dashboardAfter.data.data.counts.assignedMembers===1 && dashboardAfter.data.data.counts.activeMembers===0 && dashboardAfter.data.data.upcomingSchedules.length===0,'Dashboard removes completed Assignment from active/future metrics');
  check((await call('GET',`/coach/members/${accounts.memberA.id}/sessions`,accounts.coachA)).status===200,'Coach reads scoped legacy session history'); const legacySession=await query<{id:number}>(`SELECT TOP 1 ws.id FROM dbo.WorkoutSessions ws JOIN dbo.Workouts w ON w.id=ws.workout_id WHERE ws.user_id=@memberId AND w.coach_id=@coachId ORDER BY ws.id DESC`,{memberId:accounts.memberA.id,coachId:accounts.coachA.id}); check(Boolean(legacySession.recordset[0]),'Legacy session fixture is available for source routing'); const legacyId=Number(legacySession.recordset[0].id); check((await call('GET',`/coach/members/${accounts.memberA.id}/sessions/legacy/${legacyId}`,accounts.coachA)).status===200,'Legacy source route returns legacy Session'); check((await call('GET',`/coach/members/${accounts.memberA.id}/sessions/member/${legacyId}`,accounts.coachA)).status===404,'Member source does not fall back to legacy Session'); check((await call('GET',`/coach/members/${accounts.memberA.id}/sessions/${legacyId}`,accounts.coachA)).status===200,'Unambiguous legacy compatibility route remains readable'); check((await call('GET',`/coach/members/${accounts.memberB.id}/sessions`,accounts.coachA)).status===404,'Coach cannot read out-of-scope session history');
  const progress=await call('GET',`/coach/members/${accounts.memberA.id}/progress`,accounts.coachA); check(progress.status===200 && progress.data.data.blockedReason===null && progress.data.data.dataSources.memberProgressFlow===true,'Coach progress reads the Member progress contract');
  check((await call('GET',`/coach/assignments/${assignmentId}`,accounts.coachB)).status===404,'Coach B cannot read Coach A Assignment');
  console.log(JSON.stringify({verdict:'PASS',database:process.env.DB_NAME,accounts:{coachA:emails.coachA,coachB:emails.coachB,memberA:emails.memberA,memberB:emails.memberB},password,programAId,programBId,assignmentId,exerciseId}));
}

if (process.argv.includes('--cleanup')) cleanup().then(()=>console.log(`CLEANUP_PASS ${process.env.DB_NAME}`)).catch(error=>{console.error(error);process.exitCode=1;}).finally(closePool); else run().catch(error=>{console.error(error);process.exitCode=1;}).finally(closePool);
