import crypto from 'crypto';
import { promises as fs } from 'fs';
import path from 'path';
import bcrypt from 'bcryptjs';
import * as mssql from 'mssql';
import type { Server } from 'http';
import { config } from '../config/config';
import { closePool,query } from '../config/database';

if(process.env.SELLER006_ACCEPTANCE!=='1')throw new Error('SELLER006_ACCEPTANCE=1 is required');
const regression04=process.env.REGRESSION04_ACCEPTANCE==='1',safePrefix=regression04?'GYMFIT_REGRESSION_04_':'GYMFIT_DB_SELLER006_ACCEPTANCE_';
if(config.db.database==='GYMFIT_DB'||!config.db.database.startsWith(safePrefix))throw new Error('Refusing canonical database');
const uploadRoot=path.resolve(config.upload.dir);if(regression04?!uploadRoot.toUpperCase().includes('GYMFIT_REGRESSION_04_UPLOADS_'):!uploadRoot.toLowerCase().includes('seller006-acceptance'))throw new Error('SELLER-006 requires an isolated upload directory');
type Role='member'|'coach'|'admin'|'seller';type Account={id:number;email:string;password:string;token?:string};
const accounts:Record<string,Account>={},stamp=Date.now(),port=Number(process.env.ACCEPTANCE_PORT||5526),base=`http://127.0.0.1:${port}/api`;let server:Server|undefined,assertions=0,lastStatus=0;const suiteAbort=new AbortController();
const check=(value:boolean,message:string)=>{assertions++;if(!value)throw new Error(`${message}; last status=${lastStatus}`);};
async function call(method:string,url:string,key?:string,body?:unknown){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),regression04?5000:15000),stop=()=>controller.abort();suiteAbort.signal.addEventListener('abort',stop,{once:true});try{const multipart=body instanceof FormData,response=await fetch(base+url,{method,signal:controller.signal,headers:{...(multipart?{}:{'content-type':'application/json'}),...(key&&accounts[key].token?{authorization:`Bearer ${accounts[key].token}`}:{})},body:body===undefined?undefined:multipart?body:JSON.stringify(body)});lastStatus=response.status;let data:any={};try{data=await response.json();}catch{}return{status:response.status,data};}finally{clearTimeout(timer);suiteAbort.signal.removeEventListener('abort',stop);}}
async function expect(method:string,url:string,key:string|undefined,status:number,body?:unknown){const result=await call(method,url,key,body);check(result.status===status,`${method} ${url}: expected ${status}, got ${result.status}`);return result;}
async function seedUser(key:string,role:Role){const email=`seller006-${key}-${stamp}@example.test`,password=`Aa1!${crypto.randomBytes(12).toString('hex')}`,hash=await bcrypt.hash(password,12),r=await query<{id:number}>(`INSERT dbo.Users(email,password,name,role,is_active,email_verified,token_version) OUTPUT INSERTED.id VALUES(@email,@hash,@name,@role,1,1,0)`,{email,hash,name:`SELLER006 ${key}`,role});accounts[key]={id:Number(r.recordset[0].id),email,password};}
async function login(key:string){const r=await call('POST','/auth/login',undefined,{email:accounts[key].email,password:accounts[key].password});check(r.status===200,`${key} login`);accounts[key].token=String(r.data.data.accessToken);}
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');
function imagesForm(){const f=new FormData();f.append('images',new Blob([png],{type:'image/png'}),'seller006.png');return f;}
const orderBody=(variantId:number)=>({customerName:'Acceptance Buyer',customerPhone:'0900000000',shippingAddressLine1:'1 Test Street',shippingCity:'HCM',shippingCountry:'VN',items:[{variantId,quantity:1}]});
async function seedProduct(shopId:number,key:string,status='PENDING_REVIEW'){
  const ref=(await query<any>('SELECT (SELECT TOP 1 id FROM dbo.Categories WHERE is_active=1 ORDER BY id) category,(SELECT TOP 1 id FROM dbo.Brands WHERE is_active=1 ORDER BY is_generic DESC,id) brand')).recordset[0],sku=`SELLER006-${key}-${stamp}`;
  const product=(await query<any>(`INSERT dbo.Products(product_name,slug,description,sku,price,stock,brand_id,category_id,is_active,shop_id,moderation_status,submitted_at)
    OUTPUT INSERTED.id VALUES(@name,@slug,N'Acceptance moderation Product',@sku,100000,10,@brand,@category,@active,@shop,@status,CASE WHEN @status=N'DRAFT' THEN NULL ELSE SYSUTCDATETIME() END)`,
    {name:`SELLER006 ${key}`,slug:`seller006-${key.toLowerCase()}-${stamp}`,sku,brand:ref.brand,category:ref.category,active:status==='PUBLISHED'?1:0,shop:shopId,status})).recordset[0];
  const variant=(await query<any>(`INSERT dbo.ProductVariants(product_id,variant_name,sku,price,is_active,is_default,created_at,updated_at) OUTPUT INSERTED.id VALUES(@p,N'Default',@sku,100000,1,1,SYSUTCDATETIME(),SYSUTCDATETIME())`,{p:product.id,sku})).recordset[0];
  await query('INSERT dbo.Inventory(variant_id,on_hand,reserved,low_stock_threshold,updated_at) VALUES(@v,10,0,2,SYSUTCDATETIME())',{v:variant.id});
  await query(`INSERT dbo.ProductImages(product_id,image_url,alt_text,sort_order,is_primary,created_at) VALUES(@p,@url,N'Acceptance',0,1,SYSUTCDATETIME())`,{p:product.id,url:`/uploads/products/seller006-${key}-${stamp}.webp`});
  return{id:Number(product.id),variantId:Number(variant.id),categoryId:Number(ref.category),brandId:Number(ref.brand)};
}
async function dropDatabase(){if(process.env.SELLER006_KEEP_DB==='1')return;const pool=await new mssql.ConnectionPool({...config.db,database:'master'}).connect();try{await pool.request().batch(`IF DB_ID(N'${config.db.database}') IS NOT NULL BEGIN ALTER DATABASE [${config.db.database}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;DROP DATABASE [${config.db.database}];END`);}finally{await pool.close();}}

async function main(){
  const baseline=(await query<any>(`SELECT (SELECT COUNT(*) FROM dbo.Products) products,(SELECT COUNT(*) FROM dbo.ProductVariants) variants,(SELECT COUNT(*) FROM dbo.Inventory) inventory,(SELECT COUNT(*) FROM dbo.ProductImages) images,(SELECT COUNT(*) FROM dbo.OrderItems) orderItems`)).recordset[0];
  const migration=(await query<any>(`SELECT (SELECT COUNT(*) FROM dbo.SchemaMigrations) migrations,COL_LENGTH(N'dbo.Products',N'reviewed_at') reviewed,COL_LENGTH(N'dbo.Products',N'published_at') published,COL_LENGTH(N'dbo.Products',N'reviewed_by_user_id') reviewer,
    (SELECT COUNT(*) FROM dbo.ProductModerationHistory) history,(SELECT COUNT(*) FROM dbo.Products WHERE moderation_status=N'PUBLISHED') publishedProducts,
    (SELECT COUNT(*) FROM dbo.Products WHERE id=0 AND moderation_status=N'PUBLISHED') zeroPublished,
    (SELECT COUNT(*) FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.ProductModerationHistory') AND name IN(N'IX_ProductModerationHistory_Product_Created',N'IX_ProductModerationHistory_Status_Created')) historyIndexes,
    (SELECT COUNT(*) FROM sys.triggers WHERE name=N'TR_ProductModerationHistory_Immutable') immutableTrigger`)).recordset[0];
  check(Number(migration.migrations)===11,'0104 applied');check(migration.reviewed&&migration.published&&migration.reviewer,'moderation columns');check(Number(migration.history)===0,'no fake legacy history');check(Number(migration.publishedProducts)===Number(baseline.products)&&Number(migration.zeroPublished)===1,'legacy PUBLISHED including Product 0');check(Number(migration.historyIndexes)===2&&Number(migration.immutableTrigger)===1,'history index and trigger');
  for(const [key,role] of [['admin','admin'],['member','member'],['coach','coach'],['sellerA','seller'],['sellerB','seller']] as [string,Role][])await seedUser(key,role);for(const key of Object.keys(accounts))await login(key);
  await query(`INSERT dbo.Shops(owner_user_id,name,slug,status,is_verified,is_system) VALUES(@a,N'Seller A',@as,N'ACTIVE',1,0),(@b,N'Seller B',@bs,N'ACTIVE',1,0)`,{a:accounts.sellerA.id,as:`seller006-a-${stamp}`,b:accounts.sellerB.id,bs:`seller006-b-${stamp}`});
  const shops=(await query<any>('SELECT id,owner_user_id FROM dbo.Shops WHERE owner_user_id IN(@a,@b)',{a:accounts.sellerA.id,b:accounts.sellerB.id})).recordset,shopA=shops.find((x:any)=>x.owner_user_id===accounts.sellerA.id),shopB=shops.find((x:any)=>x.owner_user_id===accounts.sellerB.id);
  const filter=await expect('GET','/seller/products/filters','sellerA',200),category=filter.data.data.categories[0],brand=filter.data.data.brands[0],payload={name:'SELLER006 API Product',slug:`seller006-api-${stamp}`,description:'Moderation API fixture',categoryId:category.id,brandId:brand.id,defaultVariant:{name:'Default',sku:`SELLER006-API-${stamp}`,price:100000,initialOnHand:10,lowStockThreshold:2}};
  let result=await expect('POST','/seller/products','sellerA',201,payload);const apiProduct=result.data.data;await expect('POST',`/seller/products/${apiProduct.id}/images`,'sellerA',201,imagesForm());await expect('POST',`/seller/products/${apiProduct.id}/submit`,'sellerA',200);
  await expect('PATCH',`/seller/products/${apiProduct.id}`,'sellerA',400,{reviewedAt:new Date().toISOString()});await expect('PATCH',`/seller/products/${apiProduct.id}`,'sellerA',400,{publishedAt:new Date().toISOString()});await expect('PATCH',`/seller/products/${apiProduct.id}`,'sellerA',400,{moderationStatus:'PUBLISHED'});await expect('PATCH',`/seller/products/${apiProduct.id}`,'sellerA',400,{isActive:true});
  result=await expect('GET','/admin/product-moderation','admin',200);check(result.data.data.some((x:any)=>x.id===apiProduct.id),'default inbox sees pending');check(!result.data.data.some((x:any)=>x.id===0),'default inbox excludes Official');
  await expect('GET','/admin/product-moderation?sortBy=drop_table','admin',400);await expect('GET','/admin/product-moderation?unknown=1','admin',400);await expect('GET','/admin/product-moderation','sellerA',403);await expect('GET','/admin/product-moderation','member',403);await expect('GET','/admin/product-moderation','coach',403);
  for(const q of [`status=PENDING_REVIEW`,`shopId=${shopA.id}`,`categoryId=${category.id}`,`brandId=${brand.id}`,`search=${encodeURIComponent(apiProduct.slug)}`,`submittedFrom=2020-01-01&submittedTo=2099-01-01`,`page=1&limit=1&sortBy=createdAt&sortOrder=asc`]){result=await expect('GET',`/admin/product-moderation?${q}`,'admin',200);check(result.data.data.some((x:any)=>x.id===apiProduct.id)||q.includes('limit=1'),'inbox filter works');}
  result=await expect('GET',`/admin/product-moderation/${apiProduct.id}`,'admin',200);check(result.data.data.readiness.ready&&result.data.data.variants.length&&result.data.data.images.length,'detail preview and readiness');check(!JSON.stringify(result.data).match(/password|accessToken|refreshToken/i),'detail has no auth secrets');await expect('GET','/admin/product-moderation/0','admin',404);
  await expect('POST',`/admin/product-moderation/${apiProduct.id}/approve`,'sellerA',403,{});await expect('POST',`/admin/product-moderation/${apiProduct.id}/approve`,'member',403,{});await expect('POST',`/admin/product-moderation/${apiProduct.id}/approve`,'coach',403,{});
  await expect('POST',`/admin/product-moderation/${apiProduct.id}/approve`,'admin',400,{status:'PUBLISHED'});result=await expect('POST',`/admin/product-moderation/${apiProduct.id}/approve`,'admin',200,{});check(result.data.data.moderationStatus==='PUBLISHED'&&result.data.data.isActive,'approve publishes and activates');check(result.data.data.reviewedAt&&result.data.data.publishedAt&&!result.data.data.reviewReason,'approve timestamps');
  let state=(await query<any>('SELECT moderation_status,is_active,reviewed_by_user_id FROM dbo.Products WHERE id=@id',{id:apiProduct.id})).recordset[0];check(state.moderation_status==='PUBLISHED'&&state.is_active&&Number(state.reviewed_by_user_id)===accounts.admin.id,'approve persisted reviewer');check(Number((await query<any>(`SELECT COUNT(*) count FROM dbo.ProductModerationHistory WHERE product_id=@id AND from_status=N'PENDING_REVIEW' AND to_status=N'PUBLISHED'`,{id:apiProduct.id})).recordset[0].count)===1,'approve history');check(Number((await query<any>(`SELECT COUNT(*) count FROM dbo.AuditLogs WHERE entity_id=@id AND action=N'product_moderation.approved'`,{id:apiProduct.id})).recordset[0].count)===1,'approve audit');
  await expect('GET',`/products/${apiProduct.id}`,undefined,200);result=await expect('GET',`/seller/products/${apiProduct.id}`,'sellerA',200);check(result.data.data.publishedAt&&result.data.data.history.length>=2,'Seller sees safe timestamps/history');await expect('GET',`/seller/products/${apiProduct.id}`,'sellerB',404);await expect('POST',`/seller/products/${apiProduct.id}/approve`,'sellerA',404,{});await expect('PATCH',`/admin/products/${apiProduct.id}`,'admin',409,{is_active:false});await expect('POST',`/admin/product-moderation/${apiProduct.id}/approve`,'admin',409,{});
  const draft=await seedProduct(shopA.id,'Draft','DRAFT');await expect('POST',`/admin/product-moderation/${draft.id}/approve`,'admin',409,{});await expect('POST','/admin/product-moderation/0/approve','admin',404,{});
  const broken=await seedProduct(shopA.id,'Broken');await query('UPDATE dbo.ProductImages SET is_primary=0 WHERE product_id=@id',{id:broken.id});await expect('POST',`/admin/product-moderation/${broken.id}/approve`,'admin',409,{});
  const concurrency=await seedProduct(shopA.id,'Concurrent');const approvals=await Promise.all([call('POST',`/admin/product-moderation/${concurrency.id}/approve`,'admin',{}),call('POST',`/admin/product-moderation/${concurrency.id}/approve`,'admin',{})]);check(approvals.filter(x=>x.status===200).length===1&&approvals.filter(x=>x.status===409).length===1,'double approve serialized');
  const contradiction=await seedProduct(shopA.id,'Contradiction');const opposite=await Promise.all([call('POST',`/admin/product-moderation/${contradiction.id}/approve`,'admin',{}),call('POST',`/admin/product-moderation/${contradiction.id}/reject`,'admin',{reason:'Concurrent rejection'})]);check(opposite.filter(x=>x.status===200).length===1&&opposite.filter(x=>x.status===409).length===1,'approve/reject serialized');
  const rollback=await seedProduct(shopA.id,'Rollback');await query(`CREATE TRIGGER dbo.TR_SELLER006_AuditFailure ON dbo.AuditLogs AFTER INSERT AS IF EXISTS(SELECT 1 FROM inserted WHERE action=N'product_moderation.approved') THROW 51999,'forced audit failure',1;`);result=await call('POST',`/admin/product-moderation/${rollback.id}/approve`,'admin',{});check(result.status===500&&!JSON.stringify(result.data).match(/51999|TR_SELLER006|stack|SELECT|INSERT/i),'SQL failure is hidden');await query('DROP TRIGGER dbo.TR_SELLER006_AuditFailure');state=(await query<any>('SELECT moderation_status,is_active FROM dbo.Products WHERE id=@id',{id:rollback.id})).recordset[0];check(state.moderation_status==='PENDING_REVIEW'&&!state.is_active,'audit failure rolls back Product');check(Number((await query<any>('SELECT COUNT(*) count FROM dbo.ProductModerationHistory WHERE product_id=@id',{id:rollback.id})).recordset[0].count)===0,'audit failure rolls back history');
  const rejected=await seedProduct(shopA.id,'Reject');await expect('POST',`/admin/product-moderation/${rejected.id}/reject`,'admin',400,{});await expect('POST',`/admin/product-moderation/${rejected.id}/reject`,'admin',400,{reason:'  '});result=await expect('POST',`/admin/product-moderation/${rejected.id}/reject`,'admin',200,{reason:'Improve safe product content'});check(result.data.data.moderationStatus==='REJECTED'&&!result.data.data.isActive&&result.data.data.reviewReason==='Improve safe product content','reject state/reason');await expect('GET',`/products/${rejected.id}`,undefined,404);result=await expect('GET',`/seller/products/${rejected.id}`,'sellerA',200);check(result.data.data.reviewReason==='Improve safe product content','owner sees reason');await expect('GET',`/seller/products/${rejected.id}`,'sellerB',404);await expect('PATCH',`/seller/products/${rejected.id}`,'sellerA',200,{description:'Improved'});const oldSubmitted=String(result.data.data.submittedAt||'');await expect('POST',`/seller/products/${rejected.id}/submit`,'sellerA',200);state=(await query<any>('SELECT moderation_status,review_reason,submitted_at FROM dbo.Products WHERE id=@id',{id:rejected.id})).recordset[0];check(state.moderation_status==='PENDING_REVIEW'&&state.review_reason===null&&String(state.submitted_at)!==oldSubmitted,'resubmit clears reason and refreshes submitted');check(Number((await query<any>(`SELECT COUNT(*) count FROM dbo.ProductModerationHistory WHERE product_id=@id AND to_status IN(N'REJECTED',N'PENDING_REVIEW')`,{id:rejected.id})).recordset[0].count)===2,'reject history retained plus resubmit');
  await query(`UPDATE dbo.Shops SET status=N'SUSPENDED' WHERE id=@id`,{id:shopA.id});await expect('POST',`/admin/product-moderation/${rejected.id}/approve`,'admin',409,{});await expect('POST',`/admin/product-moderation/${rejected.id}/reject`,'admin',200,{reason:'Reject allowed while Shop suspended'});await query(`UPDATE dbo.Shops SET status=N'ACTIVE' WHERE id=@id`,{id:shopA.id});
  const commerce=await seedProduct(shopA.id,'Commerce','PUBLISHED');result=await expect('POST','/orders','member',201,orderBody(commerce.variantId));check(Boolean(result.data.data.id),'published Product order succeeds');const beforeSuspend=(await query<any>('SELECT on_hand,reserved FROM dbo.Inventory WHERE variant_id=@id',{id:commerce.variantId})).recordset[0];await expect('POST',`/admin/product-moderation/${commerce.id}/suspend`,'admin',400,{});await expect('POST',`/admin/product-moderation/${commerce.id}/suspend`,'admin',200,{reason:'Safety suspension'});state=(await query<any>('SELECT moderation_status,is_active,review_reason FROM dbo.Products WHERE id=@id',{id:commerce.id})).recordset[0];check(state.moderation_status==='SUSPENDED'&&!state.is_active&&state.review_reason==='Safety suspension','suspend state');const afterSuspend=(await query<any>('SELECT on_hand,reserved FROM dbo.Inventory WHERE variant_id=@id',{id:commerce.variantId})).recordset[0];check(beforeSuspend.on_hand===afterSuspend.on_hand&&beforeSuspend.reserved===afterSuspend.reserved,'suspend does not mutate Inventory');await expect('GET',`/products/${commerce.id}`,undefined,404);await expect('POST','/orders','member',404,orderBody(commerce.variantId));check((await query<any>('SELECT reserved FROM dbo.Inventory WHERE variant_id=@id',{id:commerce.variantId})).recordset[0].reserved===afterSuspend.reserved,'failed stale cart does not reserve');await expect('PATCH',`/seller/products/${commerce.id}`,'sellerA',409,{description:'blocked'});await expect('POST',`/seller/products/${commerce.id}/variants/${commerce.variantId}/inventory/adjustments`,'sellerA',201,{quantityDelta:1,reason:'Allowed while Product suspended'});await expect('POST',`/admin/product-moderation/${commerce.id}/suspend`,'admin',409,{reason:'again'});
  await query(`UPDATE dbo.Shops SET status=N'SUSPENDED' WHERE id=@id`,{id:shopA.id});await expect('POST',`/admin/product-moderation/${commerce.id}/republish`,'admin',409,{});await query(`UPDATE dbo.Shops SET status=N'ACTIVE' WHERE id=@id`,{id:shopA.id});await expect('POST',`/admin/product-moderation/${commerce.id}/republish`,'admin',200,{});await expect('GET',`/products/${commerce.id}`,undefined,200);await expect('POST','/orders','member',201,orderBody(commerce.variantId));await expect('POST',`/admin/product-moderation/${commerce.id}/republish`,'admin',409,{});
  const immutableId=(await query<any>('SELECT TOP 1 id FROM dbo.ProductModerationHistory ORDER BY id')).recordset[0].id;for(const statement of [`UPDATE dbo.ProductModerationHistory SET reason=N'tamper' WHERE id=@id`,'DELETE dbo.ProductModerationHistory WHERE id=@id']){let blocked=false;try{await query(statement,{id:immutableId});}catch{blocked=true;}check(blocked,'history is append-only');}
  await expect('POST','/orders','member',404,orderBody(draft.variantId));await expect('POST','/orders','member',404,orderBody(broken.variantId));await expect('POST','/orders','member',404,orderBody(rejected.variantId));const shopSuspendedProduct=await seedProduct(shopB.id,'ShopSuspended','PUBLISHED');await query(`UPDATE dbo.Shops SET status=N'SUSPENDED' WHERE id=@id`,{id:shopB.id});await expect('POST','/orders','member',404,orderBody(shopSuspendedProduct.variantId));await query(`UPDATE dbo.Shops SET status=N'ACTIVE' WHERE id=@id`,{id:shopB.id});
  const adminList=await expect('GET','/admin/products?page=1&limit=100','admin',200);check(Number(adminList.data.pagination.total)>=Number(baseline.products),'Admin Product global regression');await expect('GET','/admin/products/0','admin',200);
  const adminCreate=await expect('POST','/admin/products','admin',201,{product_name:'SELLER006 admin regression',sku:`SELLER006-ADMIN-${stamp}`,price:100000,stock:2,category_id:category.id}),adminId=Number(adminCreate.data.data.id),adminDefaultVariant=Number(adminCreate.data.data.display_variant.id);state=(await query<any>('SELECT p.moderation_status,s.is_system FROM dbo.Products p JOIN dbo.Shops s ON s.id=p.shop_id WHERE p.id=@id',{id:adminId})).recordset[0];check(state.moderation_status==='PUBLISHED'&&state.is_system,'Admin create stays Official/PUBLISHED');
  const adminVariant=await expect('POST',`/admin/products/${adminId}/variants`,'admin',201,{variant_name:'Extra',sku:`SELLER006-ADMIN-EXTRA-${stamp}`,price:110000,initial_on_hand:1});await expect('PATCH',`/admin/variants/${adminVariant.data.data.id}`,'admin',200,{price:120000});await expect('DELETE',`/admin/variants/${adminVariant.data.data.id}`,'admin',200);
  const adminImage=await expect('POST',`/admin/products/${adminId}/images`,'admin',201,imagesForm()),adminImageId=adminImage.data.data.images[0].id;await expect('PATCH',`/admin/products/${adminId}/images/${adminImageId}/primary`,'admin',200);await expect('DELETE',`/admin/products/${adminId}/images/${adminImageId}`,'admin',200);await expect('DELETE',`/admin/products/${adminId}`,'admin',200);
  await expect('POST',`/admin/variants/1/inventory/adjustments`,'admin',201,{type:'MANUAL_CORRECTION',quantityDelta:1,reason:'SELLER006 Admin inventory regression'});await expect('POST',`/admin/variants/1/inventory/adjustments`,'admin',201,{type:'MANUAL_CORRECTION',quantityDelta:-1,reason:'SELLER006 Admin inventory restore'});check(adminDefaultVariant>0,'Admin default Variant created');
  const transitionEvidence=(await query<any>(`SELECT
    (SELECT COUNT(*) FROM dbo.ProductModerationHistory WHERE product_id=@id AND to_status=N'SUSPENDED') suspendedHistory,
    (SELECT COUNT(*) FROM dbo.ProductModerationHistory WHERE product_id=@id AND from_status=N'SUSPENDED' AND to_status=N'PUBLISHED') republishHistory,
    (SELECT COUNT(*) FROM dbo.AuditLogs WHERE entity_id=@id AND action=N'product_moderation.suspended') suspendAudit,
    (SELECT COUNT(*) FROM dbo.AuditLogs WHERE entity_id=@id AND action=N'product_moderation.republished') republishAudit`,{id:commerce.id})).recordset[0];check(Object.values(transitionEvidence).every(value=>Number(value)===1),'suspend/republish history and audit');
  const final=(await query<any>(`SELECT (SELECT COUNT(*) FROM dbo.Products WHERE id<167 AND moderation_status<>N'PUBLISHED') legacyChanged,(SELECT COUNT(*) FROM dbo.ProductModerationHistory h JOIN dbo.Products p ON p.id=h.product_id WHERE p.id<167) fakeLegacyHistory,(SELECT COUNT(*) FROM dbo.Products p LEFT JOIN dbo.Shops s ON s.id=p.shop_id WHERE s.id IS NULL) orphans,(SELECT COUNT(*) FROM dbo.Products WHERE (brand_id IS NULL AND brand_request_id IS NULL) OR (brand_id IS NOT NULL AND brand_request_id IS NOT NULL)) invalidBrand,(SELECT COUNT(*) FROM dbo.OrderItems) orderItems`)).recordset[0];
  check(Number(final.legacyChanged)===0&&Number(final.fakeLegacyHistory)===0,'legacy Product/history unchanged');check(Number(final.orphans)===0&&Number(final.invalidBrand)===0,'ownership and Brand invariants');check(Number(final.orderItems)>=Number(baseline.orderItems)+2,'commerce regression created expected isolated orders');
  console.log(`[SELLER-006 ACCEPTANCE PASS] assertions=${assertions} database=${config.db.database}`);
}
async function run(){let timer:NodeJS.Timeout|undefined;const deadline=regression04?60000:300000;try{const{default:app}=await import('../app');server=app.listen(port,'127.0.0.1');await new Promise<void>((resolve,reject)=>{server!.once('listening',resolve);server!.once('error',reject);});await Promise.race([main(),new Promise<never>((_,reject)=>{timer=setTimeout(()=>{suiteAbort.abort();reject(new Error(`Suite timed out after ${deadline}ms`));},deadline);})]);return 0;}catch(error){console.error('[SELLER-006 ACCEPTANCE FAIL]',error instanceof Error?error.message:error);return 1;}finally{if(timer)clearTimeout(timer);if(server){server.closeAllConnections();await new Promise<void>(resolve=>server!.close(()=>resolve()));}await closePool();await fs.rm(uploadRoot,{recursive:true,force:true,maxRetries:5,retryDelay:100});await dropDatabase();}}
void run().then(code=>{process.exitCode=code;});
