import crypto from "crypto";
import bcrypt from "bcryptjs";
import * as mssql from "mssql";
import type { Server } from "http";
import { config } from "../config/config";
import { closePool, query } from "../config/database";

if(process.env.SELLER011A_ACCEPTANCE!=="1")throw new Error("SELLER011A_ACCEPTANCE=1 is required");
if(!/^GYMFIT_DB_SELLER011A_ACCEPTANCE_[A-Za-z0-9_]+$/.test(config.db.database))throw new Error("Refusing unsafe database");
const port=Number(process.env.ACCEPTANCE_PORT||5542),base=`http://127.0.0.1:${port}/api`,stamp=Date.now();
let server:Server|undefined,assertions=0,lastStatus=0;
const check=(ok:boolean,message:string)=>{assertions++;if(!ok)throw new Error(`Assertion ${assertions}: ${message}; status=${lastStatus}`);};
async function call(method:string,path:string,token?:string,body?:unknown){
  const response=await fetch(base+path,{method,headers:{...(token?{authorization:`Bearer ${token}`}:{}) ,...(body===undefined?{}:{"content-type":"application/json"})},body:body===undefined?undefined:JSON.stringify(body)});
  lastStatus=response.status;let data:any={};try{data=await response.json();}catch{}return{status:response.status,data};
}
async function user(role:string,key:string){
  const email=`seller011a-${key}-${stamp}@example.test`,password=`Aa1!${crypto.randomBytes(8).toString("hex")}`,hash=await bcrypt.hash(password,12);
  const row=(await query<any>("INSERT dbo.Users(email,password,name,role,is_active,email_verified,token_version) OUTPUT INSERTED.id VALUES(@email,@hash,@name,@role,1,1,0)",{email,hash,name:`SELLER011A ${key}`,role})).recordset[0];
  const login=await call("POST","/auth/login",undefined,{email,password});check(login.status===200,`${key} login`);return{id:Number(row.id),token:String(login.data.data.accessToken)};
}
async function shop(owner:number,key:string){return Number((await query<any>("INSERT dbo.Shops(owner_user_id,name,slug,status,is_verified,is_system) OUTPUT INSERTED.id VALUES(@owner,@name,@slug,N'ACTIVE',1,0)",{owner,name:`Complaint Shop ${key}`,slug:`seller011a-${key}-${stamp}`})).recordset[0].id);}
type Fixture={orderId:number;shopOrderId:number;itemId:number;settlementId:number;inventoryId:number;variantId:number;price:number};
async function fixture(input:{buyer:number;shop:number;product:number;variant:number;key:string;days?:number;settlement?:"PENDING"|"ELIGIBLE"|"HELD";delivered?:boolean;quantity?:number}):Promise<Fixture>{
  const days=input.days??1,delivered=input.delivered!==false,quantity=input.quantity??2,price=100000;
  const product=(await query<any>("SELECT p.product_name name,v.variant_name variantName,v.sku FROM dbo.Products p JOIN dbo.ProductVariants v ON v.id=@variant WHERE p.id=@product",{product:input.product,variant:input.variant})).recordset[0];
  const order=(await query<any>(`INSERT dbo.Orders(order_number,user_id,customer_name,customer_email,subtotal,total_amount,currency,order_status,payment_status,payment_provider,logistics_status,created_at,updated_at)
    VALUES(@number,@buyer,N'Buyer',N'buyer@example.test',@total,@total,N'VND',@orderStatus,N'PAID',N'BANK_TRANSFER',@logistics,SYSUTCDATETIME(),SYSUTCDATETIME());SELECT CAST(SCOPE_IDENTITY() AS INT) id`,
    {number:`S011A-${input.key}-${stamp}`,buyer:input.buyer,total:price*quantity,orderStatus:delivered?"DELIVERED":"PROCESSING",logistics:delivered?"DELIVERED":"WAITING_FOR_SHOPS"})).recordset[0];
  const commission=price*quantity*0.05,net=price*quantity-commission;
  const child=(await query<any>(`INSERT dbo.ShopOrders(order_id,shop_id,status,subtotal,delivered_at,commission_rate_snapshot,commission_base_amount,commission_amount,seller_net_before_adjustment,commission_snapshotted_at,created_at,updated_at)
    VALUES(@order,@shop,@status,@total,CASE WHEN @delivered=1 THEN DATEADD(DAY,-@days,SYSUTCDATETIME()) END,500,@total,@commission,@net,SYSUTCDATETIME(),SYSUTCDATETIME(),SYSUTCDATETIME());SELECT CAST(SCOPE_IDENTITY() AS INT) id`,
    {order:order.id,shop:input.shop,status:delivered?"HUB_CHECK_PASSED":"PREPARING",total:price*quantity,commission,net,delivered,days})).recordset[0];
  const item=(await query<any>(`INSERT dbo.OrderItems(order_id,shop_order_id,product_id,variant_id,product_name,variant_name,sku,quantity,unit_price,line_total,created_at)
    VALUES(@order,@child,@product,@variant,@name,@variantName,@sku,@quantity,@price,@total,SYSUTCDATETIME());SELECT CAST(SCOPE_IDENTITY() AS INT) id`,
    {order:order.id,child:child.id,product:input.product,variant:input.variant,name:product.name,variantName:product.variantName,sku:product.sku,quantity,price,total:price*quantity})).recordset[0];
  const settlementStatus=input.settlement||"PENDING",held=settlementStatus==="HELD";
  const settlement=(await query<any>(`DECLARE @earned DATETIME2=DATEADD(DAY,-@days,SYSUTCDATETIME());INSERT dbo.ShopOrderSettlements(shop_order_id,shop_id,status,commission_rate_snapshot,gross_merchandise_amount,commission_amount,net_before_adjustment,applied_adjustment_amount,payable_amount,earned_at,eligible_at,held_at,hold_reason,hold_source_type,hold_source_id,created_at,updated_at)
    OUTPUT INSERTED.id VALUES(@child,@shop,@status,500,@gross,@commission,@net,0,@net,@earned,DATEADD(DAY,7,@earned),CASE WHEN @held=1 THEN SYSUTCDATETIME() END,CASE WHEN @held=1 THEN N'Manual fixture hold' END,CASE WHEN @held=1 THEN N'MANUAL' END,CASE WHEN @held=1 THEN N'fixture' END,SYSUTCDATETIME(),SYSUTCDATETIME())`,
    {child:child.id,shop:input.shop,status:settlementStatus,gross:price*quantity,commission,net,days,held})).recordset[0];
  const inventory=(await query<any>("SELECT id FROM dbo.Inventory WHERE variant_id=@variant",{variant:input.variant})).recordset[0];
  return{orderId:Number(order.id),shopOrderId:Number(child.id),itemId:Number(item.id),settlementId:Number(settlement.id),inventoryId:Number(inventory.id),variantId:input.variant,price};
}
const create=(itemId:number,token:string,quantity=1)=>call("POST","/complaints",token,{orderItemId:itemId,category:"DAMAGED",affectedQuantity:quantity,description:"Sản phẩm nhận được bị hư hỏng rõ ràng."});
const start=(id:number,token:string)=>call("POST",`/admin/complaints/${id}/start-review`,token,{reason:"Admin bắt đầu kiểm tra complaint"});
const sellerFault=(id:number,token:string,quantity=1)=>call("POST",`/admin/complaints/${id}/decisions/seller-fault`,token,{reason:"Seller đóng gói sai hoặc hàng không đạt",replacementQuantity:quantity});
const transition=(id:number,token:string,action:string,reason?:string)=>call("POST",`/admin/complaints/replacements/${id}/actions`,token,{action,...(reason?{reason}:{})});
async function main(){
  const admin=await user("admin","admin"),sellerA=await user("seller","a"),sellerB=await user("seller","b"),buyer=await user("member","buyer"),otherBuyer=await user("member","other");
  const shopA=await shop(sellerA.id,"a"),shopB=await shop(sellerB.id,"b");
  const catalog=(await query<any>("SELECT TOP 2 p.id productId,v.id variantId FROM dbo.Products p JOIN dbo.ProductVariants v ON v.product_id=p.id ORDER BY CASE WHEN p.id=0 THEN 0 ELSE 1 END,p.id")).recordset;
  check(catalog[0].productId===0,"Product ID 0 fixture exists");
  await query("UPDATE dbo.Products SET shop_id=@shop WHERE id=@product;UPDATE dbo.Inventory SET on_hand=20,reserved=0 WHERE variant_id=@variant",{shop:shopA,product:catalog[0].productId,variant:catalog[0].variantId});
  await query("UPDATE dbo.Products SET shop_id=@shop WHERE id=@product;UPDATE dbo.Inventory SET on_hand=20,reserved=0 WHERE variant_id=@variant",{shop:shopB,product:catalog[1].productId,variant:catalog[1].variantId});
  const mainFx=await fixture({buyer:buyer.id,shop:shopA,product:catalog[0].productId,variant:catalog[0].variantId,key:"main"});
  check((await create(mainFx.itemId,otherBuyer.token)).status===404,"cross-buyer complaint blocked");
  check((await create(mainFx.itemId,buyer.token,3)).status===400,"affected quantity validated");
  let result=await create(mainFx.itemId,buyer.token);check(result.status===201,"buyer creates own delivered complaint");const main=result.data.data;check(main.faultParty==="UNDETERMINED"&&main.status==="OPEN","complaint starts open and undetermined");
  check((await create(mainFx.itemId,buyer.token)).status===409,"duplicate complaint blocked");
  check((await call("GET",`/complaints/${main.id}`,otherBuyer.token)).status===404,"cross-buyer detail IDOR blocked");
  check((await query<any>("SELECT status FROM dbo.ShopOrderSettlements WHERE id=@id",{id:mainFx.settlementId})).recordset[0].status==="PENDING","OPEN does not hold settlement");
  check((await start(main.id,sellerA.token)).status===403,"seller cannot start review");
  check((await start(main.id,admin.token)).status===200,"OPEN to UNDER_REVIEW");
  check((await query<any>("SELECT status FROM dbo.ShopOrderSettlements WHERE id=@id",{id:mainFx.settlementId})).recordset[0].status==="PENDING","UNDER_REVIEW does not hold settlement");
  check((await sellerFault(main.id,admin.token,3)).status===400,"replacement quantity cannot exceed affected");
  result=await sellerFault(main.id,admin.token);check(result.status===200,"admin seller fault creates replacement");const decided=result.data.data;
  check(decided.status==="REPLACEMENT_REQUIRED"&&decided.replacementStatus==="REQUIRED","replacement approved by admin");
  let state=(await query<any>("SELECT status,hold_source_type sourceType,hold_source_id sourceId FROM dbo.ShopOrderSettlements WHERE id=@id",{id:mainFx.settlementId})).recordset[0];check(state.status==="HELD"&&state.sourceType==="COMPLAINT"&&state.sourceId===String(main.id),"seller fault atomically holds unpaid settlement");
  const replacementCount=Number((await query<any>("SELECT COUNT(*) count FROM dbo.ComplaintReplacements WHERE complaint_id=@id",{id:main.id})).recordset[0].count);
  check((await sellerFault(main.id,admin.token)).status===200&&replacementCount===1,"seller-fault retry idempotent");
  check((await call("POST",`/admin/marketplace-finance/settlements/${mainFx.settlementId}/release`,admin.token,{reason:"Unsafe release"})).status===409,"manual release blocked by unresolved seller fault");
  check((await call("GET",`/seller/complaints/${main.id}`,sellerB.token)).status===404,"cross-shop seller detail blocked");
  check((await call("POST",`/seller/complaints/replacements/${decided.replacementId}/ready-for-pickup`,sellerB.token)).status===404,"cross-shop replacement action blocked");
  check((await transition(decided.replacementId,sellerA.token,"PICKED_UP")).status===403,"seller cannot admin transition");
  const before=Number((await query<any>("SELECT on_hand value FROM dbo.Inventory WHERE id=@id",{id:mainFx.inventoryId})).recordset[0].value);
  check((await call("POST",`/seller/complaints/replacements/${decided.replacementId}/ready-for-pickup`,sellerA.token)).status===200,"seller consumes replacement inventory");
  check((await call("POST",`/seller/complaints/replacements/${decided.replacementId}/ready-for-pickup`,sellerA.token)).status===200,"ready retry accepted");
  const after=Number((await query<any>("SELECT on_hand value FROM dbo.Inventory WHERE id=@id",{id:mainFx.inventoryId})).recordset[0].value);
  check(before-after===1&&Number((await query<any>("SELECT COUNT(*) count FROM dbo.InventoryAdjustments WHERE reference_type=N'COMPLAINT_REPLACEMENT' AND reference_id=@id",{id:String(decided.replacementId)})).recordset[0].count)===1,"inventory consumed exactly once");
  check((await transition(decided.replacementId,admin.token,"SHIPPED")).status===409,"skipped replacement state blocked");
  for(const action of ["PICKED_UP","IN_TRANSIT_TO_HUB","RECEIVED_AT_HUB"]){check((await transition(decided.replacementId,admin.token,action)).status===200,`main ${action}`);}
  check((await transition(decided.replacementId,admin.token,"HUB_CHECK_FAILED")).status===400,"hub fail requires reason");
  check((await transition(decided.replacementId,admin.token,"HUB_CHECK_FAILED","Failed first hub check")).status===200,"hub fail stored");
  for(const action of ["HUB_CHECK_PASSED","SHIPPED","DELIVERED"]){check((await transition(decided.replacementId,admin.token,action)).status===200,`main ${action}`);}
  state=(await query<any>("SELECT c.status complaintStatus,st.status settlementStatus FROM dbo.MarketplaceComplaints c JOIN dbo.ShopOrderSettlements st ON st.id=c.settlement_id WHERE c.id=@id",{id:main.id})).recordset[0];check(state.complaintStatus==="RESOLVED"&&state.settlementStatus==="PENDING","delivery resolves complaint and releases future settlement");
  const undelivered=await fixture({buyer:buyer.id,shop:shopA,product:catalog[0].productId,variant:catalog[0].variantId,key:"undelivered",delivered:false});check((await create(undelivered.itemId,buyer.token)).status===409,"undelivered complaint blocked");
  const old=await fixture({buyer:buyer.id,shop:shopA,product:catalog[0].productId,variant:catalog[0].variantId,key:"old",days:8});check((await create(old.itemId,buyer.token)).status===409,"post-window manual support boundary");
  const paidFx=await fixture({buyer:buyer.id,shop:shopA,product:catalog[0].productId,variant:catalog[0].variantId,key:"paid"});result=await create(paidFx.itemId,buyer.token);const paidComplaint=result.data.data;await query("UPDATE dbo.ShopOrderSettlements SET status=N'PAID',paid_at=SYSUTCDATETIME(),paid_by=@admin WHERE id=@id",{id:paidFx.settlementId,admin:admin.id});await start(paidComplaint.id,admin.token);result=await sellerFault(paidComplaint.id,admin.token);check(result.status===200&&result.data.data.settlementStatus==="PAID","seller fault does not reopen paid settlement");
  check(Number((await query<any>("SELECT COUNT(*) count FROM dbo.SettlementAdjustments WHERE source_paid_settlement_id=@id",{id:paidFx.settlementId})).recordset[0].count)===0,"no automatic paid carry-forward adjustment");
  const paidBoundary=await fixture({buyer:buyer.id,shop:shopA,product:catalog[0].productId,variant:catalog[0].variantId,key:"paid-boundary"});await query("UPDATE dbo.ShopOrderSettlements SET status=N'PAID',paid_at=SYSUTCDATETIME(),paid_by=@admin WHERE id=@id",{id:paidBoundary.settlementId,admin:admin.id});check((await create(paidBoundary.itemId,buyer.token)).status===409,"paid settlement creation uses manual support boundary");
  const buyerFaultFx=await fixture({buyer:buyer.id,shop:shopA,product:catalog[0].productId,variant:catalog[0].variantId,key:"buyer-fault"});result=await create(buyerFaultFx.itemId,buyer.token);await start(result.data.data.id,admin.token);check((await call("POST",`/admin/complaints/${result.data.data.id}/decisions/buyer-fault`,admin.token,{reason:"Buyer misuse confirmed"})).status===200,"buyer fault decision");state=(await query<any>("SELECT c.status complaintStatus,st.status settlementStatus FROM dbo.MarketplaceComplaints c JOIN dbo.ShopOrderSettlements st ON st.id=c.settlement_id WHERE c.id=@id",{id:result.data.data.id})).recordset[0];check(state.complaintStatus==="REJECTED"&&state.settlementStatus==="PENDING","buyer fault rejects without seller hold");
  const gymFx=await fixture({buyer:buyer.id,shop:shopA,product:catalog[0].productId,variant:catalog[0].variantId,key:"gym"});result=await create(gymFx.itemId,buyer.token);await start(result.data.data.id,admin.token);check((await call("POST",`/admin/complaints/${result.data.data.id}/decisions/gymfit-carrier`,admin.token,{reason:"Carrier handling damage"})).status===200,"GymFit/carrier decision");check((await call("POST",`/admin/complaints/${result.data.data.id}/resolve`,admin.token,{resolutionType:"MANUAL_SUPPORT",reason:"Resolved by GymFit support"})).status===200,"GymFit fault manual resolution");check((await query<any>("SELECT status FROM dbo.ShopOrderSettlements WHERE id=@id",{id:gymFx.settlementId})).recordset[0].status==="PENDING","GymFit fault does not deduct seller");
  const refundFx=await fixture({buyer:buyer.id,shop:shopA,product:catalog[0].productId,variant:catalog[0].variantId,key:"refund"});result=await create(refundFx.itemId,buyer.token,2);const refundComplaint=result.data.data;await start(refundComplaint.id,admin.token);result=await sellerFault(refundComplaint.id,admin.token,2);const failed=result.data.data;check((await call("POST",`/admin/complaints/${refundComplaint.id}/refund-fallback`,admin.token,{reason:"Too early"})).status===409,"refund cannot be initial seller-fault resolution");check((await transition(failed.replacementId,admin.token,"FAILED","Seller cannot supply replacement")).status===200,"replacement can fail with reason");check((await call("POST",`/admin/complaints/${refundComplaint.id}/refund-fallback`,admin.token,{amount:200001,reason:"Excess"})).status===400,"refund capped by original snapshot");result=await call("POST",`/admin/complaints/${refundComplaint.id}/refund-fallback`,admin.token,{reason:"Replacement unavailable"});check(result.status===201,"failed replacement enables refund fallback");const refundId=result.data.data.refundId;const refund=(await query<any>("SELECT merchandise_amount merchandise,shipping_amount shipping,status FROM dbo.Refunds WHERE id=@id",{id:refundId})).recordset[0];check(Number(refund.merchandise)===200000&&Number(refund.shipping)===0&&refund.status==="PENDING","refund uses snapshot and excludes shipping");check((await call("POST",`/admin/complaints/${refundComplaint.id}/refund-fallback`,admin.token,{reason:"Duplicate"})).status!==201,"duplicate complaint refund blocked");check((await call("PATCH",`/admin/refunds/${refundId}/status`,admin.token,{status:"COMPLETED",reason:"Manual refund completed"})).status===200,"existing refund workflow completes fallback");check((await call("POST",`/admin/complaints/${refundComplaint.id}/resolve`,admin.token,{resolutionType:"REFUND",reason:"Refund completed"})).status===200,"completed refund resolves complaint");
  const manualFx=await fixture({buyer:buyer.id,shop:shopA,product:catalog[0].productId,variant:catalog[0].variantId,key:"manual",settlement:"HELD"});result=await create(manualFx.itemId,buyer.token);await start(result.data.data.id,admin.token);result=await sellerFault(result.data.data.id,admin.token);state=(await query<any>("SELECT status,hold_source_type sourceType,hold_source_id sourceId FROM dbo.ShopOrderSettlements WHERE id=@id",{id:manualFx.settlementId})).recordset[0];check(state.status==="HELD"&&state.sourceType==="MANUAL"&&state.sourceId==="fixture","existing manual hold preserved");
  const draftFx=await fixture({buyer:buyer.id,shop:shopA,product:catalog[0].productId,variant:catalog[0].variantId,key:"draft",settlement:"ELIGIBLE"});result=await create(draftFx.itemId,buyer.token);const draftComplaint=result.data.data;const batch=await call("POST","/admin/marketplace-finance/settlement-batches",admin.token,{periodStart:"2020-01-01",periodEnd:"2099-01-01",settlementIds:[draftFx.settlementId]});check(batch.status===201,"eligible settlement enters draft before fault decision");await start(draftComplaint.id,admin.token);await sellerFault(draftComplaint.id,admin.token);check((await call("POST",`/admin/marketplace-finance/settlement-batches/${batch.data.data.id}/mark-paid`,admin.token,{reason:"Must fail"})).status===409,"draft batch payment blocked after complaint hold");result=await call("GET",`/admin/marketplace-finance/settlement-batches/${batch.data.data.id}`,admin.token);check(result.data.data.items[0].settlementStatus==="HELD"&&Number(result.data.data.items[0].sellerFaultComplaintCount)===1,"batch detail exposes held complaint blocker");
  const counts=(await query<any>("SELECT (SELECT COUNT(*) FROM dbo.Orders) orders,(SELECT COUNT(*) FROM dbo.ShopOrders) shopOrders,(SELECT COUNT(*) FROM dbo.ShopOrderSettlements) settlements,(SELECT COUNT(*) FROM dbo.SettlementAdjustments) adjustments")).recordset[0];check(Number(counts.adjustments)===0,"replacement/refund creates no automatic adjustment");check(Number((await query<any>("SELECT COUNT(*) count FROM dbo.MarketplaceNotifications WHERE complaint_id IS NOT NULL",{ })).recordset[0].count)>0,"in-app notifications created");check(Number((await query<any>("SELECT COUNT(*) count FROM dbo.ComplaintEventHistory")).recordset[0].count)>0,"complaint history persisted");
  let immutable=false;try{await query("DELETE FROM dbo.ComplaintEventHistory WHERE id=(SELECT MIN(id) FROM dbo.ComplaintEventHistory)");}catch{immutable=true;}check(immutable,"complaint history immutable");
  console.log(`[SELLER-011A ACCEPTANCE PASS] assertions=${assertions} database=${config.db.database} mail=NOT_SENT_NOT_CONFIGURED_BY_RUNNER`);
}
async function dropDatabase(){const pool=await new mssql.ConnectionPool({...config.db,database:"master"}).connect();try{await pool.request().batch(`IF DB_ID(N'${config.db.database}') IS NOT NULL BEGIN ALTER DATABASE [${config.db.database}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;DROP DATABASE [${config.db.database}];END`);}finally{await pool.close();}}
async function run(){try{const{default:app}=await import("../app");server=app.listen(port,"127.0.0.1");await new Promise<void>((resolve,reject)=>{server!.once("listening",resolve);server!.once("error",reject);});await main();return 0;}catch(error){console.error("[SELLER-011A ACCEPTANCE FAIL]",error instanceof Error?error.message:error);return 1;}finally{if(server){server.closeAllConnections();await new Promise<void>(resolve=>server!.close(()=>resolve()));}await closePool();await dropDatabase();}}
void run().then(code=>{process.exitCode=code;});
