import crypto from 'crypto';
import { promises as fs } from 'fs';
import path from 'path';
import bcrypt from 'bcryptjs';
import * as mssql from 'mssql';
import type { Server } from 'http';
import { config } from '../config/config';
import { closePool,query } from '../config/database';

if(process.env.SELLER005_ACCEPTANCE!=='1')throw new Error('SELLER005_ACCEPTANCE=1 is required');
const regression04=process.env.REGRESSION04_ACCEPTANCE==='1',safePrefix=regression04?'GYMFIT_REGRESSION_04_':'GYMFIT_DB_SELLER005_ACCEPTANCE_';
if(config.db.database==='GYMFIT_DB'||!config.db.database.startsWith(safePrefix))throw new Error('Refusing canonical database');
const uploadRoot=path.resolve(config.upload.dir);
if(regression04?!uploadRoot.toUpperCase().includes('GYMFIT_REGRESSION_04_UPLOADS_'):!uploadRoot.toLowerCase().includes('seller005-acceptance'))throw new Error('SELLER-005 requires an isolated acceptance upload directory');

type Role='member'|'coach'|'admin'|'seller';
type Account={id:number;email:string;password:string;token?:string};
const accounts:Record<string,Account>={},stamp=Date.now(),port=Number(process.env.ACCEPTANCE_PORT||5525),base=`http://127.0.0.1:${port}/api`;
let server:Server|undefined,assertions=0,lastStatus=0;const suiteAbort=new AbortController();
const check=(condition:boolean,message:string)=>{assertions++;if(!condition)throw new Error(`${message}; last status=${lastStatus}`);};
async function call(method:string,url:string,key?:string,body?:unknown){
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),regression04?5000:15000),stop=()=>controller.abort();suiteAbort.signal.addEventListener('abort',stop,{once:true});
  try{
    const multipart=body instanceof FormData;
    const response=await fetch(base+url,{method,signal:controller.signal,headers:{...(multipart?{}:{'content-type':'application/json'}),...(key&&accounts[key].token?{authorization:`Bearer ${accounts[key].token}`}:{})},body:body===undefined?undefined:multipart?body:JSON.stringify(body)});
    lastStatus=response.status;let data:any={};try{data=await response.json();}catch{}return{status:response.status,data};
  }finally{clearTimeout(timer);suiteAbort.signal.removeEventListener('abort',stop);}
}
async function expect(method:string,url:string,key:string|undefined,status:number,body?:unknown){const result=await call(method,url,key,body);check(result.status===status,`${method} ${url}: expected ${status}, got ${result.status}`);return result;}
async function seedUser(key:string,role:Role){const email=`seller005-${key}-${stamp}@example.test`,password=`Aa1!${crypto.randomBytes(12).toString('hex')}`,hash=await bcrypt.hash(password,12),r=await query<{id:number}>(`INSERT dbo.Users(email,password,name,role,is_active,email_verified,token_version) OUTPUT INSERTED.id VALUES(@email,@hash,@name,@role,1,1,0)`,{email,hash,name:`SELLER005 ${key}`,role});accounts[key]={id:Number(r.recordset[0].id),email,password};}
async function login(key:string){const r=await call('POST','/auth/login',undefined,{email:accounts[key].email,password:accounts[key].password});check(r.status===200,`${key} login`);accounts[key].token=String(r.data.data.accessToken);}
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');
function imagesForm(count=1,buffer=png,type='image/png'){const form=new FormData();for(let index=0;index<count;index++)form.append('images',new Blob([buffer],{type}),`seller005-${index}.png`);return form;}
const productPayload=(name:string,categoryId:number,brandId:number)=>({name,slug:`seller005-${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${stamp}`,description:'SELLER-005 acceptance',categoryId,brandId,defaultVariant:{name:'Default',sku:`SELLER005-${name}-${stamp}`,price:100000,salePrice:90000,initialOnHand:5,lowStockThreshold:2}});
async function dropDatabase(){if(process.env.SELLER005_KEEP_DB==='1')return;const pool=await new mssql.ConnectionPool({...config.db,database:'master'}).connect();try{await pool.request().batch(`IF DB_ID(N'${config.db.database}') IS NOT NULL BEGIN ALTER DATABASE [${config.db.database}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;DROP DATABASE [${config.db.database}];END`);}finally{await pool.close();}}

async function main(){
  const baseline=(await query<any>(`SELECT (SELECT COUNT(*) FROM dbo.Products) products,(SELECT COUNT(*) FROM dbo.ProductVariants) variants,(SELECT COUNT(*) FROM dbo.Inventory) inventory,(SELECT COUNT(*) FROM dbo.ProductImages) images,(SELECT COUNT(*) FROM dbo.OrderItems) orderItems`)).recordset[0];
  const migration=(await query<any>(`SELECT (SELECT COUNT(*) FROM dbo.SchemaMigrations) migrations,(SELECT COUNT(*) FROM dbo.Products WHERE moderation_status=N'PUBLISHED') published,(SELECT COUNT(*) FROM dbo.Products WHERE id=0 AND moderation_status=N'PUBLISHED') zeroPublished,(SELECT COUNT(*) FROM dbo.Products WHERE shop_id IS NULL) nullOwners,(SELECT COUNT(*) FROM dbo.Products p LEFT JOIN dbo.Shops s ON s.id=p.shop_id WHERE s.id IS NULL) orphanOwners,(SELECT COUNT(*) FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.Products') AND name IN(N'IX_Products_Shop_Moderation',N'IX_Products_Moderation_Submitted')) lifecycleIndexes`)).recordset[0];
  check(Number(migration.migrations)===11,'0103 plus current 0104 applied');check(Number(migration.published)===Number(baseline.products),'legacy Products published');check(Number(migration.zeroPublished)===1,'Product 0 published');check(Number(migration.nullOwners)===0&&Number(migration.orphanOwners)===0,'ownership intact');check(Number(migration.lifecycleIndexes)===2,'moderation indexes');
  for(const [key,role] of [['admin','admin'],['member','member'],['coach','coach'],['sellerA','seller'],['sellerB','seller']] as [string,Role][])await seedUser(key,role);
  for(const key of Object.keys(accounts))await login(key);
  await query(`INSERT dbo.Shops(owner_user_id,name,slug,status,is_verified,is_system) VALUES(@a,N'Seller A',@as,N'ACTIVE',1,0),(@b,N'Seller B',@bs,N'ACTIVE',0,0)`,{a:accounts.sellerA.id,as:`seller005-a-${stamp}`,b:accounts.sellerB.id,bs:`seller005-b-${stamp}`});
  const shops=(await query<any>(`SELECT owner_user_id,id,status FROM dbo.Shops WHERE owner_user_id IN(@a,@b)`,{a:accounts.sellerA.id,b:accounts.sellerB.id})).recordset,shopA=shops.find((x:any)=>x.owner_user_id===accounts.sellerA.id),shopB=shops.find((x:any)=>x.owner_user_id===accounts.sellerB.id);
  let result=await expect('GET','/seller/products/filters','sellerA',200);const category=result.data.data.categories[0],generic=result.data.data.brands.find((x:any)=>x.isGeneric);
  check(Boolean(category),'active Category selector');check(Boolean(generic),'Generic Brand selector');
  const inactiveCategory=(await query<any>(`INSERT dbo.Categories(name,slug,is_active) OUTPUT INSERTED.id VALUES(N'SELLER005 inactive category',@slug,0)`,{slug:`seller005-inactive-category-${stamp}`})).recordset[0];
  const inactiveBrand=(await query<any>(`INSERT dbo.Brands(name,slug,normalized_name,is_generic,is_active) OUTPUT INSERTED.id VALUES(N'SELLER005 inactive brand',@slug,@normalized,0,0)`,{slug:`seller005-inactive-brand-${stamp}`,normalized:`seller005 inactive brand ${stamp}`})).recordset[0];
  const payloadA=productPayload('Product-A',category.id,generic.id);
  result=await expect('POST','/seller/products','sellerA',201,payloadA);const productA=result.data.data,variantA=productA.variants[0];
  check(productA.moderationStatus==='DRAFT'&&!productA.isActive,'Seller creates non-public DRAFT');check(Number(productA.shop.id)===Number(shopA.id),'authenticated Shop ownership');check(productA.variants.length===1&&variantA.isDefault,'default Variant created');check(variantA.onHand===5&&variantA.reserved===0,'initial Inventory created');
  await expect('POST','/seller/products','member',403,productPayload('Member',category.id,generic.id));await expect('POST','/seller/products','coach',403,productPayload('Coach',category.id,generic.id));await expect('POST','/seller/products','admin',403,productPayload('Admin',category.id,generic.id));
  await expect('POST','/seller/products','sellerA',400,{...productPayload('Spoof',category.id,generic.id),shopId:shopB.id});
  await expect('POST','/seller/products','sellerA',409,{...productPayload('Duplicate',category.id,generic.id),slug:payloadA.slug});
  await expect('POST','/seller/products','sellerA',400,productPayload('InvalidCategory',99999999,generic.id));
  await expect('POST','/seller/products','sellerA',400,productPayload('InactiveCategory',inactiveCategory.id,generic.id));
  await expect('POST','/seller/products','sellerA',400,productPayload('InactiveBrand',category.id,inactiveBrand.id));
  await query(`UPDATE dbo.Shops SET status=N'SUSPENDED' WHERE id=@id`,{id:shopA.id});await expect('POST','/seller/products','sellerA',409,productPayload('Suspended',category.id,generic.id));await query(`UPDATE dbo.Shops SET status=N'ACTIVE' WHERE id=@id`,{id:shopA.id});
  const payloadB=productPayload('Product-B',category.id,generic.id);result=await expect('POST','/seller/products','sellerB',201,payloadB);const productB=result.data.data,variantB=productB.variants[0];
  await expect('PATCH',`/seller/products/${productA.id}`,'sellerA',200,{name:'Product A updated'});await expect('PATCH',`/seller/products/${productB.id}`,'sellerA',404,{name:'Cross'});await expect('PATCH',`/seller/products/${productA.id}`,'sellerA',400,{moderationStatus:'PUBLISHED'});await expect('PATCH',`/seller/products/${productA.id}`,'sellerA',400,{isActive:true});await expect('GET',`/products/${productA.id}`,undefined,404);
  result=await expect('POST',`/seller/products/${productA.id}/variants`,'sellerA',201,{name:'Large',sku:`SELLER005-EXTRA-${stamp}`,price:150000,initialOnHand:3,isDefault:false});const extra=result.data.data;
  check(Number(extra.product_id)===Number(productA.id),'Variant attached to own Product');check(extra.on_hand===3&&extra.reserved===0,'Variant Inventory invariant');
  await expect('POST',`/seller/products/${productA.id}/variants`,'sellerA',409,{name:'Duplicate',sku:extra.sku,price:150000});
  await expect('POST',`/seller/products/${productA.id}/variants`,'sellerA',400,{name:'Invalid price',sku:`SELLER005-ZERO-${stamp}`,price:0});
  await expect('POST',`/seller/products/${productB.id}/variants`,'sellerA',404,{name:'Cross',sku:`SELLER005-CROSS-${stamp}`,price:1});
  await expect('PATCH',`/seller/products/${productA.id}/variants/${variantB.id}`,'sellerA',404,{price:200000});
  await expect('PATCH',`/seller/products/${productA.id}/variants/${extra.id}`,'sellerA',200,{price:160000,salePrice:140000});
  check(Number((await query<any>(`SELECT COUNT(*) count FROM dbo.AuditLogs WHERE action=N'seller_variant.updated' AND entity_id=@id`,{id:extra.id})).recordset[0].count)===1,'price update audited');
  await expect('DELETE',`/seller/products/${productA.id}/variants/${extra.id}`,'sellerA',200);await expect('DELETE',`/seller/products/${productA.id}/variants/${variantA.id}`,'sellerA',409);
  result=await expect('POST',`/seller/products/${productA.id}/variants`,'sellerA',201,{name:'Inventory',sku:`SELLER005-INVENTORY-${stamp}`,price:120000,initialOnHand:10});const inventoryVariant=result.data.data;
  await expect('POST',`/seller/products/${productA.id}/variants/${inventoryVariant.id}/inventory/adjustments`,'sellerA',201,{quantityDelta:5,reason:'Restock acceptance'});
  await query(`UPDATE dbo.Shops SET status=N'SUSPENDED' WHERE id=@id`,{id:shopA.id});await expect('PATCH',`/seller/products/${productA.id}`,'sellerA',409,{name:'Blocked while suspended'});await expect('POST',`/seller/products/${productA.id}/variants/${inventoryVariant.id}/inventory/adjustments`,'sellerA',201,{quantityDelta:1,reason:'Inventory remains available while Shop is suspended'});await query(`UPDATE dbo.Shops SET status=N'ACTIVE' WHERE id=@id`,{id:shopA.id});
  await expect('POST',`/seller/products/${productA.id}/variants/${variantB.id}/inventory/adjustments`,'sellerA',404,{quantityDelta:1,reason:'Cross'});
  await expect('POST',`/seller/products/${productA.id}/variants/${inventoryVariant.id}/inventory/adjustments`,'sellerA',400,{quantityDelta:1,reason:'Protected',reserved:99});
  await expect('POST',`/seller/products/${productA.id}/variants/${inventoryVariant.id}/inventory/adjustments`,'sellerA',409,{quantityDelta:-999,reason:'Negative'});
  const concurrent=await Promise.all([call('POST',`/seller/products/${productA.id}/variants/${inventoryVariant.id}/inventory/adjustments`,'sellerA',{quantityDelta:2,reason:'Concurrent A'}),call('POST',`/seller/products/${productA.id}/variants/${inventoryVariant.id}/inventory/adjustments`,'sellerA',{quantityDelta:3,reason:'Concurrent B'})]);
  check(concurrent.every(x=>x.status===201),'concurrent adjustments serialized');
  const inventoryState=(await query<any>('SELECT on_hand,reserved,available FROM dbo.Inventory WHERE variant_id=@id',{id:inventoryVariant.id})).recordset[0];check(inventoryState.on_hand===21&&inventoryState.available===21&&inventoryState.reserved===0,'no lost Inventory update');
  check(Number((await query<any>(`SELECT COUNT(*) count FROM dbo.AuditLogs WHERE action=N'seller_inventory.adjusted' AND entity_id=(SELECT id FROM dbo.Inventory WHERE variant_id=@id)`,{id:inventoryVariant.id})).recordset[0].count)===4,'Inventory adjustments audited');
  result=await expect('POST',`/seller/products/${productA.id}/images`,'sellerA',201,imagesForm());let images=result.data.data.images;check(images.length===1&&images[0].is_primary,'first image auto-primary');
  await expect('POST',`/seller/products/${productB.id}/images`,'sellerA',404,imagesForm());await expect('POST',`/seller/products/${productA.id}/images`,'sellerA',400,imagesForm(1,Buffer.from('not-image'),'image/png'));await expect('POST',`/seller/products/${productA.id}/images`,'sellerA',400,imagesForm(1,png,'image/svg+xml'));await expect('POST',`/seller/products/${productA.id}/images`,'sellerA',400,imagesForm(1,Buffer.alloc(config.upload.maxFileSize+1),'image/png'));
  result=await expect('POST',`/seller/products/${productA.id}/images`,'sellerA',201,imagesForm(7));images=result.data.data.images;check(images.length===8,'maximum eight images accepted');await expect('POST',`/seller/products/${productA.id}/images`,'sellerA',400,imagesForm());
  const nonPrimary=images.find((x:any)=>!x.is_primary);result=await expect('PATCH',`/seller/products/${productA.id}/images/${nonPrimary.id}/primary`,'sellerA',200);check(result.data.data.images.filter((x:any)=>x.is_primary).length===1,'exactly one primary after change');
  await expect('PATCH',`/seller/products/${productA.id}/images/${productB.images?.[0]?.id||999999}`,'sellerA',404);await expect('DELETE',`/seller/products/${productA.id}/images/${nonPrimary.id}`,'sellerA',200);check(Number((await query<any>('SELECT COUNT(*) count FROM dbo.ProductImages WHERE product_id=@id AND is_primary=1',{id:productA.id})).recordset[0].count)===1,'primary fallback deterministic');
  const brandRequest=await expect('POST','/seller/brand-requests','sellerA',201,{requestedName:`Seller005 Brand ${stamp}`,description:'Acceptance'}),requestId=Number(brandRequest.data.data.id);
  const linkedPayload={...productPayload('BrandRequest',category.id,generic.id),brandId:undefined,brandRequestId:requestId};result=await expect('POST','/seller/products','sellerA',201,linkedPayload);const linkedProduct=result.data.data;check(linkedProduct.brandRequestId===requestId&&!linkedProduct.brandId,'pending BrandRequest linked');
  await expect('POST',`/seller/products/${linkedProduct.id}/submit`,'sellerA',409);await expect('POST','/seller/products','sellerB',404,{...productPayload('CrossRequest',category.id,generic.id),brandId:undefined,brandRequestId:requestId});
  await expect('POST',`/admin/brand-requests/${requestId}/approve`,'admin',200);const resolved=(await query<any>('SELECT brand_id,brand_request_id,moderation_status FROM dbo.Products WHERE id=@id',{id:linkedProduct.id})).recordset[0];check(resolved.brand_id&&resolved.brand_request_id===null&&resolved.moderation_status==='DRAFT','Brand approval resolves without submit');
  const noImage=await expect('POST','/seller/products','sellerA',201,productPayload('NoImage',category.id,generic.id));await expect('POST',`/seller/products/${noImage.data.data.id}/submit`,'sellerA',409);
  const noPrimary=await expect('POST','/seller/products','sellerA',201,productPayload('NoPrimary',category.id,generic.id)),noPrimaryId=Number(noPrimary.data.data.id);await expect('POST',`/seller/products/${noPrimaryId}/images`,'sellerA',201,imagesForm());await query('UPDATE dbo.ProductImages SET is_primary=0 WHERE product_id=@id',{id:noPrimaryId});await expect('POST',`/seller/products/${noPrimaryId}/submit`,'sellerA',409);
  const noVariant=await expect('POST','/seller/products','sellerA',201,productPayload('NoVariant',category.id,generic.id)),noVariantId=Number(noVariant.data.data.id);await query('DELETE dbo.Inventory WHERE variant_id IN(SELECT id FROM dbo.ProductVariants WHERE product_id=@id);DELETE dbo.ProductVariants WHERE product_id=@id',{id:noVariantId});await expect('POST',`/seller/products/${noVariantId}/submit`,'sellerA',409);
  await expect('POST',`/seller/products/${productA.id}/submit`,'sellerA',200);let submitted=(await query<any>('SELECT moderation_status,submitted_at,review_reason,is_active FROM dbo.Products WHERE id=@id',{id:productA.id})).recordset[0];check(submitted.moderation_status==='PENDING_REVIEW'&&submitted.submitted_at&&submitted.review_reason===null&&!submitted.is_active,'valid submit transition');
  await expect('PATCH',`/seller/products/${productA.id}`,'sellerA',409,{name:'Blocked'});await expect('POST',`/seller/products/${productA.id}/variants`,'sellerA',409,{name:'Blocked',sku:`BLOCKED-${stamp}`,price:1});await expect('POST',`/seller/products/${productA.id}/images`,'sellerA',409,imagesForm());await expect('POST',`/seller/products/${productA.id}/submit`,'sellerA',409);await expect('GET',`/products/${productA.id}`,undefined,404);
  await query(`UPDATE dbo.Products SET moderation_status=N'REJECTED',review_reason=N'Improve content',is_active=0 WHERE id=@id`,{id:productA.id});result=await expect('GET',`/seller/products/${productA.id}`,'sellerA',200);check(result.data.data.reviewReason==='Improve content','owner sees reject reason');await expect('GET',`/seller/products/${productA.id}`,'sellerB',404);await expect('POST',`/seller/products/${productA.id}/submit`,'sellerA',200);submitted=(await query<any>('SELECT moderation_status,review_reason FROM dbo.Products WHERE id=@id',{id:productA.id})).recordset[0];check(submitted.moderation_status==='PENDING_REVIEW'&&submitted.review_reason===null,'resubmit clears reason');
  const deletable=await expect('POST','/seller/products','sellerA',201,productPayload('DeleteMe',category.id,generic.id)),deleteId=deletable.data.data.id,deleteVariantId=deletable.data.data.variants[0].id;const deleteImage=await expect('POST',`/seller/products/${deleteId}/images`,'sellerA',201,imagesForm()),deleteImageUrl=String(deleteImage.data.data.images[0].imageUrl),deleteImagePath=path.resolve(uploadRoot,deleteImageUrl.replace(/^\/uploads\//,''));await query('UPDATE dbo.Inventory SET reserved=1 WHERE variant_id=@id',{id:deleteVariantId});await expect('DELETE',`/seller/products/${deleteId}`,'sellerA',409);await query('UPDATE dbo.Inventory SET reserved=0 WHERE variant_id=@id',{id:deleteVariantId});await expect('DELETE',`/seller/products/${deleteId}`,'sellerB',404);await expect('DELETE',`/seller/products/${deleteId}`,'sellerA',200);check(Number((await query<any>('SELECT COUNT(*) count FROM dbo.Products WHERE id=@id',{id:deleteId})).recordset[0].count)===0,'draft Product deleted');check(Number((await query<any>('SELECT COUNT(*) count FROM dbo.ProductVariants WHERE product_id=@id',{id:deleteId})).recordset[0].count)===0,'delete cleans child rows');check(await fs.access(deleteImagePath).then(()=>false).catch(()=>true),'delete cleans verified image file');await expect('DELETE',`/seller/products/${productA.id}`,'sellerA',409);
  const suspendedDelete=await expect('POST','/seller/products','sellerA',201,productPayload('SuspendedDelete',category.id,generic.id)),suspendedDeleteId=Number(suspendedDelete.data.data.id);await query(`UPDATE dbo.Products SET moderation_status=N'SUSPENDED',is_active=0 WHERE id=@id`,{id:suspendedDeleteId});await expect('DELETE',`/seller/products/${suspendedDeleteId}`,'sellerA',409);
  result=await expect('GET','/products?page=1&limit=100',undefined,200);check(!result.data.data.some((x:any)=>x.id===productA.id||x.id===productB.id),'non-published Seller Products hidden');result=await expect('GET','/products/0',undefined,200);check(Number(result.data.data.id)===0,'existing Product ID 0 public');
  result=await expect('GET','/admin/products?page=1&limit=100','admin',200);check(Number(result.data.pagination.total)>=Number(baseline.products),'Admin list remains global');check((await query<any>('SELECT moderation_status FROM dbo.Products WHERE id=@id',{id:productA.id})).recordset[0].moderation_status==='PENDING_REVIEW','Admin lifecycle metadata persisted');
  await expect('GET',`/admin/products/${productA.id}`,'admin',200);
  await expect('POST','/admin/products','admin',400,{product_name:'SELLER005 protected',sku:`SELLER005-PROTECTED-${stamp}`,price:100000,stock:2,category_id:category.id,shop_id:shopB.id,moderation_status:'DRAFT'});
  const adminCreate=await expect('POST','/admin/products','admin',201,{product_name:'SELLER005 admin',sku:`SELLER005-ADMIN-${stamp}`,price:100000,stock:2,category_id:category.id}),adminId=Number(adminCreate.data.data.id);
  const adminOwner=(await query<any>('SELECT shop_id,moderation_status FROM dbo.Products WHERE id=@id',{id:adminId})).recordset[0],official=(await query<any>(`SELECT id FROM dbo.Shops WHERE system_key=N'GYMFIT_OFFICIAL'`)).recordset[0];check(Number(adminOwner.shop_id)===Number(official.id)&&adminOwner.moderation_status==='PUBLISHED','Admin create remains Official/PUBLISHED');await expect('PATCH',`/admin/products/${adminId}`,'admin',400,{description:'Admin regression',shop_id:shopB.id,moderation_status:'SUSPENDED'});await expect('PATCH',`/admin/products/${adminId}`,'admin',200,{description:'Admin regression'});check(Number((await query<any>('SELECT shop_id FROM dbo.Products WHERE id=@id',{id:adminId})).recordset[0].shop_id)===Number(official.id),'Admin update cannot transfer ownership');const adminVariant=await expect('POST',`/admin/products/${adminId}/variants`,'admin',201,{variant_name:'Admin extra',sku:`SELLER005-ADMIN-EXTRA-${stamp}`,price:110000,initial_on_hand:1});await expect('PATCH',`/admin/variants/${adminVariant.data.data.id}`,'admin',200,{price:115000});await expect('DELETE',`/admin/variants/${adminVariant.data.data.id}`,'admin',200);const adminImage=await expect('POST',`/admin/products/${adminId}/images`,'admin',201,imagesForm()),adminImageId=adminImage.data.data.images[0].id;await expect('PATCH',`/admin/products/${adminId}/images/${adminImageId}/primary`,'admin',200);await expect('DELETE',`/admin/products/${adminId}/images/${adminImageId}`,'admin',200);await expect('DELETE',`/admin/products/${adminId}`,'admin',200);const legacyVariant=(await query<any>('SELECT TOP 1 id FROM dbo.ProductVariants WHERE product_id=0')).recordset[0];await expect('POST',`/admin/variants/${legacyVariant.id}/inventory/adjustments`,'admin',201,{type:'MANUAL_CORRECTION',quantityDelta:1,reason:'Admin inventory regression'});await expect('POST',`/admin/variants/${legacyVariant.id}/inventory/adjustments`,'admin',201,{type:'MANUAL_CORRECTION',quantityDelta:-1,reason:'Admin inventory regression restore'});
  const final=(await query<any>(`SELECT (SELECT COUNT(*) FROM dbo.Products WHERE shop_id IS NULL) nullOwners,(SELECT COUNT(*) FROM dbo.Products p LEFT JOIN dbo.Shops s ON s.id=p.shop_id WHERE s.id IS NULL) orphanOwners,(SELECT COUNT(*) FROM dbo.OrderItems) orderItems,(SELECT COUNT(*) FROM dbo.AuditLogs WHERE action LIKE N'seller_%') sellerAudits,(SELECT COUNT(*) FROM dbo.Products WHERE (brand_id IS NULL AND brand_request_id IS NULL) OR (brand_id IS NOT NULL AND brand_request_id IS NOT NULL)) invalidBrandSource`)).recordset[0];
  check(Number(final.nullOwners)===0&&Number(final.orphanOwners)===0,'no Product orphan');check(Number(final.orderItems)===Number(baseline.orderItems),'OrderItem references unchanged');check(Number(final.sellerAudits)>=15,'Seller mutations audited');check(Number(final.invalidBrandSource)===0,'Brand source XOR invariant');check(Number((await query<any>(`SELECT COUNT(*) count FROM dbo.Products WHERE id<167 AND moderation_status<>N'PUBLISHED'`)).recordset[0].count)===0,'legacy lifecycle unchanged');
  console.log(`[SELLER-005 ACCEPTANCE PASS] assertions=${assertions} database=${config.db.database}`);
}

async function run(){let timer:NodeJS.Timeout|undefined;const deadline=regression04?60000:300000;try{const{default:app}=await import('../app');server=app.listen(port,'127.0.0.1');await new Promise<void>((resolve,reject)=>{server!.once('listening',resolve);server!.once('error',reject);});await Promise.race([main(),new Promise<never>((_,reject)=>{timer=setTimeout(()=>{suiteAbort.abort();reject(new Error(`Suite timed out after ${deadline}ms`));},deadline);})]);return 0;}catch(error){console.error('[SELLER-005 ACCEPTANCE FAIL]',error instanceof Error?error.message:error);return 1;}finally{if(timer)clearTimeout(timer);if(server){server.closeAllConnections();await new Promise<void>(resolve=>server!.close(()=>resolve()));}await closePool();await fs.rm(uploadRoot,{recursive:true,force:true,maxRetries:5,retryDelay:100});await dropDatabase();}}
run().then(code=>{process.exitCode=code;});
