import crypto from 'crypto';import bcrypt from 'bcryptjs';import type{Server}from'http';import{config}from'../config/config';import{closePool,query}from'../config/database';
if(process.env.SELLER003_ACCEPTANCE!=='1')throw new Error('SELLER003_ACCEPTANCE=1 is required');const regression01=process.env.REGRESSION01==='1';const safePrefix=regression01?'GYMFIT_REGRESSION_':'GYMFIT_DB_SELLER003_ACCEPTANCE_';if(config.db.database==='GYMFIT_DB'||!config.db.database.startsWith(safePrefix))throw new Error('Refusing canonical database');
type Role='member'|'coach'|'admin'|'seller';type Account={id:number;email:string;password:string;token?:string};const a:Record<string,Account>={},stamp=Date.now(),port=Number(process.env.ACCEPTANCE_PORT||5533),base=`http://127.0.0.1:${port}/api`,requestTimeout=regression01?5000:15000;let server:Server|undefined,assertions=0,last=0;const check=(v:boolean,m:string)=>{assertions++;if(!v)throw new Error(`${m}; status=${last}`);};
async function call(method:string,path:string,key?:string,body?:unknown){const c=new AbortController(),t=setTimeout(()=>c.abort(),requestTimeout);try{const r=await fetch(base+path,{method,signal:c.signal,headers:{'content-type':'application/json',...(key&&a[key].token?{authorization:`Bearer ${a[key].token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});last=r.status;let data:any={};try{data=await r.json();}catch{}return{status:r.status,data};}finally{clearTimeout(t);}}
async function callWithToken(method:string,path:string,token:string){const c=new AbortController(),t=setTimeout(()=>c.abort(),requestTimeout);try{const r=await fetch(base+path,{method,signal:c.signal,headers:{authorization:`Bearer ${token}`}});last=r.status;let data:any={};try{data=await r.json();}catch{}return{status:r.status,data};}finally{clearTimeout(t);}}
async function expect(method:string,path:string,key:string|undefined,status:number,body?:unknown){const r=await call(method,path,key,body);check(r.status===status,`${method} ${path} expected ${status}, got ${r.status}`);return r;}
async function seed(key:string,role:Role){const email=`seller003-${key}-${stamp}@example.test`,password=`Aa1!${crypto.randomBytes(12).toString('hex')}`,hash=await bcrypt.hash(password,12);const r=await query<{id:number}>(`INSERT dbo.Users(email,password,name,role,is_active,email_verified,token_version) OUTPUT INSERTED.id VALUES(@email,@hash,@name,@role,1,1,0)`,{email,hash,name:`SELLER003 ${key}`,role});a[key]={id:Number(r.recordset[0].id),email,password};}
async function login(key:string){const r=await call('POST','/auth/login',undefined,{email:a[key].email,password:a[key].password});check(r.status===200,`${key} login`);a[key].token=r.data.data.accessToken;}
async function shop(key:string,status='ACTIVE'){await query(`INSERT dbo.Shops(owner_user_id,name,slug,status,is_verified,is_system) VALUES(@id,@name,@slug,@status,0,0)`,{id:a[key].id,name:`Shop ${key}`,slug:`shop-${key}-${stamp}`,status});}
const payload=(name:string)=>({requestedName:name,websiteUrl:'https://example.test',description:'Disposable acceptance request'});
async function main(){const connectedDatabase=String((await query<{databaseName:string}>('SELECT DB_NAME() databaseName')).recordset[0]?.databaseName||'');check(connectedDatabase.startsWith(safePrefix),`unsafe connected database ${connectedDatabase}`);const baseCounts=(await query<any>(`SELECT (SELECT COUNT(*) FROM dbo.Brands) brands,(SELECT COUNT(*) FROM dbo.Products WHERE brand_id IS NOT NULL) refs,(SELECT COUNT(*) FROM dbo.Products) products,(SELECT COUNT(*) FROM dbo.ProductVariants) variants,(SELECT COUNT(*) FROM dbo.Inventory) inventory,(SELECT COUNT(*) FROM dbo.ProductImages) images`)).recordset[0];
check(Number((await query<any>('SELECT COUNT(*) count FROM dbo.Brands WHERE normalized_name IS NULL')).recordset[0].count)===0,'normalized backfill');check(Number((await query<any>('SELECT COUNT(*) count FROM(SELECT normalized_name FROM dbo.Brands GROUP BY normalized_name HAVING COUNT(*)>1)x')).recordset[0].count)===0,'no normalized duplicates');const generic=(await query<any>('SELECT * FROM dbo.Brands WHERE is_generic=1')).recordset;check(generic.length===1&&generic[0].is_active,'one active generic');
for(const [k,r]of[['admin','admin'],['member','member'],['coach','coach'],['sellerA','seller'],['sellerB','seller'],['validation','seller'],['noShop','seller'],['suspended','seller'],['rate','seller']]as[string,Role][])await seed(k,r);for(const k of Object.keys(a))await login(k);for(const k of['sellerA','sellerB','validation','rate'])await shop(k);await shop('suspended','SUSPENDED');
await expect('GET','/seller/brand-requests',undefined,401);check((await callWithToken('GET','/seller/brand-requests','invalid-token')).status===401,'invalid token seller endpoint');await expect('POST','/seller/brand-requests',undefined,401,payload('No token'));check((await callWithToken('POST','/seller/brand-requests','invalid-token')).status===401,'invalid token seller create');for(const k of['member','coach','admin'])await expect('GET','/seller/brand-requests',k,403);await expect('GET','/seller/brand-requests?page=0','sellerA',400);await expect('GET','/seller/brand-requests?limit=101','sellerA',400);await expect('GET','/seller/brand-requests?status=UNKNOWN','sellerA',400);
let r=await expect('POST','/seller/brand-requests','sellerA',201,payload('  New   Việt Brand  '));const requestId=Number(r.data.data.id);check(r.data.data.status==='PENDING'&&r.data.data.history[0].toStatus==='PENDING','create PENDING with history');
await expect('GET','/seller/brand-requests','sellerA',200);await expect('GET',`/seller/brand-requests/${requestId}`,'sellerA',200);await expect('GET',`/seller/brand-requests/${requestId}`,'sellerB',404);
for(const k of['member','coach','admin'])await expect('POST','/seller/brand-requests',k,403,payload(`No ${k}`));await expect('POST','/seller/brand-requests','validation',400,{});await expect('POST','/seller/brand-requests','validation',400,{...payload('Protected'),status:'APPROVED'});await expect('POST','/seller/brand-requests','validation',400,{...payload('Spoofed seller'),sellerId:a.sellerB.id});await expect('POST','/seller/brand-requests','validation',400,payload(' '));await expect('POST','/seller/brand-requests','validation',400,payload('X'.repeat(201)));await expect('POST','/seller/brand-requests','validation',400,{...payload('Long description'),description:'X'.repeat(2001)});await expect('POST','/seller/brand-requests','validation',400,{...payload('Bad URL'),websiteUrl:'bad'});await expect('POST','/seller/brand-requests','noShop',409,payload('No Shop Brand'));
await expect('POST','/seller/brand-requests','sellerB',409,payload('new việt   brand'));const conflict=await expect('POST','/seller/brand-requests','sellerA',409,payload(String(generic[0].name).toUpperCase()));check(!JSON.stringify(conflict.data).includes(a.sellerA.email),'dedupe response private');
const existing=(await query<any>('SELECT TOP 1 name FROM dbo.Brands WHERE is_generic=0 AND is_active=1 ORDER BY id')).recordset[0];await expect('POST','/seller/brand-requests','sellerA',409,payload(existing.name.toUpperCase()));
await expect('POST','/seller/brand-requests','suspended',409,payload('Suspended create'));await expect('GET','/seller/brand-requests','suspended',200);
await expect('GET','/admin/brand-requests',undefined,401);check((await callWithToken('GET','/admin/brand-requests','invalid-token')).status===401,'invalid token admin endpoint');for(const k of['sellerA','member','coach'])await expect('GET','/admin/brand-requests',k,403);await expect('GET','/admin/brand-requests?page=-1','admin',400);await expect('GET','/admin/brand-requests?status=UNKNOWN','admin',400);r=await expect('GET','/admin/brand-requests','admin',200);check(r.data.data.every((x:any)=>x.status==='PENDING'),'default inbox PENDING');await expect('GET','/admin/brand-requests/2147483000','admin',404);await expect('POST','/admin/brand-requests/2147483000/approve','admin',404);await expect('POST','/admin/brand-requests/2147483000/reject','admin',404,{reason:'Missing'});await expect('GET',`/admin/brand-requests/${requestId}`,'admin',200);await expect('POST',`/admin/brand-requests/${requestId}/reject`,'sellerA',403,{reason:'Forbidden'});await expect('POST',`/admin/brand-requests/${requestId}/reject`,'member',403,{reason:'Forbidden'});await expect('POST',`/admin/brand-requests/${requestId}/reject`,'admin',400,{});await expect('POST',`/admin/brand-requests/${requestId}/reject`,'admin',400,{reason:'   '});await expect('POST',`/admin/brand-requests/${requestId}/reject`,'admin',200,{reason:'Needs evidence'});await expect('POST',`/admin/brand-requests/${requestId}/reject`,'admin',409,{reason:'Again'});await expect('POST',`/admin/brand-requests/${requestId}/approve`,'admin',409);r=await expect('GET','/admin/brand-requests?status=REJECTED','admin',200);check(r.data.data.some((x:any)=>Number(x.id)===requestId),'rejected filter');r=await expect('GET',`/seller/brand-requests/${requestId}`,'sellerA',200);check(r.data.data.reviewReason==='Needs evidence','seller sees reason');
r=await expect('POST','/seller/brand-requests','sellerA',201,payload('New Việt Brand'));const approveId=Number(r.data.data.id);await expect('POST',`/admin/brand-requests/${approveId}/approve`,'sellerA',403);await expect('POST',`/admin/brand-requests/${approveId}/approve`,'member',403);await expect('POST',`/admin/brand-requests/${approveId}/approve`,'admin',200);await expect('POST',`/admin/brand-requests/${approveId}/approve`,'admin',409);await expect('POST',`/admin/brand-requests/${approveId}/reject`,'admin',409,{reason:'Cannot reverse'});await expect('POST','/seller/brand-requests','sellerA',409,payload('New Việt Brand'));const approved=(await query<any>('SELECT resolved_brand_id,reviewed_by_user_id,reviewed_at FROM dbo.BrandRequests WHERE id=@id',{id:approveId})).recordset[0];check(Boolean(approved.resolved_brand_id)&&Number(approved.reviewed_by_user_id)===a.admin.id&&Boolean(approved.reviewed_at),'approved resolves Brand with reviewer/time');r=await expect('GET','/admin/brand-requests?status=APPROVED','admin',200);check(r.data.data.some((x:any)=>Number(x.id)===approveId&&x.reviewerName),'approved filter and reviewer name');r=await expect('GET','/admin/products/filters','admin',200);check(r.data.data.brands.some((b:any)=>b.id===approved.resolved_brand_id),'approved Brand in selector');
r=await expect('POST','/seller/brand-requests','sellerB',201,payload('Resolve Existing Later'));const resolveId=Number(r.data.data.id);await query(`INSERT dbo.Brands(name,slug,normalized_name,is_generic,is_active) VALUES(N'Resolve Existing Later',@slug,N'resolve existing later',0,1)`,{slug:`resolve-existing-${stamp}`});const existingId=(await query<any>(`SELECT id FROM dbo.Brands WHERE normalized_name=N'resolve existing later'`)).recordset[0].id;await expect('POST',`/admin/brand-requests/${resolveId}/approve`,'admin',200);check(Number((await query<any>('SELECT resolved_brand_id FROM dbo.BrandRequests WHERE id=@id',{id:resolveId})).recordset[0].resolved_brand_id)===Number(existingId),'approve resolves existing');
r=await expect('POST','/seller/brand-requests','sellerB',201,payload('Concurrent Approval'));const concurrentId=Number(r.data.data.id);const concurrent=await Promise.all([call('POST',`/admin/brand-requests/${concurrentId}/approve`,'admin'),call('POST',`/admin/brand-requests/${concurrentId}/approve`,'admin')]);check(concurrent.map(x=>x.status).sort().join(',')==='200,409','concurrent review safe');
r=await expect('POST','/seller/brand-requests','sellerB',201,payload('Rollback Brand'));const rollbackId=Number(r.data.data.id);await query(`CREATE TRIGGER dbo.TR_SELLER003_AuditFail ON dbo.AuditLogs AFTER INSERT AS IF EXISTS(SELECT 1 FROM inserted WHERE action LIKE N'brand_request.approved%') THROW 51999,'forced',1;`);await expect('POST',`/admin/brand-requests/${rollbackId}/approve`,'admin',500);await query('DROP TRIGGER dbo.TR_SELLER003_AuditFail');const rollback=(await query<any>('SELECT status FROM dbo.BrandRequests WHERE id=@id',{id:rollbackId})).recordset[0];check(rollback.status==='PENDING'&&Number((await query<any>(`SELECT COUNT(*) count FROM dbo.Brands WHERE normalized_name=N'rollback brand'`)).recordset[0].count)===0,'approval rollback');
r=await expect('POST','/admin/brands','admin',201,{name:`Admin Brand ${stamp}`});const adminBrand=Number(r.data.data.id);await expect('POST','/admin/brands','admin',409,{name:`  ADMIN   BRAND ${stamp} `});await expect('PATCH',`/admin/brands/${adminBrand}`,'admin',200,{name:`Renamed Brand ${stamp}`});check((await query<any>('SELECT normalized_name FROM dbo.Brands WHERE id=@id',{id:adminBrand})).recordset[0].normalized_name===`renamed brand ${stamp}`,'admin update normalized');await expect('PATCH',`/admin/brands/${generic[0].id}`,'admin',409,{is_active:false});await expect('DELETE',`/admin/brands/${generic[0].id}`,'admin',409);
for(let i=0;i<10;i++)await expect('POST','/seller/brand-requests','rate',201,payload(`Rate Brand ${i} ${stamp}`));await expect('POST','/seller/brand-requests','rate',429,payload(`Rate Brand 11 ${stamp}`));
check(Number((await query<any>(`SELECT COUNT(*) count FROM dbo.AuditLogs WHERE action=N'brand_request.created'`)).recordset[0].count)>0,'create audit');check(Number((await query<any>(`SELECT COUNT(*) count FROM dbo.AuditLogs WHERE action LIKE N'brand_request.approved%'`)).recordset[0].count)>0,'approve audit');check(Number((await query<any>(`SELECT COUNT(*) count FROM dbo.AuditLogs WHERE action=N'brand_request.rejected' AND new_value LIKE N'%Needs evidence%'`)).recordset[0].count)===1,'reject audit reason');
await expect('GET','/products',undefined,200);await expect('GET','/products/0',undefined,200);const end=await query<any>(`SELECT (SELECT COUNT(*) FROM dbo.Products WHERE brand_id IS NOT NULL) refs,(SELECT COUNT(*) FROM dbo.Products) products,(SELECT COUNT(*) FROM dbo.ProductVariants) variants,(SELECT COUNT(*) FROM dbo.Inventory) inventory,(SELECT COUNT(*) FROM dbo.ProductImages) images,(SELECT COUNT(*) FROM dbo.Shops WHERE system_key=N'GYMFIT_OFFICIAL' AND is_system=1 AND status=N'ACTIVE') official`);check(end.recordset[0].refs===baseCounts.refs&&end.recordset[0].products===baseCounts.products&&end.recordset[0].variants===baseCounts.variants&&end.recordset[0].inventory===baseCounts.inventory&&end.recordset[0].images===baseCounts.images,'commerce counts unchanged');check(Number(end.recordset[0].official)===1,'Shop invariant');console.log(`[ACCEPTANCE PASS] assertions=${assertions} database=${config.db.database}`);
}
async function run(){let timer:NodeJS.Timeout|undefined;try{const{default:app}=await import('../app');server=app.listen(port,'127.0.0.1');await new Promise<void>((ok,bad)=>{server!.once('listening',ok);server!.once('error',bad);});await Promise.race([main(),new Promise((_,bad)=>{timer=setTimeout(()=>bad(new Error('Suite timed out')),regression01?60000:300000);})]);return 0;}catch(e){console.error('[ACCEPTANCE FAIL]',e instanceof Error?e.message:e);return 1;}finally{if(timer)clearTimeout(timer);if(server){server.closeAllConnections();await new Promise<void>(ok=>server!.close(()=>ok()));}await closePool();}}run().then(c=>process.exitCode=c);
