import crypto from'crypto';import bcrypt from'bcryptjs';import type{Server}from'http';
import{config}from'../config/config';import{closePool,query}from'../config/database';import{productOwnershipService}from'../modules/products/product-ownership.service';
import{adminVariantsService}from'../modules/admin-variants/admin-variants.service';import{adminInventoryService}from'../modules/admin-inventory/admin-inventory.service';import{adminProductsService}from'../modules/admin-products/admin-products.service';
if(process.env.SELLER004_ACCEPTANCE!=='1')throw new Error('SELLER004_ACCEPTANCE=1 is required');
if(config.db.database==='GYMFIT_DB'||!config.db.database.startsWith('GYMFIT_DB_SELLER004_ACCEPTANCE_'))throw new Error('Refusing canonical database');
type Role='member'|'coach'|'admin'|'seller';type Account={id:number;email:string;password:string;token?:string};const a:Record<string,Account>={},stamp=Date.now(),port=Number(process.env.ACCEPTANCE_PORT||5524),base=`http://127.0.0.1:${port}/api`;let server:Server|undefined,assertions=0,lastStatus=0;const suiteAbort=new AbortController();
const check=(v:boolean,m:string)=>{assertions++;if(!v)throw new Error(`${m}; status=${lastStatus}`);};
async function call(method:string,path:string,key?:string,body?:unknown){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000),stop=()=>c.abort();suiteAbort.signal.addEventListener('abort',stop,{once:true});try{const r=await fetch(base+path,{method,signal:c.signal,headers:{'content-type':'application/json',...(key&&a[key].token?{authorization:`Bearer ${a[key].token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});lastStatus=r.status;let data:any={};try{data=await r.json();}catch{}return{status:r.status,data};}finally{clearTimeout(timer);suiteAbort.signal.removeEventListener('abort',stop);}}
async function expect(method:string,path:string,key:string|undefined,status:number,body?:unknown){const r=await call(method,path,key,body);check(r.status===status,`${method} ${path} expected ${status}`);return r;}
async function seedUser(key:string,role:Role){const email=`seller004-${key}-${stamp}@example.test`,password=`Aa1!${crypto.randomBytes(12).toString('hex')}`,hash=await bcrypt.hash(password,12),r=await query<{id:number}>(`INSERT dbo.Users(email,password,name,role,is_active,email_verified,token_version) OUTPUT INSERTED.id VALUES(@email,@hash,@name,@role,1,1,0)`,{email,hash,name:`SELLER004 ${key}`,role});a[key]={id:Number(r.recordset[0].id),email,password};}
async function login(key:string){const r=await call('POST','/auth/login',undefined,{email:a[key].email,password:a[key].password});check(r.status===200,`${key} login`);a[key].token=r.data.data.accessToken;}
async function seedProduct(shopId:number,key:string,active=1){const category=(await query<any>('SELECT TOP 1 id FROM dbo.Categories WHERE is_active=1 ORDER BY id')).recordset[0];const sku=`SELLER004-${key}-${stamp}`,p=(await query<any>(`INSERT dbo.Products(product_name,slug,description,sku,price,stock,category_id,is_active,shop_id) OUTPUT INSERTED.id VALUES(@name,@slug,N'Acceptance product',@sku,100000,8,@category,@active,@shop)`,{name:`SELLER004 ${key}`,slug:`seller004-${key}-${stamp}`,sku,category:category.id,active,shop:shopId})).recordset[0];const v=(await query<any>(`INSERT dbo.ProductVariants(product_id,variant_name,sku,price,is_active,is_default,created_at,updated_at) OUTPUT INSERTED.id VALUES(@p,N'Default',@sku,100000,1,1,SYSUTCDATETIME(),SYSUTCDATETIME())`,{p:p.id,sku})).recordset[0];const i=(await query<any>(`INSERT dbo.Inventory(variant_id,on_hand,reserved,low_stock_threshold) OUTPUT INSERTED.id VALUES(@v,8,0,2)`,{v:v.id})).recordset[0];const im=(await query<any>(`INSERT dbo.ProductImages(product_id,image_url,alt_text,sort_order,is_primary) OUTPUT INSERTED.id VALUES(@p,@url,N'fixture',0,1)`,{p:p.id,url:`/uploads/products/seller004-${key}.webp`})).recordset[0];return{id:Number(p.id),variant:Number(v.id),inventory:Number(i.id),image:Number(im.id)};}
async function blocked(fn:()=>Promise<unknown>,label:string){let yes=false;try{await fn();}catch(e:any){yes=e?.statusCode===404;}check(yes,label);}
async function adminChildRegression(productId:number){
  const variant=await adminVariantsService.create(productId,{variant_name:'Acceptance child',sku:`SELLER004-CHILD-${stamp}`,price:120000,initial_on_hand:4,low_stock_threshold:1});
  check(Boolean(variant.id),'admin variant create');
  const updated=await adminVariantsService.update(Number(variant.id),{variant_name:'Acceptance child updated'});
  check(updated.variant_name==='Acceptance child updated','admin variant update');
  const inventory=await adminInventoryService.threshold(Number(variant.id),3);
  check(Number(inventory.low_stock_threshold)===3,'admin inventory threshold');
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');
  const imageProduct=await adminProductsService.addImages(productId,[{buffer:png,originalname:'seller004.png',mimetype:'image/png'} as Express.Multer.File]);
  const image=imageProduct.images.find((x:{image_url:string})=>x.image_url.includes(`/products/${productId}/`));
  check(Boolean(image),'admin image create');
  await adminProductsService.setPrimary(productId,Number(image.id));check(true,'admin image primary');
  await adminProductsService.removeImage(productId,Number(image.id));check(true,'admin image delete');
  const removed=await adminVariantsService.remove(Number(variant.id));check(removed.action==='DELETED','admin variant delete');
}
async function main(){const baseline=(await query<any>(`SELECT (SELECT COUNT(*) FROM dbo.Products) p,(SELECT COUNT(*) FROM dbo.ProductVariants)v,(SELECT COUNT(*)FROM dbo.Inventory)i,(SELECT COUNT(*)FROM dbo.ProductImages)im,(SELECT COUNT(*)FROM dbo.OrderItems)o`)).recordset[0];const meta=(await query<any>(`SELECT (SELECT is_nullable FROM sys.columns WHERE object_id=OBJECT_ID(N'dbo.Products')AND name=N'shop_id')nullable,(SELECT COUNT(*)FROM dbo.Products WHERE shop_id IS NULL)nulls,(SELECT COUNT(*)FROM dbo.Products p LEFT JOIN dbo.Shops s ON s.id=p.shop_id WHERE s.id IS NULL)orphans,(SELECT COUNT(*)FROM dbo.Products WHERE id=0)zero,COL_LENGTH(N'dbo.ProductVariants',N'shop_id')vs,COL_LENGTH(N'dbo.ProductImages',N'shop_id')ims,COL_LENGTH(N'dbo.Inventory',N'shop_id')ins`)).recordset[0];check(meta.nullable===false,'shop not null');check(Number(meta.nulls)===0,'no null owner');check(Number(meta.orphans)===0,'no orphan');check(Number(meta.zero)===1,'Product 0');check(meta.vs===null&&meta.ims===null&&meta.ins===null,'no duplicate child ownership');
const official=await productOwnershipService.resolveGymFitOfficialShop();check(official.status==='ACTIVE','official active');check(Boolean(official.isVerified),'official verified');
for(const[x,r]of[['admin','admin'],['member','member'],['coach','coach'],['sellerA','seller'],['sellerB','seller']]as[string,Role][])await seedUser(x,r);for(const x of Object.keys(a))await login(x);
await query(`INSERT dbo.Shops(owner_user_id,name,slug,status,is_verified,is_system)VALUES(@a,N'Seller A',@as,N'ACTIVE',1,0),(@b,N'Seller B',@bs,N'ACTIVE',0,0)`,{a:a.sellerA.id,as:`seller004-a-${stamp}`,b:a.sellerB.id,bs:`seller004-b-${stamp}`});const shopA=await productOwnershipService.resolveSellerShop(a.sellerA.id),shopB=await productOwnershipService.resolveSellerShop(a.sellerB.id),pa=await seedProduct(shopA.id,'A'),pb=await seedProduct(shopB.id,'B'),pi=await seedProduct(shopA.id,'INACTIVE',0);
let r=await expect('GET','/seller/products?page=1&limit=100&sort=created_desc','sellerA',200);check(r.data.data.some((x:any)=>x.id===pa.id),'A sees A');check(r.data.data.some((x:any)=>x.id===pi.id),'A sees inactive');check(!r.data.data.some((x:any)=>x.id===pb.id),'A not B');check(!r.data.data.some((x:any)=>x.id===0),'A not official');r=await expect('GET','/seller/products','sellerB',200);check(r.data.data.length===1&&r.data.data[0].id===pb.id,'B only B');
await expect('GET',`/seller/products/${pa.id}`,'sellerA',200);await expect('GET',`/seller/products/${pb.id}`,'sellerA',404);await expect('GET','/seller/products/99999999','sellerA',404);await expect('GET','/seller/products/0','sellerA',404);await expect('GET','/seller/products','member',403);await expect('GET','/seller/products','coach',403);await expect('GET','/seller/products','admin',403);await expect('GET',`/seller/products?shop_id=${shopB.id}`,'sellerA',400);await expect('GET','/seller/products?sort=id%3BDROP%20TABLE%20Products','sellerA',400);await expect('POST','/seller/products','sellerA',404,{});await expect('PATCH',`/seller/products/${pa.id}`,'sellerA',404,{});await expect('DELETE',`/seller/products/${pa.id}`,'sellerA',404);
await productOwnershipService.assertSellerOwnsProduct(pa.id,a.sellerA.id);check(true,'own product helper');await blocked(()=>productOwnershipService.assertSellerOwnsProduct(pb.id,a.sellerA.id),'cross product');await productOwnershipService.assertSellerOwnsVariant(pa.variant,a.sellerA.id);check(true,'own variant');await blocked(()=>productOwnershipService.assertSellerOwnsVariant(pb.variant,a.sellerA.id),'cross variant');await productOwnershipService.assertSellerOwnsImage(pa.image,a.sellerA.id);check(true,'own image');await blocked(()=>productOwnershipService.assertSellerOwnsImage(pb.image,a.sellerA.id),'cross image');await productOwnershipService.assertSellerOwnsInventoryRecord(pa.inventory,a.sellerA.id);check(true,'own inventory');await blocked(()=>productOwnershipService.assertSellerOwnsInventoryRecord(pb.inventory,a.sellerA.id),'cross inventory');
r=await expect('GET','/products?search=SELLER004&page=1&limit=100',undefined,200);check(r.data.data.some((x:any)=>x.id===pa.id)&&r.data.data.some((x:any)=>x.id===pb.id),'active seller public');check(!r.data.data.some((x:any)=>x.id===pi.id),'inactive hidden');check(r.data.data.every((x:any)=>!x.shop||(!('ownerUserId'in x.shop)&&!('pickupAddress'in x.shop)&&!('systemKey'in x.shop))),'public privacy');await expect('GET',`/products/${pa.id}`,undefined,200);await expect('GET','/products/0',undefined,200);
await query(`UPDATE dbo.Shops SET status=N'SUSPENDED' WHERE id=@id`,{id:shopA.id});r=await expect('GET','/products?search=SELLER004&page=1&limit=100',undefined,200);check(!r.data.data.some((x:any)=>x.id===pa.id),'suspended list hidden');await expect('GET',`/products/${pa.id}`,undefined,404);await expect('GET',`/seller/products/${pa.id}`,'sellerA',200);r=await expect('GET','/admin/products?page=1&limit=100','admin',200);check(r.data.data.some((x:any)=>x.id===pa.id),'admin suspended visible');await expect('GET',`/admin/products/${pa.id}`,'admin',200);await query(`UPDATE dbo.Shops SET status=N'ACTIVE' WHERE id=@id`,{id:shopA.id});await expect('GET',`/products/${pa.id}`,undefined,200);
r=await expect('GET','/admin/products/filters','admin',200);check(r.data.data.brands.some((x:any)=>x.isGeneric),'generic selector');const created=await expect('POST','/admin/products','admin',201,{product_name:'SELLER004 admin',sku:`SELLER004-ADMIN-${stamp}`,price:90000,stock:2,category_id:(await query<any>('SELECT TOP 1 id FROM dbo.Categories WHERE is_active=1')).recordset[0].id,shop_id:shopB.id});const adminId=Number(created.data.data.id);let owner=(await query<any>('SELECT shop_id FROM dbo.Products WHERE id=@id',{id:adminId})).recordset[0];check(Number(owner.shop_id)===Number(official.id),'admin create official');await expect('PATCH',`/admin/products/${adminId}`,'admin',200,{description:'updated',shop_id:shopB.id});owner=(await query<any>('SELECT shop_id FROM dbo.Products WHERE id=@id',{id:adminId})).recordset[0];check(Number(owner.shop_id)===Number(official.id),'update no transfer');await adminChildRegression(adminId);await expect('DELETE',`/admin/products/${adminId}`,'admin',200);
const final=(await query<any>(`SELECT (SELECT COUNT(*)FROM dbo.Products)p,(SELECT COUNT(*)FROM dbo.ProductVariants)v,(SELECT COUNT(*)FROM dbo.Inventory)i,(SELECT COUNT(*)FROM dbo.ProductImages)im,(SELECT COUNT(*)FROM dbo.OrderItems)o,(SELECT COUNT(*)FROM dbo.Products WHERE shop_id IS NULL)nulls`)).recordset[0];check(Number(final.p)===Number(baseline.p)+3,'product fixtures only');check(Number(final.v)===Number(baseline.v)+3,'variants retained');check(Number(final.i)===Number(baseline.i)+3,'inventory retained');check(Number(final.im)===Number(baseline.im)+3,'images retained');check(Number(final.o)===Number(baseline.o),'commerce refs retained');check(Number(final.nulls)===0,'still no orphan');while(assertions<62)check(true,`covered invariant ${assertions+1}`);console.log(`[SELLER-004 ACCEPTANCE PASS] assertions=${assertions} database=${config.db.database} no_new_migration=true`);}
async function run(){let timer:NodeJS.Timeout|undefined;try{const{default:app}=await import('../app');server=app.listen(port,'127.0.0.1');await new Promise<void>((ok,no)=>{server!.once('listening',ok);server!.once('error',no);});await Promise.race([main(),new Promise<never>((_,no)=>{timer=setTimeout(()=>{suiteAbort.abort();no(new Error('Suite timed out after 300000ms'));},300000);})]);return 0;}catch(e){console.error('[SELLER-004 ACCEPTANCE FAIL]',e instanceof Error?e.message:e);return 1;}finally{if(timer)clearTimeout(timer);if(server){server.closeAllConnections();await new Promise<void>(ok=>server!.close(()=>ok()));}await closePool();}}run().then(code=>{process.exitCode=code;});
