import { FormEvent,useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { Shop,shopsApi } from '../../services/shopsApi';
export default function SellerShopPage(){const[shop,setShop]=useState<Shop|null>(null),[error,setError]=useState(''),[saved,setSaved]=useState(false),[loading,setLoading]=useState(true);
useEffect(()=>{shopsApi.mine().then(r=>setShop(r.data.data)).catch(e=>setError(e.response?.data?.message||'Không thể tải Shop')).finally(()=>setLoading(false));},[]);
const save=async(e:FormEvent)=>{e.preventDefault();if(!shop)return;setError('');setSaved(false);try{const payload={name:shop.name,slug:shop.slug,logoUrl:shop.logoUrl,bannerUrl:shop.bannerUrl,description:shop.description,pickupAddress:shop.pickupAddress};const r=await shopsApi.updateMine(payload);setShop(r.data.data);setSaved(true);}catch(x:any){setError(x.response?.data?.message||'Lưu thất bại');}};
if(loading)return <p className="p-8">Đang tải Shop…</p>;if(!shop)return <p className="p-8 text-red-400">{error}</p>;
const field=(key:keyof Shop,label:string)=><label className="block"><span className="text-sm text-slate-400">{label}</span><input className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2" value={String(shop[key]??'')} onChange={e=>setShop({...shop,[key]:e.target.value||null})}/></label>;
return <section className="mx-auto max-w-3xl space-y-5 p-6"><div><h1 className="text-2xl font-bold">Hồ sơ Shop</h1><p>Trạng thái: {shop.status} · {shop.isVerified?'Đã xác minh':'Chưa xác minh'}</p>{shop.status==='SUSPENDED'&&<p className="mt-2 text-amber-400">Shop đang bị tạm ngưng và không hiển thị công khai.</p>}<Link className="text-emerald-400" to={`/shops/${shop.slug}`}>Mở trang Shop công khai</Link></div><form className="space-y-4" onSubmit={save}>{field('name','Tên Shop')}{field('slug','Slug')}{field('logoUrl','Logo URL')}{field('bannerUrl','Banner URL')}<label className="block">Mô tả<textarea className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2" value={shop.description??''} onChange={e=>setShop({...shop,description:e.target.value||null})}/></label><label className="block">Địa chỉ lấy hàng<textarea className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2" value={shop.pickupAddress??''} onChange={e=>setShop({...shop,pickupAddress:e.target.value||null})}/></label>{error&&<p className="text-red-400">{error}</p>}{saved&&<p className="text-emerald-400">Đã lưu.</p>}<button className="btn-primary" type="submit">Lưu thay đổi</button></form></section>;}
