import { FormEvent,useEffect,useState } from 'react';
import { Link,useNavigate,useParams } from 'react-router-dom';
import { SellerProductFilters,sellerProductsApi } from '../../services/sellerProductsApi';

export default function SellerProductFormPage(){
  const{id}=useParams(),editing=Boolean(id),navigate=useNavigate();
  const[filters,setFilters]=useState<SellerProductFilters|null>(null),[name,setName]=useState(''),[slug,setSlug]=useState(''),[description,setDescription]=useState(''),[categoryId,setCategoryId]=useState(''),[brandSource,setBrandSource]=useState('');
  const[sku,setSku]=useState(''),[price,setPrice]=useState(''),[stock,setStock]=useState('0'),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  useEffect(()=>{Promise.all([sellerProductsApi.filters(),editing?sellerProductsApi.detail(Number(id)):Promise.resolve(null)]).then(([filterResponse,detailResponse])=>{setFilters(filterResponse.data.data);if(detailResponse){const product=detailResponse.data.data;setName(product.name);setSlug(product.slug);setDescription(product.description||'');setCategoryId(String(product.categoryId));setBrandSource(product.brandId?`brand:${product.brandId}`:`request:${product.brandRequestId}`);}}).catch(cause=>setError(cause.response?.data?.message||'Không thể tải biểu mẫu'));},[editing,id]);
  const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError('');try{const[source,value]=brandSource.split(':');const payload:Record<string,unknown>={name,slug:slug||undefined,description:description||null,categoryId:Number(categoryId),[source==='brand'?'brandId':'brandRequestId']:Number(value)};const response=editing?await sellerProductsApi.update(Number(id),payload):await sellerProductsApi.create({...payload,defaultVariant:{name:'Default',sku,price:Number(price),initialOnHand:Number(stock),lowStockThreshold:5}});navigate(`/seller/products/${response.data.data.id}`);}catch(cause:any){setError(cause.response?.data?.message||'Không thể lưu Product');}finally{setSaving(false);}};
  if(!filters&&!error)return <p className="p-6">Đang tải…</p>;
  return <section className="mx-auto max-w-3xl space-y-5 p-6"><div><Link className="text-emerald-400" to="/seller/products">← Danh sách</Link><h1 className="mt-2 text-3xl font-bold">{editing?'Chỉnh sửa Product DRAFT':'Tạo Product DRAFT'}</h1></div><form className="space-y-4" onSubmit={submit}>
    <label className="block">Tên Product<input className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2" required maxLength={200} value={name} onChange={event=>setName(event.target.value)}/></label>
    <label className="block">Slug<input className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2" maxLength={200} value={slug} onChange={event=>setSlug(event.target.value)}/></label>
    <label className="block">Mô tả<textarea className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2" value={description} onChange={event=>setDescription(event.target.value)}/></label>
    <label className="block">Category<select className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2" required value={categoryId} onChange={event=>setCategoryId(event.target.value)}><option value="">Chọn Category</option>{filters?.categories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    <label className="block">Brand hoặc Brand Request<select className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2" required value={brandSource} onChange={event=>setBrandSource(event.target.value)}><option value="">Chọn nguồn Brand</option><optgroup label="Brand chính thức">{filters?.brands.map(item=><option key={`brand-${item.id}`} value={`brand:${item.id}`}>{item.name}{item.isGeneric?' (Generic)':''}</option>)}</optgroup><optgroup label="Brand Request">{filters?.brandRequests.map(item=><option disabled={item.status==='REJECTED'} key={`request-${item.id}`} value={`request:${item.id}`}>{item.requestedName} · {item.status}</option>)}</optgroup></select></label>
    {!editing&&<div className="grid gap-3 md:grid-cols-3"><label>SKU<input className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2" required value={sku} onChange={event=>setSku(event.target.value)}/></label><label>Giá<input className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2" type="number" min="1" required value={price} onChange={event=>setPrice(event.target.value)}/></label><label>Tồn đầu kỳ<input className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2" type="number" min="0" required value={stock} onChange={event=>setStock(event.target.value)}/></label></div>}
    {error&&<p className="text-red-400">{error}</p>}<button className="btn-primary" disabled={saving} type="submit">{saving?'Đang lưu…':'Lưu DRAFT'}</button>
  </form></section>;
}
