import { FormEvent,useCallback,useEffect,useState } from 'react';
import { Link,useNavigate,useParams } from 'react-router-dom';
import { SellerProductDetail,sellerProductsApi } from '../../services/sellerProductsApi';

export default function SellerProductDetailPage(){
  const{id}=useParams(),productId=Number(id),navigate=useNavigate(),[item,setItem]=useState<SellerProductDetail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const[variantName,setVariantName]=useState(''),[variantSku,setVariantSku]=useState(''),[variantPrice,setVariantPrice]=useState(''),[variantStock,setVariantStock]=useState('0'),[files,setFiles]=useState<File[]>([]);
  const load=useCallback(async()=>{setError('');try{setItem((await sellerProductsApi.detail(productId)).data.data);}catch(cause:any){setError(cause.response?.data?.message||'Không thể tải Product');}},[productId]);
  useEffect(()=>{void load();},[load]);
  const action=async(work:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await work();await load();}catch(cause:any){setError(cause.response?.data?.message||'Thao tác thất bại');}finally{setBusy(false);}};
  const createVariant=(event:FormEvent)=>{event.preventDefault();void action(()=>sellerProductsApi.createVariant(productId,{name:variantName,sku:variantSku,price:Number(variantPrice),initialOnHand:Number(variantStock)}));};
  const editVariant=(variantId:number,currentPrice:number)=>{const value=window.prompt('Giá mới',String(currentPrice));if(value)void action(()=>sellerProductsApi.updateVariant(productId,variantId,{price:Number(value)}));};
  const adjust=(variantId:number)=>{const delta=window.prompt('Số lượng tăng/giảm, ví dụ 5 hoặc -2');if(!delta)return;const reason=window.prompt('Lý do điều chỉnh');if(reason)void action(()=>sellerProductsApi.adjustInventory(productId,variantId,Number(delta),reason));};
  if(error&&!item)return <section className="p-6"><p className="text-red-400">{error}</p><Link to="/seller/products">Quay lại</Link></section>;
  if(!item)return <p className="p-6">Đang tải…</p>;
  const editable=['DRAFT','REJECTED'].includes(item.moderationStatus)&&item.shop.status==='ACTIVE';
  const canSubmit=editable&&!item.brandRequestId&&item.variants.length>0&&item.variants.some(variant=>variant.isDefault)&&item.variants.every(variant=>variant.price>0&&variant.onHand>=variant.reserved)&&item.images.length>0&&item.images.filter(image=>image.isPrimary).length===1;
  return <section className="mx-auto max-w-5xl space-y-6 p-6">
    <div><Link className="text-emerald-400" to="/seller/products">← Danh sách Product</Link><h1 className="mt-2 text-3xl font-bold">{item.name}</h1><p className="text-slate-400">Shop: {item.shop.name} · {item.moderationStatus} · {item.isActive?'Public':'Not public'}</p>{item.reviewReason&&<p className="mt-2 rounded border border-red-500/30 bg-red-500/10 p-3 text-red-300">Review reason: {item.reviewReason}</p>}{item.brandRequestId&&<p className="mt-2 text-amber-300">Brand Request: {item.brandRequestName} · {item.brandRequestStatus}{item.brandRequestReviewReason?` · ${item.brandRequestReviewReason}`:''}</p>}<div className="mt-3 flex flex-wrap gap-2">{editable&&<Link className="btn-primary" to={`/seller/products/${productId}/edit`}>Chỉnh sửa</Link>}{editable&&<button disabled={busy||!canSubmit} onClick={()=>void action(()=>sellerProductsApi.submit(productId))}>Gửi xét duyệt</button>}{editable&&!canSubmit&&<span className="text-sm text-amber-300">Cần Brand đã resolve, Variant mặc định hợp lệ và đúng một ảnh primary.</span>}{editable&&<button disabled={busy} className="text-red-400" onClick={()=>{if(window.confirm('Xóa Product DRAFT này?'))void sellerProductsApi.remove(productId).then(()=>navigate('/seller/products')).catch(cause=>setError(cause.response?.data?.message||'Không thể xóa'));}}>Xóa Product</button>}</div></div>
    <p className="text-sm text-slate-400">Reviewed: {item.reviewedAt||'—'} · Published: {item.publishedAt||'—'}</p>
    {error&&<p className="text-red-400">{error}</p>}
    <div className="grid gap-4 md:grid-cols-3"><div className="rounded-xl border border-slate-800 p-4"><small className="text-slate-400">Brand</small><p>{item.brand||item.brandRequestName||'—'}</p></div><div className="rounded-xl border border-slate-800 p-4"><small className="text-slate-400">Category</small><p>{item.category||'—'}</p></div><div className="rounded-xl border border-slate-800 p-4"><small className="text-slate-400">Product ID</small><p>{item.id}</p></div></div>
    <div><h2 className="mb-3 text-xl font-semibold">Variant và Inventory</h2><div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full text-left"><thead className="bg-slate-900"><tr><th className="p-3">Variant</th><th>SKU</th><th>Giá</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Thao tác</th></tr></thead><tbody>{item.variants.map(variant=><tr className="border-t border-slate-800" key={variant.id}><td className="p-3">{variant.variantName}{variant.isDefault?' · Default':''}</td><td>{variant.sku}</td><td>{Number(variant.salePrice??variant.price).toLocaleString('vi-VN')}đ</td><td>{variant.onHand}</td><td>{variant.reserved}</td><td>{variant.available}</td><td className="space-x-2">{editable&&<button disabled={busy} onClick={()=>editVariant(variant.id,variant.price)}>Sửa giá</button>}{editable&&<button disabled={busy} className="text-red-400" onClick={()=>void action(()=>sellerProductsApi.removeVariant(productId,variant.id))}>Xóa</button>}{editable&&<button disabled={busy} onClick={()=>adjust(variant.id)}>Điều chỉnh tồn</button>}</td></tr>)}</tbody></table></div>
      {editable&&<form className="mt-3 grid gap-2 md:grid-cols-5" onSubmit={createVariant}><input className="rounded border border-slate-700 bg-slate-950 p-2" placeholder="Tên Variant" required value={variantName} onChange={event=>setVariantName(event.target.value)}/><input className="rounded border border-slate-700 bg-slate-950 p-2" placeholder="SKU" required value={variantSku} onChange={event=>setVariantSku(event.target.value)}/><input className="rounded border border-slate-700 bg-slate-950 p-2" placeholder="Giá" type="number" min="1" required value={variantPrice} onChange={event=>setVariantPrice(event.target.value)}/><input className="rounded border border-slate-700 bg-slate-950 p-2" placeholder="Tồn đầu" type="number" min="0" value={variantStock} onChange={event=>setVariantStock(event.target.value)}/><button disabled={busy} type="submit">Thêm Variant</button></form>}
    </div>
    <div><h2 className="mb-3 text-xl font-semibold">Hình ảnh ({item.images.length}/8)</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{item.images.map(image=><div key={image.id}><img className="aspect-square w-full rounded-lg object-cover" src={image.imageUrl} alt={image.altText||item.name}/><p>{image.isPrimary?'Primary':''}</p>{editable&&<div className="flex gap-2">{!image.isPrimary&&<button onClick={()=>void action(()=>sellerProductsApi.setPrimary(productId,image.id))}>Đặt primary</button>}<button className="text-red-400" onClick={()=>void action(()=>sellerProductsApi.removeImage(productId,image.id))}>Xóa</button></div>}</div>)}</div>{editable&&<div className="mt-3 flex gap-2"><input type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={event=>setFiles(Array.from(event.target.files||[]))}/><button disabled={busy||!files.length} onClick={()=>void action(()=>sellerProductsApi.uploadImages(productId,files))}>Upload</button></div>}</div>
    <div><h2 className="mb-3 text-xl font-semibold">Moderation history</h2>{item.history.length===0?<p>Chưa có lịch sử.</p>:item.history.map((entry,index)=><p key={`${entry.createdAt}-${index}`}>{entry.fromStatus||'—'} → {entry.toStatus} · {entry.reason||'—'} · {entry.createdAt}</p>)}</div>
  </section>;
}
