import {useCallback,useEffect,useState} from "react";
import api from "../../api/axios";

type Status="PENDING"|"HELD"|"ELIGIBLE"|"PAID";
type Settlement={id:number;shopOrderId:number;orderNumber:string;status:Status;commissionRateSnapshot:number;grossMerchandiseAmount:number;commissionAmount:number;appliedAdjustmentAmount:number;payableAmount:number;earnedAt:string;eligibleAt:string;externalPaymentReference:string|null};
type Summary={grossMerchandiseAmount:number;commissionAmount:number;appliedAdjustmentAmount:number;pendingCarryForwardAdjustmentAmount:number;netPayableAmount:number;pendingAmount:number;heldAmount:number;eligibleAmount:number;paidAmount:number;deliveredShopOrderCount:number;settlementCount:number};
type Adjustment={id:number;signedAmount:number;status:"PENDING"|"APPLIED"|"VOIDED";reason:string;sourceReference:string|null;sourcePaidSettlementId:number|null;appliedSettlementId:number|null;createdAt:string};
const money=(value:number)=>Number(value||0).toLocaleString("vi-VN",{style:"currency",currency:"VND"});
const today=new Date().toISOString().slice(0,10),weekAgo=new Date(Date.now()-6*86400000).toISOString().slice(0,10);

export default function SellerRevenuePage(){
  const [from,setFrom]=useState(weekAgo),[to,setTo]=useState(today),[status,setStatus]=useState<Status|"" >(""),[summary,setSummary]=useState<Summary|null>(null),[rows,setRows]=useState<Settlement[]>([]),[adjustments,setAdjustments]=useState<Adjustment[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const params={from,to,status:status||undefined};const [summaryResponse,listResponse,adjustmentResponse]=await Promise.all([api.get<{data:Summary}>("/seller/finance/summary",{params}),api.get<{data:{items:Settlement[]}}>("/seller/finance/settlements",{params}),api.get<{data:Adjustment[]}>("/seller/finance/adjustments")]);setSummary(summaryResponse.data.data);setRows(listResponse.data.data.items);setAdjustments(adjustmentResponse.data.data);}catch{setError("Không thể tải dữ liệu doanh thu.");}finally{setLoading(false);}},[from,to,status]);
  useEffect(()=>{void load();},[load]);
  const cards=summary?[["Doanh thu merchandise",summary.grossMerchandiseAmount],["Hoa hồng GymFit",summary.commissionAmount],["Điều chỉnh đã áp dụng",summary.appliedAdjustmentAmount],["Điều chỉnh chuyển tiếp",summary.pendingCarryForwardAdjustmentAmount],["Khoản phải trả dự kiến",summary.netPayableAmount],["Pending",summary.pendingAmount],["Held",summary.heldAmount],["Eligible",summary.eligibleAmount],["Paid",summary.paidAmount]]:[];
  return <main className="space-y-6 p-4 md:p-8"><header><h1 className="text-3xl font-bold">Doanh thu người bán</h1><p className="text-slate-400">Đối soát merchandise, hoa hồng và khoản phải trả theo ShopOrder đã giao.</p></header>
    <section className="flex flex-wrap gap-3 rounded-xl border border-white/10 p-4"><label>Từ <input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="ml-2 rounded bg-slate-900 p-2"/></label><label>Đến <input type="date" value={to} onChange={e=>setTo(e.target.value)} className="ml-2 rounded bg-slate-900 p-2"/></label><select value={status} onChange={e=>setStatus(e.target.value as Status|"")} className="rounded bg-slate-900 p-2"><option value="">Tất cả trạng thái</option><option>PENDING</option><option>HELD</option><option>ELIGIBLE</option><option>PAID</option></select><button className="btn-secondary" onClick={()=>void load()}>Làm mới</button></section>
    {error&&<p role="alert" className="rounded bg-red-500/10 p-3 text-red-300">{error}</p>}
    {summary&&<><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([label,value])=><article key={String(label)} className="rounded-xl border border-white/10 bg-white/5 p-4"><p className="text-sm text-slate-400">{label}</p><strong className="text-xl">{money(Number(value))}</strong></article>)}</section><p className="text-sm text-slate-400">{summary.deliveredShopOrderCount} ShopOrder đã giao · {summary.settlementCount} settlement</p></>}
    {loading?<p>Đang tải…</p>:rows.length===0?<p className="rounded-xl border border-dashed border-white/10 p-8 text-center text-slate-400">Chưa có settlement trong khoảng đã chọn.</p>:<div className="overflow-x-auto rounded-xl border border-white/10"><table className="w-full min-w-[1000px]"><thead><tr><th>Order / ShopOrder</th><th>Giao hàng</th><th>Gross</th><th>Tỷ lệ</th><th>Hoa hồng</th><th>Điều chỉnh</th><th>Phải trả</th><th>Đủ điều kiện</th><th>Trạng thái</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t border-white/10"><td className="p-3">{row.orderNumber} / #{row.shopOrderId}</td><td>{new Date(row.earnedAt).toLocaleString("vi-VN")}</td><td>{money(row.grossMerchandiseAmount)}</td><td>{(row.commissionRateSnapshot/100).toFixed(2)}%</td><td>{money(row.commissionAmount)}</td><td>{money(row.appliedAdjustmentAmount)}</td><td>{money(row.payableAmount)}</td><td>{new Date(row.eligibleAt).toLocaleString("vi-VN")}</td><td>{row.status}{row.externalPaymentReference&&<small className="block text-slate-400">{row.externalPaymentReference}</small>}</td></tr>)}</tbody></table></div>}
    <section className="space-y-3"><h2 className="text-xl font-semibold">Điều chỉnh</h2>{adjustments.length===0?<p className="text-slate-400">Chưa có điều chỉnh được hiển thị.</p>:<div className="overflow-x-auto rounded-xl border border-white/10"><table className="w-full min-w-[700px]"><thead><tr><th>Ngày</th><th>Số tiền</th><th>Loại</th><th>Trạng thái</th><th>Lý do / tham chiếu</th></tr></thead><tbody>{adjustments.map(item=><tr key={item.id} className="border-t border-white/10"><td className="p-3">{new Date(item.createdAt).toLocaleString("vi-VN")}</td><td className={item.signedAmount<0?"text-red-300":"text-emerald-300"}>{money(item.signedAmount)}</td><td>{item.sourcePaidSettlementId?"Carry-forward":"Settlement"}</td><td>{item.status}</td><td>{item.reason}{item.sourceReference&&<small className="block text-slate-400">{item.sourceReference}</small>}</td></tr>)}</tbody></table></div>}</section>
  </main>;
}
