import { Request, Response, NextFunction } from 'express';
import * as service from './coach-workspace.service';
import { sendSuccess } from '../../utils/response';

const actor = (req: Request) => req.user!.userId;
const numberParam = (req: Request, key: string) => Number(req.params[key]);
const run = (handler: (req: Request) => Promise<unknown>, statusCode = 200) => async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await handler(req), 'Success', statusCode); } catch (error) { next(error); } };

export const getDashboard = run(req => service.dashboard(actor(req)));
export const getSelfProfile = run(req => service.getSelfProfile(actor(req)));
export const updateSelfProfile = run(req => service.updateSelfProfile(actor(req), req.body));
export const listExercises = run(req => service.listExercises({ q: req.query.q as string | undefined, muscleGroup: req.query.muscleGroup as string | undefined, difficulty: req.query.difficulty as string | undefined, equipment: req.query.equipment as string | undefined, page: Number(req.query.page), limit: Number(req.query.limit), sort: String(req.query.sort) }));
export const getExercise = run(req => service.getExercise(numberParam(req, 'exerciseId')));
export const listPrograms = run(req => service.listPrograms(actor(req), Number(req.query.page), Number(req.query.limit), req.query.q as string | undefined));
export const getProgram = run(req => service.getProgram(actor(req), numberParam(req, 'programId')));
export const createProgram = run(req => service.createProgram(actor(req), req.body), 201);
export const updateProgram = run(req => service.updateProgram(actor(req), numberParam(req, 'programId'), req.body));
export const activateProgram = run(req => service.setProgramActive(actor(req), numberParam(req, 'programId'), true));
export const deactivateProgram = run(req => service.setProgramActive(actor(req), numberParam(req, 'programId'), false));
export const publishProgram = run(req => service.publishProgram(actor(req), numberParam(req, 'programId')));
export const cloneProgramVersion = run(req => service.cloneProgramVersion(actor(req), numberParam(req, 'programId')), 201);
export const archiveProgram = run(req => service.archiveProgram(actor(req), numberParam(req, 'programId')));
export const createDay = run(req => service.createDay(actor(req), numberParam(req, 'programId'), req.body), 201);
export const updateDay = run(req => service.updateDay(actor(req), numberParam(req, 'dayId'), req.body));
export const deleteDay = run(async req => { await service.deleteDay(actor(req), numberParam(req, 'dayId')); return null; });
export const reorderDays = run(async req => { await service.reorderDays(actor(req), numberParam(req, 'programId'), req.body.ids); return { reordered: true }; });
export const createProgramExercise = run(req => service.createProgramExercise(actor(req), numberParam(req, 'dayId'), req.body), 201);
export const updateProgramExercise = run(req => service.updateProgramExercise(actor(req), numberParam(req, 'programExerciseId'), req.body));
export const deleteProgramExercise = run(async req => { await service.deleteProgramExercise(actor(req), numberParam(req, 'programExerciseId')); return null; });
export const reorderProgramExercises = run(async req => { await service.reorderProgramExercises(actor(req), numberParam(req, 'dayId'), req.body.ids); return { reordered: true }; });
export const listMembers = run(req => service.listMembers(actor(req), Number(req.query.page), Number(req.query.limit), req.query.q as string | undefined));
export const getMember = run(req => service.getMember(actor(req), numberParam(req, 'memberId')));
export const getMemberContext = run(req => service.getMemberContext(actor(req), numberParam(req, 'memberId')));
export const updateMemberContext = run(req => service.updateMemberContext(actor(req), numberParam(req, 'memberId'), req.body));
export const listAssignments = run(req => service.listAssignments(actor(req), Number(req.query.page), Number(req.query.limit), req.query.memberId ? Number(req.query.memberId) : undefined));
export const createAssignment = run(req => service.createAssignment(actor(req), req.body), 201);
export const getAssignment = run(async req => service.assertAssignment(actor(req), numberParam(req, 'assignmentId')));
export const pauseAssignment = run(req => service.transitionAssignment(actor(req), numberParam(req, 'assignmentId'), 'PAUSED'));
export const resumeAssignment = run(req => service.transitionAssignment(actor(req), numberParam(req, 'assignmentId'), 'ACTIVE'));
export const completeAssignment = run(req => service.transitionAssignment(actor(req), numberParam(req, 'assignmentId'), 'COMPLETED'));
export const cancelAssignment = run(req => service.transitionAssignment(actor(req), numberParam(req, 'assignmentId'), 'CANCELLED'));
export const listSchedules = run(req => service.listSchedules(actor(req), Number(req.query.page), Number(req.query.limit), req.query.memberId ? Number(req.query.memberId) : undefined, req.query.fromDate as string | undefined, req.query.toDate as string | undefined));
export const generateSchedules = run(req => service.generateSchedules(actor(req), numberParam(req, 'assignmentId'), req.body));
export const reschedule = run(req => service.reschedule(actor(req), numberParam(req, 'scheduleId'), req.body.scheduledDate));
export const cancelSchedule = run(req => service.cancelSchedule(actor(req), numberParam(req, 'scheduleId')));
export const listSessions = run(req => service.listSessions(actor(req), numberParam(req, 'memberId'), Number(req.query.page), Number(req.query.limit)));
export const getSession = run(req => service.getSession(actor(req), numberParam(req, 'memberId'), numberParam(req, 'sessionId'), req.params.source as service.CoachSessionSource | undefined));
export const getProgress = run(req => service.getProgress(actor(req), numberParam(req, 'memberId')));
