import api from '../api/axios';
import type { CoachAssignment, CoachDashboardData, CoachExercise, CoachMember, CoachMemberContextResponse, CoachMemberDetail, CoachProgram, CoachProgramDay, CoachProgramExercise, CoachProgress, CoachSchedule, CoachSessionDetail, CoachSessionHistoryItem } from '../types/coachWorkspace';

export type Page<T> = { items:T[]; page:number; limit:number; total:number; totalPages:number };
export type RequestOptions = { signal?: AbortSignal };
const data = <T,>(response:{data:{data:T}}) => response.data.data;
const page = <T,>(response:{data:{data:Page<T>}}) => response.data.data;
const coach = '/coach';
const getConfig = (options?:RequestOptions) => options?.signal ? { signal: options.signal } : undefined;
export const getCoachDashboard = async (options?:RequestOptions) => data<CoachDashboardData>(await api.get(`${coach}/dashboard`, getConfig(options)));
export const listCoachExercises = async (params:Record<string,unknown>, options?:RequestOptions) => page<CoachExercise>(await api.get(`${coach}/exercises`, { params, ...getConfig(options) }));
export const getCoachExercise = async (id:number) => data<CoachExercise>(await api.get(`${coach}/exercises/${id}`));
export const listPrograms = async (params:Record<string,unknown>, options?:RequestOptions) => page<CoachProgram>(await api.get(`${coach}/workout-programs`, { params, ...getConfig(options) }));
export const createProgram = async (body:Record<string,unknown>) => data<CoachProgram>(await api.post(`${coach}/workout-programs`, body));
export const getProgram = async (id:number) => data<CoachProgram>(await api.get(`${coach}/workout-programs/${id}`));
export const updateProgram = async (id:number, body:Record<string,unknown>) => data<CoachProgram>(await api.patch(`${coach}/workout-programs/${id}`, body));
export const activateProgram = async (id:number) => data<CoachProgram>(await api.post(`${coach}/workout-programs/${id}/activate`, {}));
export const deactivateProgram = async (id:number) => data<CoachProgram>(await api.post(`${coach}/workout-programs/${id}/deactivate`, {}));
export const publishProgram = async (id:number) => data<CoachProgram>(await api.post(`${coach}/workout-programs/${id}/publish`, {}));
export const cloneProgramVersion = async (id:number) => data<CoachProgram>(await api.post(`${coach}/workout-programs/${id}/clone-version`, {}));
export const archiveProgram = async (id:number) => data<CoachProgram>(await api.post(`${coach}/workout-programs/${id}/archive`, {}));
export const createDay = async (programId:number, body:Record<string,unknown>) => data<CoachProgramDay>(await api.post(`${coach}/workout-programs/${programId}/days`, body));
export const updateDay = async (dayId:number, body:Record<string,unknown>) => data<CoachProgramDay>(await api.patch(`${coach}/workout-program-days/${dayId}`, body));
export const deleteDay = async (dayId:number) => api.delete(`${coach}/workout-program-days/${dayId}`);
export const reorderDays = async (programId:number, ids:number[]) => api.post(`${coach}/workout-programs/${programId}/days/reorder`, { ids });
export const createProgramExercise = async (dayId:number, body:Record<string,unknown>) => data<CoachProgramExercise>(await api.post(`${coach}/workout-program-days/${dayId}/exercises`, body));
export const updateProgramExercise = async (id:number, body:Record<string,unknown>) => data<CoachProgramExercise>(await api.patch(`${coach}/workout-program-exercises/${id}`, body));
export const deleteProgramExercise = async (id:number) => api.delete(`${coach}/workout-program-exercises/${id}`);
export const reorderProgramExercises = async (dayId:number, ids:number[]) => api.post(`${coach}/workout-program-days/${dayId}/exercises/reorder`, { ids });
export const listMembers = async (params:Record<string,unknown>, options?:RequestOptions) => page<CoachMember>(await api.get(`${coach}/members`, { params, ...getConfig(options) }));
export const getMember = async (id:number) => data<CoachMemberDetail>(await api.get(`${coach}/members/${id}`));
export const getMemberContext = async (id:number) => data<CoachMemberContextResponse>(await api.get(`${coach}/members/${id}/context`));
export const updateMemberContext = async (id:number, body:Record<string,unknown>) => data<CoachMemberContextResponse>(await api.patch(`${coach}/members/${id}/context`, body));
export const listAssignments = async (params:Record<string,unknown>, options?:RequestOptions) => page<CoachAssignment>(await api.get(`${coach}/assignments`, { params, ...getConfig(options) }));
export const createAssignment = async (body:Record<string,unknown>) => data<CoachAssignment>(await api.post(`${coach}/assignments`, body));
export const getAssignment = async (id:number) => data<CoachAssignment>(await api.get(`${coach}/assignments/${id}`));
export const transitionAssignment = async (id:number, action:'pause'|'resume'|'complete'|'cancel') => data<CoachAssignment>(await api.post(`${coach}/assignments/${id}/${action}`, {}));
export const listSchedules = async (params:Record<string,unknown>, options?:RequestOptions) => page<CoachSchedule>(await api.get(`${coach}/schedules`, { params, ...getConfig(options) }));
export type ScheduleGenerationResult = {
  inserted:number;
  skipped:number;
  skippedExisting:number;
  skippedOutsideAssignment:number;
  skippedOutsideProgram:number;
  requestedFromDate:string;
  fromDate:string;
  toDate:string;
  effectiveFromDate:string;
  effectiveToDate:string;
  horizonDays:number;
};
export const generateSchedules = async (id:number, body:Record<string,unknown>) => data<ScheduleGenerationResult>(await api.post(`${coach}/assignments/${id}/schedules/generate`, body));
export const reschedule = async (id:number, scheduledDate:string) => data<CoachSchedule>(await api.post(`${coach}/schedules/${id}/reschedule`, { scheduledDate }));
export const cancelSchedule = async (id:number) => data<CoachSchedule>(await api.post(`${coach}/schedules/${id}/cancel`, {}));
export const listSessions = async (memberId:number, params:Record<string,unknown>, options?:RequestOptions) => page<CoachSessionHistoryItem>(await api.get(`${coach}/members/${memberId}/sessions`, { params, ...getConfig(options) }));
export const getSession = async (memberId:number, source:'legacy'|'member'|undefined, sessionId:number) => data<CoachSessionDetail>(await api.get(`${coach}/members/${memberId}/sessions${source ? `/${source}` : ''}/${sessionId}`));
export const getProgress = async (memberId:number) => data<CoachProgress>(await api.get(`${coach}/members/${memberId}/progress`));
