import api from '../api/axios';
export type ModerationStatus='DRAFT'|'PENDING_REVIEW'|'PUBLISHED'|'REJECTED'|'SUSPENDED';
export type SellerProductSummary={id:number;name:string;slug:string;isActive:boolean;moderationStatus:ModerationStatus;submittedAt:string|null;reviewedAt:string|null;publishedAt:string|null;reviewReason:string|null;createdAt:string;updatedAt:string;brandId:number|null;brand:string|null;brandRequestId:number|null;brandRequestName?:string|null;brandRequestStatus?:string|null;categoryId:number|null;category:string|null;variantCount:number;availableInventory:number|null;price:number|null;salePrice:number|null;primaryImage:string|null;};
export type SellerVariant={id:number;variantName:string;sku:string;barcode:string|null;price:number;salePrice:number|null;weight:number|null;isActive:boolean;isDefault:boolean;inventoryId:number;onHand:number;reserved:number;available:number;lowStockThreshold:number};
export type SellerImage={id:number;imageUrl:string;altText:string|null;isPrimary:boolean;sortOrder:number};
export type SellerProductDetail=SellerProductSummary&{description:string|null;specifications:string|null;brandRequestReviewReason?:string|null;shop:{id:number;name:string;slug:string;status:'ACTIVE'|'SUSPENDED';isVerified:boolean};variants:SellerVariant[];images:SellerImage[];history:Array<{fromStatus:string|null;toStatus:ModerationStatus;reason:string|null;createdAt:string;actorLabel:string}>;};
export type SellerProductFilters={categories:Array<{id:number;name:string;slug:string}>;brands:Array<{id:number;name:string;slug:string;isGeneric:boolean}>;brandRequests:Array<{id:number;requestedName:string;status:'PENDING'|'APPROVED'|'REJECTED';resolvedBrandId:number|null;reviewReason:string|null}>};
export const sellerProductsApi={
  list:(params:Record<string,unknown>)=>api.get('/seller/products',{params}),detail:(id:number)=>api.get(`/seller/products/${id}`),filters:()=>api.get('/seller/products/filters'),
  create:(data:Record<string,unknown>)=>api.post('/seller/products',data),update:(id:number,data:Record<string,unknown>)=>api.patch(`/seller/products/${id}`,data),remove:(id:number)=>api.delete(`/seller/products/${id}`),submit:(id:number)=>api.post(`/seller/products/${id}/submit`),
  createVariant:(productId:number,data:Record<string,unknown>)=>api.post(`/seller/products/${productId}/variants`,data),updateVariant:(productId:number,variantId:number,data:Record<string,unknown>)=>api.patch(`/seller/products/${productId}/variants/${variantId}`,data),removeVariant:(productId:number,variantId:number)=>api.delete(`/seller/products/${productId}/variants/${variantId}`),
  uploadImages:(productId:number,files:File[])=>{const form=new FormData();files.forEach(file=>form.append('images',file));return api.post(`/seller/products/${productId}/images`,form);},
  setPrimary:(productId:number,imageId:number)=>api.patch(`/seller/products/${productId}/images/${imageId}/primary`),removeImage:(productId:number,imageId:number)=>api.delete(`/seller/products/${productId}/images/${imageId}`),
  adjustInventory:(productId:number,variantId:number,quantityDelta:number,reason:string)=>api.post(`/seller/products/${productId}/variants/${variantId}/inventory/adjustments`,{quantityDelta,reason}),
};
