export interface MemberAssignment { id:number; member_id:number; program_id:number; coach_id:number; start_date:string; end_date:string|null; status:string; schedule_timezone:string; note:string|null; program_name:string; program_description:string|null; goal:string; difficulty:string; duration_weeks:number; days_per_week:number; coach_name:string; }
export interface MemberProgramExercise { program_exercise_id:number; program_day_id:number; exercise_id:number; sort_order:number; target_sets:number|null; target_reps_min:number|null; target_reps_max:number|null; target_weight:number|null; target_duration_seconds:number|null; rest_seconds:number|null; tempo:string|null; coach_note:string|null; exercise_name:string; exercise_slug:string; }
export interface MemberProgramDay { id:number; program_id:number; week_number:number; day_number:number; title:string; description:string|null; sort_order:number; exercises:MemberProgramExercise[]; }
export interface MemberSchedule { id:number; assignment_id:number; program_day_id:number; scheduled_date:string; status:string; created_at:string; updated_at:string; member_id:number; program_id:number; schedule_timezone:string; program_name:string; week_number:number; day_number:number; day_title:string; can_start?:boolean; blocked_reason?:string|null; }
export interface MemberScheduleDetail extends MemberSchedule { assignment_status:string; day_description:string|null; exercises:MemberProgramExercise[]; }
export interface MemberSetLog { id:number; set_number:number; reps:number|null; weight_kg:number|null; duration_seconds:number|null; distance_meters:number|null; completed:boolean; note:string|null; created_at:string; updated_at:string; }
export interface MemberSessionExercise { session_exercise_id:number; program_exercise_id:number|null; exercise_id:number; exercise_name:string; sort_order:number; target_sets:number|null; target_reps_min:number|null; target_reps_max:number|null; target_weight:number|null; target_duration_seconds:number|null; rest_seconds:number|null; coach_note:string|null; sets:MemberSetLog[]; }
export interface MemberSession { id:number; member_id:number; assignment_id:number; schedule_id:number; started_at:string; ended_at:string|null; status:'IN_PROGRESS'|'COMPLETED'|'ABANDONED'|string; total_duration_seconds:number|null; note:string|null; program:{id:number;name:string}; schedule:{id:number;scheduled_date:string;status:string;timezone:string;day_title:string}; exercises:MemberSessionExercise[]; }
export interface MemberCurrent { assignment:MemberAssignment|null; program:{days:MemberProgramDay[]}|null; upcomingSchedules:MemberSchedule[]; activeSession:MemberSession|null; }
export interface MemberSchedulePage { items:MemberSchedule[]; pagination:{page:number;limit:number;total:number;totalPages:number}; }
export interface MemberSessionListItem { id:number; member_id:number; assignment_id:number; schedule_id:number; program_id:number; program_name:string; day_title:string; scheduled_date:string; schedule_status:string; status:string; started_at:string; completed_at:string|null; total_duration_seconds:number|null; note:string|null; exercise_count:number; set_count:number; completed_set_count:number; }
export interface RecentWorkoutSession { id:number; program_id:number; program_name:string; day_title:string; scheduled_date:string; status:'COMPLETED'|'ABANDONED'|string; completed_at:string|null; total_duration_seconds:number|null; }
export interface MemberSessionPage { items:MemberSessionListItem[]; pagination:{page:number;limit:number;total:number;totalPages:number}; }
export interface MemberExerciseProgress { exercise_id:number; exercise_name:string; session_count:number; completed_sets:number; total_reps:number; training_volume:number; }
export interface MemberExerciseProgressHistory { session_id:number; scheduled_date:string; completed_at:string|null; set_count:number; total_reps:number; max_weight_kg:number|null; total_volume:number; }
export interface MemberExerciseProgressDetail { exercise:{id:number;name:string}; last_performed_at:string|null; session_count:number; total_sets:number; total_reps:number; max_weight_kg:number|null; total_volume:number; history:MemberExerciseProgressHistory[]; }
export interface MemberProgress { completed_sessions:number; total_duration:number; training_volume:number; completion_rate:number|null; recent_sessions:RecentWorkoutSession[]; exercise_history:MemberExerciseProgress[]; due_schedules:number; completed_due_schedules:number; blockedReason:null; dataSources:{legacySessions:boolean;setLogs:boolean;memberProgressFlow:boolean}; }
export interface MemberProgressSessionPage { items:MemberSessionListItem[]; pagination:{page:number;limit:number;total:number;totalPages:number}; }
