export type PaymentStatus='UNPAID'|'PENDING'|'PAID'|'FAILED'|'PARTIALLY_REFUNDED'|'REFUNDED';
export type OrderStatus='PENDING'|'CONFIRMED'|'PROCESSING'|'SHIPPED'|'DELIVERED'|'CANCELLED';
export interface CustomerOrderItem { id:number; productId:number; variantId:number; productName:string; variantName:string; sku:string; quantity:number; unitPrice:number; lineTotal:number }
export type ShopOrderStatus='PENDING_PAYMENT'|'PENDING_STOCK_CHECK'|'PREPARING'|'READY_FOR_PICKUP'|'PICKED_UP'|'IN_TRANSIT_TO_HUB'|'RECEIVED_AT_HUB'|'HUB_CHECK_PASSED'|'HUB_CHECK_FAILED'|'UNABLE_TO_FULFILL'|'CANCELLED';
export type ParentLogisticsStatus='WAITING_FOR_SHOPS'|'READY_TO_SHIP'|'SHIPPED'|'DELIVERED';
export interface CustomerShopOrder { id:number;shop:{id:number;name:string;slug:string};status:ShopOrderStatus;subtotal:number;readyForPickupAt?:string|null;pickedUpAt?:string|null;inTransitToHubAt?:string|null;receivedAtHubAt?:string|null;hubCheckedAt?:string|null;deliveredAt?:string|null;hubCheckFailed:boolean;createdAt:string;updatedAt:string;refund?:{id:number;merchandiseAmount:number;shippingAmount:number;totalAmount:number;status:string;reason:string}|null;compensationVoucher?:{id:number;code:string;amount:number;minimumOrderAmount:number;expiresAt:string;status:string}|null;items:CustomerOrderItem[] }
export type BankTransferConfigurationField='BANK_NAME'|'BANK_ACCOUNT_NAME'|'BANK_ACCOUNT_NUMBER'|'BANK_QR_IMAGE_URL';
export interface BankTransferPublicConfig { ready:boolean; missingFields:BankTransferConfigurationField[]; bankName:string|null; accountName:string|null; accountNumber:string|null; qrImageUrl:string|null; transferContent:string }
export type CancellationReason='AUTO_EXPIRED'|'CUSTOMER_CANCELLED'|'ADMIN_CANCELLED'|null;
export interface CustomerOrderDetail { id:number; orderNumber:string; userId:number; orderStatus:string; logisticsStatus:ParentLogisticsStatus|null;readyToShipAt:string|null;shippedAt:string|null;deliveredAt:string|null;paymentStatus:PaymentStatus; paymentProvider:string|null; paymentReference:string|null; reservationExpiresAt:string|null; cancellationReason:CancellationReason; subtotal:number; discountAmount:number; shippingAmount:number; taxAmount:number; totalAmount:number; currency:string; createdAt:string; updatedAt:string; customerName:string; customerEmail:string; customerPhone:string|null; addressLine1:string|null; addressLine2:string|null; city:string|null; state:string|null; postalCode:string|null; country:string|null; items:CustomerOrderItem[]; shopOrders:CustomerShopOrder[]; bankTransfer?:BankTransferPublicConfig }
export interface PaymentNotificationInput { paymentReference?:string }
export type PaymentNotificationReason='PAYMENT_UPDATED'|'ALREADY_PENDING'|'MAIL_NOT_CONFIGURED'|'MAIL_DELIVERY_FAILED';
export interface PaymentNotificationResult { orderId:number; orderNumber:string; paymentStatus:'PENDING'; paymentProvider:'BANK_TRANSFER'; paymentUpdated:boolean; notificationSkipped:boolean; reason:PaymentNotificationReason; emailConfigured:boolean; emailAttempted:boolean; emailSent:boolean }
export interface CreateOrderInput { customerName:string; customerPhone:string; shippingAddressLine1:string; shippingAddressLine2?:string; shippingCity:string; shippingState?:string; shippingPostalCode?:string; shippingCountry:string; cartVersion:number;voucherCode?:string }
export interface CreateOrderResult { id:number; orderNumber:string; orderStatus:string; paymentStatus:string; paymentProvider:string; subtotal:number; totalAmount:number; currency:string; itemCount:number; createdAt:string; reservationExpiresAt:string;shopOrders:Array<{id:number;shop:{id:number;name:string;slug:string};status:'PENDING_PAYMENT';subtotal:number}>;cartVersion:number }
export interface CustomerCancelOrderInput { note?:string }
export interface CustomerCancelOrderResult { orderId:number; orderNumber:string; orderStatus:'CANCELLED'; releasedItems:number }
export interface CheckoutFormValues { customerName:string; customerPhone:string; addressLine1:string; addressLine2:string; city:string; state:string; postalCode:string; country:string }
export type CheckoutFormErrors = Partial<Record<keyof CheckoutFormValues | 'items', string>>;
export interface CustomerOrderSummary { id:number;orderNumber:string;orderStatus:OrderStatus;paymentStatus:PaymentStatus;paymentProvider:string|null;itemCount:number;subtotal:number;totalAmount:number;currency:string;reservationExpiresAt:string|null;createdAt:string;updatedAt:string }
export interface CustomerOrderListFilters { page:number;limit:10|20|50;orderStatus?:OrderStatus;paymentStatus?:PaymentStatus;sortOrder:'asc'|'desc' }
export interface PaginatedCustomerOrders { items:CustomerOrderSummary[];page:number;limit:number;total:number;totalPages:number }
