import type { ChatbotAction, ChatbotIntent, ChatbotRoute, ChatbotRole } from './chatbotTypes';
import { suggestions } from './chatbotSuggestions';

const allRoles: ChatbotRole[] = ['guest', 'member', 'coach', 'seller', 'admin'];
const memberRoles: ChatbotRole[] = ['member'];
const coachRoles: ChatbotRole[] = ['coach'];
const sellerRoles: ChatbotRole[] = ['seller'];
const adminRoles: ChatbotRole[] = ['admin'];
const buyerRoles: ChatbotRole[] = ['member', 'coach'];

const action = (id: string, label: string, route: ChatbotRoute, roles?: ChatbotRole[]): ChatbotAction => ({ id, label, kind: 'NAVIGATE', route, roles });

const commonActions = {
  products: action('open-products', 'Mở trang Sản phẩm', '/products'),
  coaches: action('open-coaches', 'Xem Coach', '/coaches'),
  plans: action('open-plans', 'Xem gói hội viên', '/membership'),
  account: action('open-account', 'Mở tài khoản', '/profile', ['member', 'coach', 'seller', 'admin']),
  appointments: action('open-appointments', 'Mở lịch hẹn', '/appointments', memberRoles),
  workouts: action('open-workouts', 'Mở Workout', '/workouts', memberRoles),
  orders: action('open-orders', 'Mở đơn hàng', '/orders', buyerRoles),
  cart: action('open-cart', 'Mở giỏ hàng', '/cart'),
  checkout: action('open-checkout', 'Mở checkout', '/checkout', buyerRoles),
  sellerApply: action('open-seller-apply', 'Mở đăng ký Seller', '/seller/apply', ['member', 'seller']),
  seller: action('open-seller', 'Mở khu Seller', '/seller', sellerRoles),
  admin: action('open-admin', 'Mở khu Admin', '/admin', adminRoles),
};

const intents: ChatbotIntent[] = [
  {
    id: 'greeting', category: 'GENERAL', priority: 10, roles: allRoles,
    exactPhrases: ['xin chào', 'chào', 'hello', 'hi', 'hey'], keywordsAny: ['chao', 'hello', 'hi', 'hey'], minimumScore: 3,
    staticMessage: 'Chào bạn! Mình có thể hướng dẫn các tính năng GYMFIT hoặc tra cứu dữ liệu công khai và dữ liệu của chính bạn khi hệ thống cho phép.',
    suggestions: [suggestions.products, suggestions.coaches, suggestions.plans, suggestions.help], actions: [commonActions.products, commonActions.coaches, commonActions.plans],
  },
  {
    id: 'help', category: 'GENERAL', priority: 8, roles: allRoles, exactPhrases: ['trợ giúp', 'help', 'bạn làm được gì'],
    keywordsAny: ['tro giup', 'help', 'ho tro', 'lam duoc gi'], minimumScore: 3,
    staticMessage: 'Bạn có thể hỏi về Sản phẩm, Coach, gói hội viên, lịch hẹn, Workout, đơn hàng, Seller, Admin hoặc tài khoản. Bạn cũng có thể chọn một gợi ý bên dưới.',
    suggestions: [suggestions.products, suggestions.coaches, suggestions.plans, suggestions.services, suggestions.account],
  },
  {
    id: 'services_overview', category: 'GENERAL', priority: 7, roles: allRoles, exactPhrases: ['dịch vụ của web có gì', 'gymfit có gì'],
    keywordsAny: ['dich vu', 'tinh nang', 'chuc nang', 'gymfit co gi', 'web co gi'], minimumScore: 3,
    staticMessage: 'GYMFIT hiện có các nhóm chức năng chính: sản phẩm và Shop công khai, Coach và lịch hẹn, gói hội viên, Workout/tiến độ, đơn hàng, Seller và khu quản trị theo quyền. Mình chỉ mở hoặc tra cứu những route/API hệ thống thật sự cung cấp.',
    suggestions: [suggestions.products, suggestions.coaches, suggestions.plans, suggestions.help],
    actions: [commonActions.products, commonActions.coaches, commonActions.plans],
  },
  { id: 'thanks', category: 'GENERAL', priority: 5, roles: allRoles, exactPhrases: ['cảm ơn', 'thanks'], keywordsAny: ['cam on', 'thanks', 'thank you'], minimumScore: 3, staticMessage: 'Không có gì. Nếu cần, bạn có thể chọn một gợi ý hoặc nhập câu hỏi mới.', suggestions: [suggestions.help, suggestions.products, suggestions.coaches] },
  { id: 'goodbye', category: 'GENERAL', priority: 5, roles: allRoles, exactPhrases: ['tạm biệt', 'bye'], keywordsAny: ['tam biet', 'bye', 'hen gap lai'], minimumScore: 3, staticMessage: 'Tạm biệt! Khi cần hỗ trợ GYMFIT, bạn có thể mở lại khung chat.', suggestions: [suggestions.help] },
  {
    id: 'login', category: 'AUTH', priority: 7, roles: ['guest'], exactPhrases: ['đăng nhập', 'login'], keywordsAny: ['dang nhap', 'login', 'vao tai khoan'], minimumScore: 3,
    staticMessage: 'Bạn có thể đăng nhập tại trang đăng nhập. Chatbot không yêu cầu hoặc lưu mật khẩu của bạn.', suggestions: [suggestions.products, suggestions.coaches], actions: [action('login', 'Đăng nhập', '/login')],
  },
  {
    id: 'register', category: 'AUTH', priority: 7, roles: ['guest'], exactPhrases: ['đăng ký', 'register', 'tạo tài khoản'], keywordsAny: ['dang ky', 'register', 'tao tai khoan'], minimumScore: 3,
    staticMessage: 'Bạn có thể tạo tài khoản tại trang đăng ký. Sau khi đăng nhập, các route riêng sẽ được backend quyết định theo role.', suggestions: [suggestions.products, suggestions.coaches], actions: [action('register', 'Đăng ký', '/register')],
  },
  { id: 'profile', category: 'AUTH', priority: 6, roles: ['member', 'coach', 'seller', 'admin'], keywordsAny: ['ho so', 'profile', 'thong tin ca nhan'], minimumScore: 3, staticMessage: 'Bạn có thể xem hồ sơ tại route Profile. Chatbot chỉ điều hướng, không tự cập nhật thông tin.', suggestions: [suggestions.account], actions: [commonActions.account] },
  { id: 'settings', category: 'AUTH', priority: 6, roles: ['member', 'coach', 'seller', 'admin'], keywordsAny: ['cai dat', 'settings', 'thiet lap'], minimumScore: 3, staticMessage: 'Bạn có thể mở phần Cài đặt để tự kiểm tra tài khoản. Chatbot không thay đổi cài đặt thay bạn.', suggestions: [suggestions.account], actions: [action('settings', 'Mở Cài đặt', '/settings', ['member', 'coach', 'seller', 'admin'])] },
  { id: 'password', category: 'AUTH', priority: 6, roles: ['member', 'coach', 'seller', 'admin'], keywordsAny: ['doi mat khau', 'quen mat khau', 'password reset'], minimumScore: 3, staticMessage: 'Hãy dùng luồng tài khoản/đăng nhập hiện có để đổi hoặc khôi phục mật khẩu. Không gửi mật khẩu, token hoặc mã bí mật vào chatbot.', suggestions: [suggestions.account], actions: [action('login-password', 'Mở Đăng nhập', '/login')] },

  { id: 'plans', category: 'MEMBERSHIP', priority: 8, roles: allRoles, exactPhrases: ['gói hội viên', 'xem các gói'], keywordsAny: ['goi hoi vien', 'cac goi', 'plan', 'plans', 'gia goi'], minimumScore: 3, adapterId: 'plans', dynamic: true, suggestions: [suggestions.membership, suggestions.coaches, suggestions.help], actions: [commonActions.plans] },
  { id: 'membership_status', category: 'MEMBERSHIP', priority: 8, roles: memberRoles, keywordsAny: ['goi cua toi', 'membership cua toi', 'hoi vien cua toi', 'dang ky cua toi'], minimumScore: 3, adapterId: 'membership', dynamic: true, suggestions: [suggestions.plans, suggestions.coaches], actions: [action('membership-account', 'Mở gói của tôi', '/membership/account', memberRoles)] },
  { id: 'membership_pending_payment', category: 'MEMBERSHIP', priority: 7, roles: memberRoles, keywordsAny: ['thanh toan dang cho', 'pending payment', 'cho xac nhan thanh toan'], minimumScore: 3, adapterId: 'membership', dynamic: true, suggestions: [suggestions.membership, suggestions.plans], actions: [action('membership-account', 'Mở gói của tôi', '/membership/account', memberRoles)] },
  { id: 'membership_upgrade', category: 'MEMBERSHIP', priority: 7, roles: memberRoles, keywordsAny: ['nang cap goi', 'upgrade goi', 'len goi'], minimumScore: 3, staticMessage: 'Bạn có thể xem lựa chọn nâng cấp trong tài khoản Membership. Chatbot chỉ hướng dẫn và không tự thực hiện giao dịch.', suggestions: [suggestions.plans, suggestions.membership], actions: [action('membership-account', 'Mở Membership', '/membership/account', memberRoles)] },
  { id: 'membership_downgrade', category: 'MEMBERSHIP', priority: 7, roles: memberRoles, keywordsAny: ['ha cap goi', 'downgrade goi'], minimumScore: 3, staticMessage: 'Bạn có thể xem lựa chọn hạ cấp trong tài khoản Membership. Chatbot không tự thay đổi gói.', suggestions: [suggestions.plans, suggestions.membership], actions: [action('membership-account', 'Mở Membership', '/membership/account', memberRoles)] },
  { id: 'membership_cancel', category: 'MEMBERSHIP', priority: 7, roles: memberRoles, keywordsAny: ['huy goi', 'cancel membership', 'huy hoi vien'], minimumScore: 3, staticMessage: 'Bạn có thể kiểm tra luồng hủy trong tài khoản Membership. Chatbot không tự hủy gói hoặc hoàn tiền.', suggestions: [suggestions.membership, suggestions.help], actions: [action('membership-account', 'Mở Membership', '/membership/account', memberRoles)] },
  { id: 'membership_entitlement', category: 'MEMBERSHIP', priority: 8, roles: ['member', 'coach'], keywordsAny: ['dat coach duoc khong', 'quyen dat coach', 'coach entitlement', 'co duoc dat coach'], minimumScore: 3, adapterId: 'membership', dynamic: true, suggestions: [suggestions.plans, suggestions.coaches], actions: [commonActions.plans] },
  { id: 'membership_quota', category: 'MEMBERSHIP', priority: 8, roles: memberRoles, keywordsAny: ['may luot', 'quota', 'con bao nhieu luot', 'luot dat coach'], minimumScore: 3, adapterId: 'membership', dynamic: true, suggestions: [suggestions.coaches, suggestions.membership], actions: [action('membership-account', 'Mở Membership', '/membership/account', memberRoles)] },

  { id: 'coach_find', category: 'COACH', priority: 8, roles: allRoles, exactPhrases: ['tìm coach', 'coach online'], keywordsAny: ['tim coach', 'coach online', 'coach offline', 'coach phu hop', 'huan luyen vien'], minimumScore: 3, adapterId: 'coaches', dynamic: true, suggestions: [suggestions.coachTomorrow, suggestions.plans, suggestions.help], actions: [commonActions.coaches] },
  { id: 'coach_profile', category: 'COACH', priority: 8, roles: allRoles, keywordsAny: ['thong tin coach', 'ho so coach', 'coach ten', 'coach do', 'coach nay'], minimumScore: 3, adapterId: 'coaches', dynamic: true, suggestions: [suggestions.coachTomorrow, suggestions.coaches], actions: [commonActions.coaches] },
  { id: 'coach_availability', category: 'COACH', priority: 9, roles: allRoles, keywordsAny: ['con lich coach', 'lich coach', 'availability coach', 'slot coach', 'con lich ngay', 'con lich'], minimumScore: 3, adapterId: 'coach_availability', dynamic: true, suggestions: [suggestions.appointments, suggestions.coaches], actions: [commonActions.coaches] },
  { id: 'coach_booking', category: 'COACH', priority: 10, roles: allRoles, keywordsAny: ['dat coach', 'dat lich coach', 'booking coach', 'muon dat huan luyen vien'], minimumScore: 3, staticMessage: 'Bạn có thể chọn Coach, ngày và slot cụ thể trong trang đặt lịch. Chatbot không tự đặt lịch; availability chỉ được xác nhận từ API khi bạn nêu rõ Coach và ngày.', suggestions: [suggestions.coaches, suggestions.appointments, suggestions.plans], actions: [commonActions.coaches] },
  { id: 'coach_booking_status', category: 'COACH', priority: 8, roles: memberRoles, keywordsAny: ['lich hen coach', 'booking cua toi', 'lich dat cua toi', 'pending booking', 'booking confirmed'], minimumScore: 3, adapterId: 'bookings', dynamic: true, suggestions: [suggestions.appointments, suggestions.coaches], actions: [commonActions.appointments] },
  { id: 'coach_booking_conflict', category: 'COACH', priority: 8, roles: memberRoles, exactPhrases: ['trùng lịch coach', 'bị trùng lịch'], keywordsAny: ['trung lich coach', 'booking conflict', 'bi trung lich'], minimumScore: 3, staticMessage: 'Nếu slot bị trùng, hãy chọn slot khác trong lịch Coach. Chatbot không tự hủy hoặc đổi lịch.', suggestions: [suggestions.coaches, suggestions.appointments], actions: [commonActions.appointments] },
  { id: 'coach_booking_quota', category: 'COACH', priority: 8, roles: memberRoles, keywordsAny: ['quota dat coach', 'gioi han dat coach'], minimumScore: 3, adapterId: 'membership', dynamic: true, suggestions: [suggestions.membership, suggestions.coaches], actions: [commonActions.plans] },
  { id: 'coach_booking_mode', category: 'COACH', priority: 8, roles: allRoles, keywordsAny: ['online hay truc tiep', 'mode coach', 'tai phong tap', 'session mode'], minimumScore: 3, staticMessage: 'Một slot đặt lịch phải có mode cụ thể Online hoặc Tại phòng tập khi dữ liệu availability yêu cầu. Hãy chọn mode do hệ thống hiển thị.', suggestions: [suggestions.coaches, suggestions.help], actions: [commonActions.coaches] },
  { id: 'coach_workspace', category: 'COACH', priority: 7, roles: coachRoles, keywordsAny: ['khu coach', 'workspace coach', 'hoc vien cua toi', 'chuong trinh cua toi', 'lich workout coach', 'lich hen hoc vien', 'tien do hoc vien'], minimumScore: 3, staticMessage: 'Khu Coach có hồ sơ, học viên, chương trình, assignment, schedule, session và progress theo quyền backend. Chatbot chỉ mở route, không tạo hoặc chỉnh sửa dữ liệu.', suggestions: [suggestions.coachAppointments, suggestions.coachWorkout, suggestions.coachProgress, suggestions.help], actions: [action('coach-home', 'Mở khu Coach', '/coach', coachRoles)] },
  { id: 'member_appointments', category: 'COACH', priority: 8, roles: memberRoles, keywordsAny: ['lich hen cua toi', 'appointment cua toi', 'cuoc hen cua toi'], minimumScore: 3, adapterId: 'bookings', dynamic: true, suggestions: [suggestions.coachTomorrow, suggestions.orders], actions: [commonActions.appointments] },

  { id: 'workout_program', category: 'WORKOUT', priority: 7, roles: memberRoles, keywordsAny: ['chuong trinh tap', 'program tap', 'bai tap cua toi'], minimumScore: 3, adapterId: 'workouts', dynamic: true, suggestions: [suggestions.workouts, suggestions.progress], actions: [commonActions.workouts] },
  { id: 'workout_assignment', category: 'WORKOUT', priority: 7, roles: memberRoles, keywordsAny: ['assignment tap', 'duoc giao bai', 'lich duoc giao'], minimumScore: 3, adapterId: 'workouts', dynamic: true, suggestions: [suggestions.workouts, suggestions.progress], actions: [commonActions.workouts] },
  { id: 'workout_schedule', category: 'WORKOUT', priority: 8, roles: memberRoles, keywordsAny: ['lich tap', 'schedule tap', 'tap hom nay'], minimumScore: 3, adapterId: 'workouts', dynamic: true, suggestions: [suggestions.workouts, suggestions.progress], actions: [commonActions.workouts] },
  { id: 'workout_session', category: 'WORKOUT', priority: 7, roles: memberRoles, keywordsAny: ['bat dau buoi tap', 'start workout', 'set log', 'hoan thanh buoi tap'], minimumScore: 3, staticMessage: 'Bạn có thể mở Workout để bắt đầu, ghi Set hoặc hoàn thành buổi tập. Chatbot không tự ghi log hoặc hoàn thành buổi tập.', suggestions: [suggestions.workouts, suggestions.progress], actions: [commonActions.workouts] },
  { id: 'workout_progress', category: 'WORKOUT', priority: 8, roles: memberRoles, keywordsAny: ['tien do tap', 'progress tap', 'thong ke tap'], minimumScore: 3, adapterId: 'workouts', dynamic: true, suggestions: [suggestions.workouts, suggestions.coaches], actions: [action('progress', 'Mở tiến độ', '/progress', memberRoles)] },
  { id: 'workout_notifications', category: 'WORKOUT', priority: 7, roles: ['member', 'coach', 'seller', 'admin'], keywordsAny: ['thong bao', 'notifications', 'notification'], minimumScore: 3, adapterId: 'notifications', dynamic: true, suggestions: [suggestions.account, suggestions.help], actions: [action('notifications', 'Mở thông báo', '/notifications', ['member', 'coach', 'seller', 'admin'])] },

  { id: 'product_search', category: 'MARKETPLACE', priority: 9, roles: allRoles, exactPhrases: ['tìm whey', 'tìm sản phẩm'], keywordsAny: ['tim san pham', 'cho toi san pham', 'co san pham', 'product'], negativeKeywords: ['gio hang', 'checkout', 'thanh toan'], minimumScore: 3, adapterId: 'products', dynamic: true, suggestions: [suggestions.productCategory, suggestions.cheapProducts, suggestions.coaches], actions: [commonActions.products] },
  { id: 'product_filter', category: 'MARKETPLACE', priority: 10, roles: allRoles, keywordsAny: ['duoi', 'tren', 'tu', 'den', 're nhat', 'dat nhat', 'gia thap nhat', 'gia cao nhat', 'danh muc', 'category', 'cai dau tien', 'cai thu nhat', 'san pham do'], minimumScore: 4, adapterId: 'products', dynamic: true, suggestions: [suggestions.products, suggestions.cheapProducts], actions: [commonActions.products] },
  { id: 'product_detail', category: 'MARKETPLACE', priority: 8, roles: allRoles, keywordsAny: ['chi tiet san pham', 'mo san pham', 'xem san pham nay'], minimumScore: 3, adapterId: 'products', dynamic: true, suggestions: [suggestions.products, suggestions.help], actions: [commonActions.products] },
  { id: 'shop_detail', category: 'MARKETPLACE', priority: 8, roles: allRoles, keywordsAny: ['chi tiet shop', 'mo shop', 'cua hang nay', 'shop slug', 'shop do', 'shop nay'], minimumScore: 3, adapterId: 'shop_detail', dynamic: true, suggestions: [suggestions.products, suggestions.help] },
  { id: 'shop_search_unsupported', category: 'MARKETPLACE', priority: 8, roles: allRoles, keywordsAny: ['tim shop', 'tim cua hang', 'shop nao'], minimumScore: 3, staticMessage: 'Public Shop hiện hỗ trợ mở chi tiết theo slug/link. Hệ thống chưa có Shop search tổng quát nên mình không thể tự đoán hoặc bịa danh sách Shop.', suggestions: [suggestions.products, suggestions.services, suggestions.help], actions: [commonActions.products] },
  { id: 'cart', category: 'MARKETPLACE', priority: 8, roles: buyerRoles, keywordsAny: ['gio hang', 'cart', 'them vao gio'], minimumScore: 3, staticMessage: 'Bạn có thể mở giỏ hàng để tự xem hoặc chỉnh sản phẩm. Chatbot không tự thêm, xóa hoặc đổi số lượng.', suggestions: [suggestions.products, suggestions.orders], actions: [commonActions.cart] },
  { id: 'checkout', category: 'MARKETPLACE', priority: 9, roles: buyerRoles, keywordsAny: ['checkout', 'thanh toan don', 'dat hang'], negativeKeywords: ['huy', 'refund'], minimumScore: 3, staticMessage: 'Bạn có thể mở Checkout để tự thực hiện giao dịch. Chatbot không checkout hoặc thanh toán thay bạn.', suggestions: [suggestions.products, suggestions.orders], actions: [commonActions.checkout] },
  { id: 'order_status', category: 'MARKETPLACE', priority: 8, roles: buyerRoles, keywordsAny: ['don hang cua toi', 'trang thai don', 'don hang'], minimumScore: 3, adapterId: 'orders', dynamic: true, suggestions: [suggestions.orders, suggestions.help], actions: [commonActions.orders] },
  { id: 'order_tracking', category: 'MARKETPLACE', priority: 8, roles: buyerRoles, keywordsAny: ['theo doi don', 'tracking don', 'giao hang'], minimumScore: 3, adapterId: 'orders', dynamic: true, suggestions: [suggestions.orders, suggestions.help], actions: [commonActions.orders] },
  { id: 'order_cancel', category: 'MARKETPLACE', priority: 10, roles: buyerRoles, keywordsAny: ['huy don', 'cancel don'], minimumScore: 3, staticMessage: 'Bạn có thể xem chính sách và route đơn hàng để tự kiểm tra khả năng hủy. Chatbot không tự hủy đơn.', suggestions: [suggestions.orders, suggestions.help], actions: [commonActions.orders] },
  { id: 'order_complaint', category: 'MARKETPLACE', priority: 8, roles: buyerRoles, keywordsAny: ['khieu nai don', 'complaint don', 'bao loi don'], minimumScore: 3, staticMessage: 'Bạn có thể mở khiếu nại để tự gửi thông tin theo quy trình hiện có. Chatbot không tự tạo khiếu nại.', suggestions: [suggestions.orders, suggestions.help], actions: [action('complaints', 'Mở Khiếu nại', '/complaints', buyerRoles)] },
  { id: 'order_refund', category: 'MARKETPLACE', priority: 9, roles: buyerRoles, keywordsAny: ['refund', 'hoan tien', 'tra tien'], minimumScore: 3, staticMessage: 'Chatbot chỉ giải thích và đưa bạn đến khu đơn hàng/khiếu nại. Quyết định refund thuộc quy trình/backend hiện có; chatbot không tự refund.', suggestions: [suggestions.orders, suggestions.help], actions: [commonActions.orders] },
  { id: 'order_replacement', category: 'MARKETPLACE', priority: 8, roles: buyerRoles, keywordsAny: ['doi hang', 'replacement', 'thay san pham'], minimumScore: 3, staticMessage: 'Bạn có thể mở đơn hàng hoặc khiếu nại để xem quy trình đổi hàng. Chatbot không tự tạo yêu cầu.', suggestions: [suggestions.orders, suggestions.help], actions: [commonActions.orders] },
  { id: 'review', category: 'MARKETPLACE', priority: 7, roles: buyerRoles, keywordsAny: ['danh gia', 'review san pham'], minimumScore: 3, staticMessage: 'Bạn có thể mở Reviews để xem và thực hiện thao tác theo quyền. Chatbot không tự gửi review.', suggestions: [suggestions.orders, suggestions.help], actions: [action('reviews', 'Mở Reviews', '/reviews', buyerRoles)] },
  { id: 'complaint', category: 'MARKETPLACE', priority: 7, roles: buyerRoles, keywordsAny: ['khieu nai', 'complaint'], minimumScore: 3, staticMessage: 'Bạn có thể mở khu Khiếu nại để tự kiểm tra hoặc gửi yêu cầu. Chatbot chỉ hướng dẫn.', suggestions: [suggestions.orders, suggestions.help], actions: [action('complaints', 'Mở Khiếu nại', '/complaints', buyerRoles)] },

  { id: 'seller_apply', category: 'SELLER', priority: 8, roles: ['member', 'seller'], keywordsAny: ['dang ky seller', 'apply seller', 'lam seller'], minimumScore: 3, staticMessage: 'Member có thể mở luồng đăng ký Seller nếu backend cho phép. Seller hiện tại chỉ nên xem trạng thái/workspace; chatbot không tự submit hồ sơ.', suggestions: [suggestions.sellerWorkspace, suggestions.products], actions: [commonActions.sellerApply] },
  { id: 'seller_status', category: 'SELLER', priority: 8, roles: ['member', 'seller'], keywordsAny: ['trang thai seller', 'ho so seller', 'application seller'], minimumScore: 3, staticMessage: 'Bạn có thể mở route Seller Apply để xem trạng thái theo quyền backend. Chatbot không tự thay đổi hồ sơ.', suggestions: [suggestions.sellerWorkspace, suggestions.account], actions: [commonActions.sellerApply] },
  { id: 'seller_shop', category: 'SELLER', priority: 7, roles: sellerRoles, keywordsAny: ['shop cua toi', 'seller shop', 'quan ly shop'], minimumScore: 3, staticMessage: 'Seller có thể mở workspace Shop của mình. Chatbot không cập nhật Shop.', suggestions: [suggestions.sellerWorkspace], actions: [action('seller-shop', 'Mở Shop Seller', '/seller/shop', sellerRoles)] },
  { id: 'seller_products', category: 'SELLER', priority: 7, roles: sellerRoles, keywordsAny: ['san pham cua toi', 'seller products', 'quan ly san pham'], minimumScore: 3, staticMessage: 'Seller có thể mở danh sách sản phẩm của mình. Chatbot không tạo hoặc sửa sản phẩm.', suggestions: [suggestions.sellerWorkspace, suggestions.help], actions: [action('seller-products', 'Mở sản phẩm Seller', '/seller/products', sellerRoles)] },
  { id: 'seller_orders', category: 'SELLER', priority: 7, roles: sellerRoles, keywordsAny: ['don seller', 'seller orders', 'don cua seller'], minimumScore: 3, staticMessage: 'Seller có thể mở đơn Seller theo quyền backend. Chatbot không cập nhật trạng thái đơn.', suggestions: [suggestions.sellerWorkspace, suggestions.help], actions: [action('seller-orders', 'Mở đơn Seller', '/seller/orders', sellerRoles)] },
  { id: 'seller_revenue', category: 'SELLER', priority: 7, roles: sellerRoles, keywordsAny: ['doanh thu seller', 'revenue seller', 'doanh thu'], minimumScore: 3, staticMessage: 'Seller có thể mở báo cáo doanh thu theo quyền backend. Chatbot không quyết toán hoặc chỉnh số liệu.', suggestions: [suggestions.sellerWorkspace, suggestions.help], actions: [action('seller-revenue', 'Mở doanh thu', '/seller/revenue', sellerRoles)] },
  { id: 'seller_complaints', category: 'SELLER', priority: 7, roles: sellerRoles, keywordsAny: ['khieu nai seller', 'seller complaints'], minimumScore: 3, staticMessage: 'Seller có thể mở khu Khiếu nại của mình theo quyền backend. Chatbot chỉ hướng dẫn.', suggestions: [suggestions.sellerWorkspace, suggestions.help], actions: [action('seller-complaints', 'Mở khiếu nại Seller', '/seller/complaints', sellerRoles)] },

  { id: 'admin_dashboard', category: 'ADMIN', priority: 7, roles: adminRoles, keywordsAny: ['admin dashboard', 'khu admin', 'quan tri'], minimumScore: 3, staticMessage: 'Admin có thể mở Dashboard quản trị theo quyền backend. Chatbot không tự thao tác quản trị.', suggestions: [suggestions.adminWorkspace, suggestions.help], actions: [commonActions.admin] },
  { id: 'admin_coach', category: 'ADMIN', priority: 7, roles: adminRoles, keywordsAny: ['quan ly coach', 'admin coach'], minimumScore: 3, staticMessage: 'Admin có thể mở quản lý Coach theo quyền backend. Chatbot chỉ điều hướng.', suggestions: [suggestions.adminWorkspace], actions: [action('admin-coach', 'Quản lý Coach', '/admin/coaches', adminRoles)] },
  { id: 'admin_exercises', category: 'ADMIN', priority: 7, roles: adminRoles, keywordsAny: ['exercise library admin', 'thu vien bai tap', 'admin exercise'], minimumScore: 3, staticMessage: 'Admin có thể mở Exercise Library theo quyền backend.', suggestions: [suggestions.adminWorkspace], actions: [action('admin-exercises', 'Exercise Library', '/admin/exercises', adminRoles)] },
  { id: 'admin_moderation', category: 'ADMIN', priority: 7, roles: adminRoles, keywordsAny: ['duyet san pham', 'moderation', 'kiem duyet'], minimumScore: 3, staticMessage: 'Admin có thể mở Product Moderation theo quyền backend. Chatbot không tự duyệt sản phẩm.', suggestions: [suggestions.adminWorkspace], actions: [action('admin-moderation', 'Product Moderation', '/admin/product-moderation', adminRoles)] },
  { id: 'admin_seller_applications', category: 'ADMIN', priority: 7, roles: adminRoles, keywordsAny: ['seller applications admin', 'duyet seller', 'ho so seller admin'], minimumScore: 3, staticMessage: 'Admin có thể mở Seller Applications theo quyền backend. Chatbot không tự approve/reject.', suggestions: [suggestions.adminWorkspace], actions: [action('admin-seller-applications', 'Seller Applications', '/admin/seller-applications', adminRoles)] },
  { id: 'admin_orders', category: 'ADMIN', priority: 7, roles: adminRoles, keywordsAny: ['admin orders', 'don hang admin'], minimumScore: 3, staticMessage: 'Admin có thể xem tổng quan đơn hàng theo UI/API hiện có. Chatbot không thay đổi trạng thái.', suggestions: [suggestions.adminWorkspace], actions: [action('admin-orders', 'Admin Orders', '/admin/orders', adminRoles)] },
  { id: 'admin_refunds', category: 'ADMIN', priority: 7, roles: adminRoles, keywordsAny: ['admin refund', 'refund admin'], minimumScore: 3, staticMessage: 'Admin có thể mở khu Refund theo quyền backend. Chatbot không tự quyết định hoặc thực hiện refund.', suggestions: [suggestions.adminWorkspace], actions: [action('admin-refunds', 'Admin Refunds', '/admin/refunds', adminRoles)] },
  { id: 'admin_settlements', category: 'ADMIN', priority: 7, roles: adminRoles, keywordsAny: ['settlement admin', 'doi soat admin'], minimumScore: 3, staticMessage: 'Admin có thể xem Settlement overview theo UI/API hiện có. Chatbot không quyết toán.', suggestions: [suggestions.adminWorkspace], actions: [action('admin-settlements', 'Admin Settlements', '/admin/settlements', adminRoles)] },

  { id: 'safety_secret', category: 'SAFETY', priority: 100, roles: allRoles, keywordsAny: ['mat khau', 'password', 'token', 'api key', 'secret', 'jwt', 'credential'], minimumScore: 2, safety: true, staticMessage: 'Mình không thể cung cấp, đọc hoặc lưu mật khẩu, token, API key hay thông tin bí mật. Hãy dùng luồng xác thực chính thức của hệ thống.', suggestions: [suggestions.account, suggestions.help] },
  { id: 'safety_idor', category: 'SAFETY', priority: 100, roles: allRoles, keywordsAny: ['user id', 'userid', 'id cua nguoi khac', 'bypass role', 'truy cap nguoi khac', 'idor'], minimumScore: 2, safety: true, staticMessage: 'Mình không thể giúp bypass role hoặc truy cập dữ liệu người khác. Backend authorization luôn là nguồn quyết định quyền truy cập.', suggestions: [suggestions.account, suggestions.help] },
  { id: 'safety_medical', category: 'SAFETY', priority: 100, roles: allRoles, keywordsAny: ['dau bung', 'dau dau', 'dau lung', 'dau khop', 'dau co', 'chan thuong', 'benh', 'thuoc', 'y te', 'medical', 'injury'], minimumScore: 2, safety: true, staticMessage: 'Mình chỉ là trợ lý hướng dẫn nền tảng, không chẩn đoán hoặc đưa chỉ định y tế. Với đau/chấn thương/bệnh, hãy trao đổi Coach hoặc chuyên gia phù hợp.', suggestions: [suggestions.coaches, suggestions.help] },
  { id: 'mutation_block', category: 'SAFETY', priority: 100, roles: allRoles, keywordsAny: ['huy don giup', 'checkout giup', 'dat coach giup', 'refund giup', 'doi du lieu', 'update du lieu', 'xoa don'], minimumScore: 2, safety: true, staticMessage: 'Chatbot không tự checkout, đặt Coach, hủy, refund, update hoặc thao tác Admin. Mình có thể hướng dẫn route và tra cứu READ-ONLY khi API hiện hữu cho phép.', suggestions: [suggestions.products, suggestions.coaches, suggestions.help] },
  { id: 'unsupported', category: 'SAFETY', priority: 90, roles: allRoles, keywordsAny: ['bitcoin', 'chung khoan', 'thoi tiet', 'dat ve', 'y te'], minimumScore: 2, safety: true, staticMessage: 'Chức năng này không thuộc phạm vi GYMFIT hiện tại. Mình có thể hỗ trợ các nhóm Sản phẩm, Coach, Membership, Workout, đơn hàng, Seller, Admin và tài khoản.', suggestions: [suggestions.products, suggestions.coaches, suggestions.help] },
];

export const chatbotCatalog: readonly ChatbotIntent[] = intents;
