import { useCallback, useEffect, useState } from 'react';
import { Calendar, ClipboardList, Dumbbell, Users, UserCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { format } from 'date-fns';
import { DashboardPageHeader, DashboardPanel, EmptyState, MetricCard, PanelError, QuickAction, QuickStartCard } from '../../components/dashboard/DashboardPrimitives';
import { getCoachDashboard } from '../../services/coachWorkspaceApi';
import { getBookingSummary, getCoachAppointmentsPage, type Booking, type BookingSummary } from '../../services/bookings';
import type { CoachDashboardData } from '../../types/coachWorkspace';
import { displayCoachDate, displayCoachTime, todayInCoachTimeZone } from '../../utils/coachBooking';

const messageFor = (reason: unknown) => { const value = reason as { response?: { data?: { message?: string } }; message?: string }; return value.response?.data?.message || value.message || 'Không thể tải dữ liệu trong phạm vi Coach.'; };

export default function CoachDashboard() {
  const [dashboard, setDashboard] = useState<CoachDashboardData | null>(null);
  const [todayAppointments, setTodayAppointments] = useState<Booking[]>([]);
  const [pendingAppointments, setPendingAppointments] = useState<Booking[]>([]);
  const [bookingSummary, setBookingSummary] = useState<BookingSummary | null>(null);
  const [workspaceLoading, setWorkspaceLoading] = useState(true); const [appointmentsLoading, setAppointmentsLoading] = useState(true);
  const [workspaceError, setWorkspaceError] = useState(''); const [appointmentsError, setAppointmentsError] = useState('');
  const loadWorkspace = useCallback(async () => { setWorkspaceLoading(true); setWorkspaceError(''); try { setDashboard(await getCoachDashboard()); } catch (reason: unknown) { setWorkspaceError(messageFor(reason)); } finally { setWorkspaceLoading(false); } }, []);
  const loadAppointments = useCallback(async () => { setAppointmentsLoading(true); setAppointmentsError(''); try { const today = todayInCoachTimeZone(); const [summary, todayPage, pendingPage] = await Promise.all([getBookingSummary(), getCoachAppointmentsPage({ status: ['pending', 'confirmed'], fromDate: today, toDate: today, page: 1, limit: 20 }), getCoachAppointmentsPage({ status: 'pending', page: 1, limit: 4 })]); setBookingSummary(summary); setTodayAppointments(todayPage.items); setPendingAppointments(pendingPage.items); } catch (reason: unknown) { setAppointmentsError(messageFor(reason)); } finally { setAppointmentsLoading(false); } }, []);
  useEffect(() => { void loadWorkspace(); }, [loadWorkspace]); useEffect(() => { void loadAppointments(); }, [loadAppointments]);
  const today = todayInCoachTimeZone(); const appointmentErrorPanel = appointmentsError ? <PanelError message={appointmentsError} onRetry={() => void loadAppointments()} /> : null;
  return <div className="dashboard-page"><DashboardPageHeader eyebrow="KHÔNG GIAN COACH" title="Tổng quan Coach" description="Theo dõi lịch hẹn và workout bằng các truy vấn server-side tách biệt." action={<Link className="primary-button" to="/coach/appointments">Mở lịch hẹn</Link>} />
    <div className="metric-grid"><MetricCard title="Yêu cầu chờ xác nhận" value={appointmentsLoading ? '—' : bookingSummary?.pending ?? '—'} detail="Booking pending" icon={<Calendar size={18} />} tone="amber" loading={appointmentsLoading} /><MetricCard title="Lịch đã xác nhận" value={appointmentsLoading ? '—' : bookingSummary?.upcoming ?? '—'} detail="Sắp tới" icon={<Calendar size={18} />} tone="blue" loading={appointmentsLoading} /><MetricCard title="Lịch hôm nay" value={appointmentsLoading ? '—' : bookingSummary?.today ?? '—'} detail={today} icon={<UserCircle size={18} />} tone="lime" loading={appointmentsLoading} /><MetricCard title="Chương trình của tôi" value={workspaceLoading ? '—' : dashboard?.counts.ownedPrograms ?? '—'} detail="Workout riêng Coach" icon={<Dumbbell size={18} />} tone="slate" loading={workspaceLoading} /></div>
    <QuickStartCard title="Thiết lập công việc Coach" description="Hoàn thiện nền tảng trước khi xử lý học viên và lịch tập." steps={[{ to: '/coach/profile', title: 'Hoàn thiện hồ sơ', description: 'Cập nhật thông tin Coach hiển thị công khai.' }, { to: '/coach/appointments', title: 'Kiểm tra lịch hẹn', description: 'Xử lý các yêu cầu booking đang chờ.' }, { to: '/coach/workout-programs', title: 'Tạo chương trình', description: 'Quản lý các chương trình do bạn sở hữu.' }, { to: '/coach/members', title: 'Gán học viên', description: 'Mở danh sách học viên thuộc phạm vi.' }]} />
    <div className="dashboard-grid-main"><DashboardPanel title="Lịch hẹn hôm nay" description="Booking Coach, không phải lịch workout">{appointmentErrorPanel || appointmentsLoading ? appointmentErrorPanel || <div className="panel-state">Đang tải lịch hẹn...</div> : todayAppointments.length === 0 ? <EmptyState title="Không có lịch hẹn hôm nay" description="Các yêu cầu mới sẽ xuất hiện ở Lịch hẹn học viên." action={<Link className="secondary-button" to="/coach/appointments">Mở lịch hẹn</Link>} /> : <div className="space-y-3">{todayAppointments.map(item => <Link key={item.id} to={`/coach/appointments/${item.id}`} className="quick-action"><span className="quick-icon"><Calendar size={18} /></span><span><strong>{item.member_name || `Member #${item.member_id}`}</strong><small>{displayCoachTime(item.start_time)} · {item.status === 'pending' ? 'Chờ xác nhận' : 'Đã xác nhận'}</small></span></Link>)}</div>}</DashboardPanel><DashboardPanel title="Yêu cầu mới" description={`${bookingSummary?.pending ?? 0} booking đang chờ xử lý`}>{appointmentErrorPanel || appointmentsLoading ? appointmentErrorPanel || <div className="panel-state">Đang tải lịch hẹn...</div> : <div className="space-y-3">{pendingAppointments.map(item => <Link key={item.id} to={`/coach/appointments/${item.id}`} className="quick-action"><span className="quick-icon"><Calendar size={18} /></span><span><strong>{item.member_name || `Member #${item.member_id}`}</strong><small>{displayCoachDate(item.booking_date)} · {displayCoachTime(item.start_time)}</small></span></Link>)}{pendingAppointments.length === 0 && <div className="panel-state">Không có yêu cầu mới.</div>}<Link to="/coach/appointments" className="text-sm text-[#60a5fa]">Xem tất cả lịch hẹn</Link></div>}</DashboardPanel></div>
    {workspaceError && <DashboardPanel title="Không tải được workspace workout" description="Lịch hẹn vẫn hoạt động độc lập"><PanelError message={workspaceError} onRetry={() => void loadWorkspace()} /></DashboardPanel>}
    {!workspaceError && <div className="dashboard-grid-main"><DashboardPanel title="Lịch workout sắp tới" description="Workout Schedule của học viên thuộc scope">{workspaceLoading ? <div className="panel-state">Đang tải workout...</div> : dashboard?.upcomingSchedules.length === 0 ? <EmptyState title="Chưa có lịch workout sắp tới" description="Tạo assignment và generate schedule khi đã có Program active." action={<Link className="secondary-button" to="/coach/schedules">Mở lịch workout</Link>} /> : <div className="space-y-3">{dashboard?.upcomingSchedules.map(schedule => <Link key={schedule.id} to={`/coach/members/${schedule.member_id}/schedule`} className="quick-action"><span className="quick-icon"><Calendar size={18} /></span><span><strong>{schedule.member_name} · {schedule.day_title}</strong><small>{schedule.scheduled_date} · {schedule.program_name}</small></span></Link>)}</div>}</DashboardPanel><DashboardPanel title="Session gần đây" description="Workout session read-only">{workspaceLoading ? <div className="panel-state">Đang tải session...</div> : dashboard?.recentSessions.length === 0 ? <EmptyState title="Chưa có session" description="Session sẽ xuất hiện khi có dữ liệu thật." /> : <div className="space-y-3">{dashboard?.recentSessions.map(session => <Link key={`${session.source}-${session.id}`} to={`/coach/members/${session.member_id}/sessions/${session.source}/${session.id}`} className="quick-action"><span className="quick-icon"><Dumbbell size={18} /></span><span><strong>{session.member_name?.trim() || `Hội viên #${session.member_id}`} · {session.workout_name}</strong><small>{format(new Date(session.started_at), 'dd/MM/yyyy HH:mm')} · {session.status} · {session.source}</small></span></Link>)}</div>}</DashboardPanel></div>}
    {!workspaceError && <DashboardPanel title="Cần xử lý" description="Queue bounded theo dữ liệu Coach, không phải chẩn đoán sức khỏe">{workspaceLoading ? <div className="panel-state">Đang tải queue...</div> : dashboard?.attentionQueueAvailable === false ? <div className="panel-state">Attention Queue chưa khả dụng.</div> : dashboard?.attentionQueue.length === 0 ? <EmptyState title="Không có việc cần xử lý" description="Các rule hiện tại không phát hiện item cần chú ý." /> : <div className="space-y-3">{dashboard?.attentionQueue.map(item => <Link key={`${item.type}-${item.memberId}-${item.createdFrom}`} to={item.actionUrl} className="quick-action"><span className={`quick-icon ${item.severity === 'HIGH' ? 'text-red-300' : item.severity === 'MEDIUM' ? 'text-amber-300' : 'text-slate-300'}`}><Calendar size={18} /></span><span><strong>{item.title}</strong><small>{item.memberName} · {item.description}</small></span><span className="text-xs uppercase text-slate-500">{item.severity}</span></Link>)}</div>}</DashboardPanel>}
    <DashboardPanel title="Lối tắt" description="Các route Coach chính"><div className="quick-grid"><QuickAction to="/coach/appointments" title="Lịch hẹn học viên" description="Xác nhận và cập nhật booking" icon={<Calendar size={18} />} /><QuickAction to="/coach/workout-programs" title="Chương trình của tôi" description="Quản lý program Coach" icon={<Dumbbell size={18} />} /><QuickAction to="/coach/members" title="Học viên của tôi" description="Member thuộc scope" icon={<Users size={18} />} /><QuickAction to="/coach/schedules" title="Lịch workout" description="Lịch tập tương lai" icon={<ClipboardList size={18} />} /></div></DashboardPanel>
  </div>;
}
