import {useCallback,useEffect,useState} from "react";
import api from "../../api/axios";
type Refund={id:number;orderId:number;shopOrderId:number;orderNumber:string;merchandiseAmount:number;shippingAmount:number;totalAmount:number;currency:string;status:"PENDING"|"COMPLETED"|"FAILED";reason:string;externalReference:string|null;createdAt:string};
export default function AdminRefundsPage(){
  const [rows,setRows]=useState<Refund[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{setRows((await api.get<{data:Refund[]}>("/admin/refunds")).data.data);}catch{setError("Không thể tải danh sách refund.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const update=async(refund:Refund,status:"PENDING"|"COMPLETED"|"FAILED")=>{const reason=window.prompt(status==="PENDING"?"Lý do retry refund":"Lý do/xác nhận xử lý refund");if(!reason?.trim())return;const externalReference=status==="COMPLETED"?window.prompt("Mã tham chiếu hoàn tiền bên ngoài (không bắt buộc)")||undefined:undefined;try{await api.patch(`/admin/refunds/${refund.id}/status`,{status,reason:reason.trim(),externalReference});await load();}catch{setError("Không thể cập nhật refund.");}};
  return <main className="space-y-5 p-4 md:p-8"><div className="flex justify-between"><div><h1 className="text-3xl font-bold">Refunds</h1><p className="text-slate-400">Hoàn tiền thủ công ngoài hệ thống; mọi chuyển trạng thái đều được audit.</p></div><button className="btn-secondary" onClick={()=>void load()}>Làm mới</button></div>{error&&<p role="alert" className="rounded bg-red-500/10 p-3 text-red-300">{error}</p>}{loading?<p>Đang tải…</p>:<div className="overflow-x-auto rounded-xl border border-white/10"><table className="w-full min-w-[1050px]"><thead><tr><th>Refund</th><th>Order / ShopOrder</th><th>Merchandise</th><th>Shipping</th><th>Total</th><th>Status</th><th>Reason</th><th>Action</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t border-white/10"><td className="p-3">#{row.id}</td><td>{row.orderNumber} / #{row.shopOrderId}</td><td>{row.merchandiseAmount.toLocaleString()} {row.currency}</td><td>{row.shippingAmount.toLocaleString()} {row.currency}</td><td>{row.totalAmount.toLocaleString()} {row.currency}</td><td>{row.status}</td><td>{row.reason}</td><td className="space-x-2">{row.status==="PENDING"&&<><button className="text-emerald-400" onClick={()=>void update(row,"COMPLETED")}>Complete</button><button className="text-red-300" onClick={()=>void update(row,"FAILED")}>Fail</button></>}{row.status==="FAILED"&&<button className="text-amber-300" onClick={()=>void update(row,"PENDING")}>Retry</button>}</td></tr>)}</tbody></table></div>}</main>;
}
