import { FormEvent,useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { productModerationApi } from '../../services/productModerationApi';
type Row={id:number;name:string;slug:string;moderationStatus:string;submittedAt:string|null;brand:string|null;category:string|null;shop:{id:number;name:string};};
export default function AdminProductModerationPage(){
  const[items,setItems]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('PENDING_REVIEW'),[shopId,setShopId]=useState(''),[categoryId,setCategoryId]=useState(''),[brandId,setBrandId]=useState(''),[submittedFrom,setSubmittedFrom]=useState(''),[page,setPage]=useState(1),[pages,setPages]=useState(1);
  const load=async()=>{setLoading(true);setError('');try{const r=await productModerationApi.list({page,limit:20,status,search:search||undefined,shopId:shopId||undefined,categoryId:categoryId||undefined,brandId:brandId||undefined,submittedFrom:submittedFrom||undefined});setItems(r.data.data);setPages(r.data.pagination.pages||1);}catch(cause:any){setError(cause.response?.data?.message||'Không thể tải moderation inbox');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[page,status]);
  const submit=(event:FormEvent)=>{event.preventDefault();if(page===1)void load();else setPage(1);};
  return <section className="space-y-5 p-6"><h1 className="text-3xl font-bold">Duyệt sản phẩm</h1>
    <form className="grid gap-2 md:grid-cols-6" onSubmit={submit}><input placeholder="Tên, slug hoặc SKU" value={search} onChange={e=>setSearch(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}>{['PENDING_REVIEW','PUBLISHED','REJECTED','SUSPENDED','DRAFT'].map(x=><option key={x}>{x}</option>)}</select><input placeholder="Shop ID" type="number" value={shopId} onChange={e=>setShopId(e.target.value)}/><input placeholder="Category ID" type="number" value={categoryId} onChange={e=>setCategoryId(e.target.value)}/><input placeholder="Brand ID" type="number" value={brandId} onChange={e=>setBrandId(e.target.value)}/><input type="date" value={submittedFrom} onChange={e=>setSubmittedFrom(e.target.value)}/><button type="submit">Lọc</button></form>
    {error&&<p className="text-red-400">{error}</p>}{loading?<p>Đang tải…</p>:items.length===0?<p>Không có Product phù hợp.</p>:<div className="overflow-x-auto"><table className="w-full text-left"><thead><tr><th>Product</th><th>Shop</th><th>Brand / Category</th><th>Submitted</th><th>Status</th></tr></thead><tbody>{items.map(item=><tr className="border-t border-slate-800" key={item.id}><td className="py-3"><Link className="text-emerald-400" to={`/admin/product-moderation/${item.id}`}>{item.name}</Link><small className="block">{item.slug}</small></td><td>{item.shop.name}</td><td>{item.brand||'—'} / {item.category||'—'}</td><td>{item.submittedAt?new Date(item.submittedAt).toLocaleString('vi-VN'):'—'}</td><td>{item.moderationStatus}</td></tr>)}</tbody></table></div>}
    <div className="flex gap-3"><button disabled={page<=1} onClick={()=>setPage(x=>x-1)}>Trước</button><span>{page}/{pages}</span><button disabled={page>=pages} onClick={()=>setPage(x=>x+1)}>Sau</button></div>
  </section>;
}
