import { useCallback, useEffect, useState } from 'react';
import { AxiosError } from 'axios';
import { Link } from 'react-router-dom';
import { sellerApplicationsApi } from '../../services/sellerApplicationsApi';
import type { SellerApplication, SellerApplicationStatus } from '../../types/sellerApplications';

const statuses: SellerApplicationStatus[]=['PENDING','DRAFT','REJECTED','WITHDRAWN','APPROVED'];
const errorMessage=(error:unknown)=>error instanceof AxiosError&&typeof error.response?.data?.message==='string'?error.response.data.message:'Không thể tải Seller Applications.';
export default function AdminSellerApplicationsPage(){
  const [rows,setRows]=useState<SellerApplication[]>([]),[status,setStatus]=useState<SellerApplicationStatus>('PENDING'),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await sellerApplicationsApi.adminList({status,search:query||undefined,page,limit:20,sortOrder:'desc'});setRows(response.data.data.items);setPages(Math.max(1,response.data.data.totalPages));setTotal(response.data.data.total);}catch(requestError){setError(errorMessage(requestError));}finally{setLoading(false)}},[page,query,status]);
  useEffect(()=>{void load()},[load]);
  return <section className="space-y-5 p-4 md:p-8"><header><p className="text-sm font-semibold uppercase tracking-widest text-emerald-400">Marketplace operations</p><h1 className="text-3xl font-bold">Seller Applications</h1><p className="text-slate-400">Default inbox chỉ hiển thị hồ sơ PENDING.</p></header><div className="flex flex-wrap gap-3"><form onSubmit={event=>{event.preventDefault();setPage(1);setQuery(search.trim())}} className="flex min-w-[280px] flex-1 gap-2"><input className="input-field w-full" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Business, contact hoặc email"/><button className="btn-secondary">Tìm</button></form><select className="input-field" value={status} onChange={event=>{setStatus(event.target.value as SellerApplicationStatus);setPage(1)}}>{statuses.map(value=><option key={value}>{value}</option>)}</select></div>{error?<p role="alert" className="rounded-xl bg-red-500/10 p-4 text-red-300">{error}</p>:loading?<p className="p-10 text-center text-slate-400">Đang tải…</p>:rows.length===0?<p className="rounded-xl border border-slate-800 p-10 text-center text-slate-400">Không có hồ sơ {status}.</p>:<div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full min-w-[900px] text-sm"><thead><tr><th className="p-3 text-left">Doanh nghiệp</th><th>Người liên hệ</th><th>Email</th><th>Trạng thái</th><th>Ngày gửi</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t border-slate-800"><td className="p-3">{row.businessName||'Chưa nhập'}<div className="text-xs text-slate-500">#{row.id} · {row.businessType||'—'}</div></td><td>{row.contactName||'—'}</td><td>{row.contactEmail||'—'}</td><td>{row.status}</td><td>{row.submittedAt?new Date(row.submittedAt).toLocaleString('vi-VN'):'—'}</td><td><Link className="text-emerald-400" to={`/admin/seller-applications/${row.id}`}>Xem chi tiết</Link></td></tr>)}</tbody></table></div>}<div className="flex items-center justify-between"><span>{total} hồ sơ · Trang {page}/{pages}</span><div className="flex gap-2"><button className="btn-secondary" disabled={page<=1||loading} onClick={()=>setPage(value=>value-1)}>Trước</button><button className="btn-secondary" disabled={page>=pages||loading} onClick={()=>setPage(value=>value+1)}>Sau</button></div></div></section>;
}

