import { useEffect, useState } from 'react';
import { Search, UserCheck, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { DashboardPageHeader, EmptyState, MetricCard, PanelError } from '../../../components/dashboard/DashboardPrimitives';
import { inputClass } from '../../../pages/coaches/CoachCommon';
import { listAdminCoaches, getAdminCoachSummary } from '../../../services/adminCoachApi';
import type { AdminCoach, AdminCoachStatus, AdminCoachSummary } from '../../../types/adminCoach';

const statusLabel: Record<AdminCoachStatus, string> = { ACTIVE: 'Active', SUSPENDED: 'Suspended', INACTIVE: 'Inactive' };
const statusClass: Record<AdminCoachStatus, string> = { ACTIVE: 'text-emerald-300', SUSPENDED: 'text-amber-300', INACTIVE: 'text-slate-400' };
const errorMessage = (error: unknown) => { const value = error as { response?: { data?: { message?: string } }; message?: string }; return value.response?.data?.message || value.message || 'Không thể tải dữ liệu Admin Coach.'; };

export default function AdminCoachManagementPage() {
  const [result, setResult] = useState<{ items: AdminCoach[]; page: number; total: number; totalPages: number } | null>(null);
  const [summary, setSummary] = useState<AdminCoachSummary | null>(null); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const [rows, overview] = await Promise.all([listAdminCoaches({ search: search || undefined, status: status || undefined, page, limit: 20 }), getAdminCoachSummary()]); setResult(rows); setSummary(overview); } catch (reason) { setError(errorMessage(reason)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [search, status, page]);
  return <div className="dashboard-page">
    <DashboardPageHeader eyebrow="ADMIN COACH MANAGEMENT" title="Quản lý Coach" description="Quản trị trạng thái và phạm vi Coach–Member từ một khu vực riêng." action={<Link className="secondary-button" to="/admin/workouts">Mở Workout Governance</Link>} />
    {summary && <div className="metric-grid"><MetricCard title="Tổng Coach" value={summary.totalCoaches} icon={<Users size={18}/>} tone="blue"/><MetricCard title="Đang hoạt động" value={summary.activeCoaches} icon={<UserCheck size={18}/>} tone="lime"/><MetricCard title="Bị suspend" value={summary.suspendedCoaches} icon={<UserCheck size={18}/>} tone="amber"/><MetricCard title="Member chưa có Coach" value={summary.unassignedMembers} icon={<Users size={18}/>} tone="slate"/><MetricCard title="Assignment sắp hết hạn" value={summary.expiringAssignments} icon={<UserCheck size={18}/>} tone="amber"/><MetricCard title="Session tuần này" value={summary.completedSessionsThisWeek} icon={<UserCheck size={18}/>} tone="blue"/></div>}
    <div className="dashboard-panel mb-6"><div className="flex flex-col gap-3 md:flex-row md:items-end"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={17}/><input className={`${inputClass} pl-10`} value={search} onChange={event => { setPage(1); setSearch(event.target.value); }} placeholder="Tìm theo tên hoặc email" aria-label="Tìm Coach"/></div><label className="text-sm text-slate-400">Trạng thái<select className={`${inputClass} mt-1 md:w-48`} value={status} onChange={event => { setPage(1); setStatus(event.target.value); }}><option value="">Tất cả</option><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option><option value="INACTIVE">Inactive</option></select></label></div></div>
    {error ? <PanelError message={error} onRetry={() => void load()}/> : loading ? <div className="panel-state">Đang tải danh sách Coach…</div> : !result?.items.length ? <div className="dashboard-panel"><EmptyState title="Không có Coach phù hợp" description="Thử thay đổi từ khóa hoặc bộ lọc trạng thái." /></div> : <>
      <div className="hidden overflow-x-auto rounded-2xl border border-slate-800 bg-slate-950/30 md:block"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b border-slate-800 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Coach</th><th className="px-5 py-4">Trạng thái</th><th className="px-5 py-4">Member</th><th className="px-5 py-4">Program</th><th className="px-5 py-4">Session gần đây</th><th className="px-5 py-4"/></tr></thead><tbody>{result.items.map(coach => <tr key={coach.id} className="border-b border-slate-900 last:border-0"><td className="px-5 py-4"><strong className="text-white">{coach.name}</strong><p className="text-xs text-slate-500">{coach.email}</p></td><td className={`px-5 py-4 font-medium ${statusClass[coach.status]}`}>{statusLabel[coach.status]}</td><td className="px-5 py-4 text-slate-300">{coach.member_count}</td><td className="px-5 py-4 text-slate-300">{coach.program_count}</td><td className="px-5 py-4 text-slate-300">{coach.recent_session_count}</td><td className="px-5 py-4 text-right"><Link className="secondary-button" to={`/admin/coaches/${coach.id}`}>Chi tiết</Link></td></tr>)}</tbody></table></div>
      <div className="grid gap-3 md:hidden">{result.items.map(coach => <Link key={coach.id} to={`/admin/coaches/${coach.id}`} className="dashboard-panel block"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-white">{coach.name}</h2><p className="text-sm text-slate-500">{coach.email}</p></div><span className={statusClass[coach.status]}>{statusLabel[coach.status]}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs text-slate-400"><span>Member <strong className="block text-white">{coach.member_count}</strong></span><span>Program <strong className="block text-white">{coach.program_count}</strong></span><span>Session <strong className="block text-white">{coach.recent_session_count}</strong></span></div></Link>)}</div>
      <div className="mt-5 flex items-center justify-between text-sm text-slate-400"><span>{result.total} Coach</span><div className="flex gap-2"><button className="secondary-button" disabled={page <= 1} onClick={() => setPage(value => value - 1)}>Trước</button><span className="px-2 py-2">{page}/{result.totalPages || 1}</span><button className="secondary-button" disabled={page >= result.totalPages} onClick={() => setPage(value => value + 1)}>Sau</button></div></div>
    </>}
  </div>;
}
