import type {Transaction} from "mssql";
import {getPool,sql} from "../../config/database";
import {AppError} from "../../middleware/errorHandler";
import {mailService} from "../mail/mail.service";

export type ComplaintStatus="OPEN"|"UNDER_REVIEW"|"REPLACEMENT_REQUIRED"|"RESOLVED"|"REJECTED";
export type FaultParty="UNDETERMINED"|"SELLER_FAULT"|"BUYER_FAULT"|"GYMFIT_OR_CARRIER";
export type ReplacementStatus="REQUIRED"|"READY_FOR_PICKUP"|"PICKED_UP"|"IN_TRANSIT_TO_HUB"|"RECEIVED_AT_HUB"|"HUB_CHECK_PASSED"|"HUB_CHECK_FAILED"|"SHIPPED"|"DELIVERED"|"FAILED";
type Scope={buyerId?:number;sellerId?:number};

const text=(value:string|undefined,label:string)=>{const result=value?.trim();if(!result)throw new AppError(400,`${label} is required`);return result;};
const activeStatuses="N'OPEN',N'UNDER_REVIEW',N'REPLACEMENT_REQUIRED'";

async function emailUsersBestEffort(userIds:number[],subject:string,message:string,includeConfiguredAdmin=false){
  try{
    const unique=[...new Set(userIds.filter(Number.isInteger))];
    const request=(await getPool()).request();
    const names=unique.map((id,index)=>{request.input(`mailUser${index}`,sql.Int,id);return `@mailUser${index}`;});
    const recipients=names.length?(await request.query<{email:string}>(`SELECT email FROM dbo.Users WHERE id IN(${names.join(",")}) AND is_active=1`)).recordset.map(row=>row.email):[];
    const configuredAdmin=includeConfiguredAdmin?process.env.ADMIN_NOTIFICATION_EMAIL?.trim():undefined;
    if(configuredAdmin)recipients.push(configuredAdmin);
    await Promise.all([...new Set(recipients)].map(to=>mailService.send({to,subject,text:message})));
  }catch{
    // Email is best-effort and never changes the committed commerce transaction.
  }
}

async function notify(tx:Transaction,input:{recipientId:number;eventKey:string;type:string;title:string;message:string;orderId:number;shopOrderId:number;complaintId:number;replacementId?:number;refundId?:number}){
  await tx.request().input("notifyRecipient",sql.Int,input.recipientId).input("notifyKey",sql.NVarChar(150),input.eventKey).input("notifyType",sql.NVarChar(50),input.type).input("notifyTitle",sql.NVarChar(255),input.title).input("notifyMessage",sql.NVarChar(2000),input.message).input("notifyOrder",sql.Int,input.orderId).input("notifyShopOrder",sql.Int,input.shopOrderId).input("notifyComplaint",sql.BigInt,input.complaintId).input("notifyReplacement",sql.BigInt,input.replacementId||null).input("notifyRefund",sql.BigInt,input.refundId||null).query(
    "IF NOT EXISTS(SELECT 1 FROM dbo.MarketplaceNotifications WITH(UPDLOCK,HOLDLOCK) WHERE event_key=@notifyKey) INSERT dbo.MarketplaceNotifications(buyer_id,event_key,notification_type,title,message,order_id,shop_order_id,refund_id,complaint_id,replacement_id,created_at) VALUES(@notifyRecipient,@notifyKey,@notifyType,@notifyTitle,@notifyMessage,@notifyOrder,@notifyShopOrder,@notifyRefund,@notifyComplaint,@notifyReplacement,SYSUTCDATETIME())",
  );
}
async function notifyAdmins(tx:Transaction,complaintId:number,orderId:number,shopOrderId:number,message:string){
  await tx.request().input("adminComplaint",sql.BigInt,complaintId).input("adminOrder",sql.Int,orderId).input("adminShopOrder",sql.Int,shopOrderId).input("adminMessage",sql.NVarChar(2000),message).query(
    "INSERT dbo.MarketplaceNotifications(buyer_id,event_key,notification_type,title,message,order_id,shop_order_id,complaint_id,created_at) SELECT u.id,CONCAT(N'COMPLAINT_CREATED:',@adminComplaint,N':ADMIN:',u.id),N'COMPLAINT_CREATED',N'Khiếu nại marketplace mới',@adminMessage,@adminOrder,@adminShopOrder,@adminComplaint,SYSUTCDATETIME() FROM dbo.Users u WHERE u.role=N'admin' AND u.is_active=1 AND NOT EXISTS(SELECT 1 FROM dbo.MarketplaceNotifications n WHERE n.event_key=CONCAT(N'COMPLAINT_CREATED:',@adminComplaint,N':ADMIN:',u.id))",
  );
}
async function history(tx:Transaction,input:{complaintId:number;event:string;actorId:number;actorRole:"member"|"seller"|"admin";reason:string;previousStatus?:string;newStatus?:string;previousFault?:string;newFault?:string;settlementId?:number;replacementId?:number;refundId?:number}){
  await tx.request().input("eventComplaint",sql.BigInt,input.complaintId).input("eventType",sql.NVarChar(40),input.event).input("eventActor",sql.Int,input.actorId).input("eventRole",sql.NVarChar(20),input.actorRole).input("eventReason",sql.NVarChar(1000),input.reason).input("eventPreviousStatus",sql.NVarChar(30),input.previousStatus||null).input("eventNewStatus",sql.NVarChar(30),input.newStatus||null).input("eventPreviousFault",sql.NVarChar(30),input.previousFault||null).input("eventNewFault",sql.NVarChar(30),input.newFault||null).input("eventSettlement",sql.BigInt,input.settlementId||null).input("eventReplacement",sql.BigInt,input.replacementId||null).input("eventRefund",sql.BigInt,input.refundId||null).query(
    "INSERT dbo.ComplaintEventHistory(complaint_id,event_type,previous_status,new_status,previous_fault_party,new_fault_party,actor_id,actor_role,reason,settlement_id,replacement_id,refund_id,created_at) VALUES(@eventComplaint,@eventType,@eventPreviousStatus,@eventNewStatus,@eventPreviousFault,@eventNewFault,@eventActor,@eventRole,@eventReason,@eventSettlement,@eventReplacement,@eventRefund,SYSUTCDATETIME())",
  );
}
async function replacementHistory(tx:Transaction,input:{replacementId:number;previous?:string;next:string;actorId:number;role:"seller"|"admin";reason:string}){
  await tx.request().input("rhReplacement",sql.BigInt,input.replacementId).input("rhPrevious",sql.NVarChar(30),input.previous||null).input("rhNext",sql.NVarChar(30),input.next).input("rhActor",sql.Int,input.actorId).input("rhRole",sql.NVarChar(20),input.role).input("rhReason",sql.NVarChar(1000),input.reason).query(
    "INSERT dbo.ReplacementStatusHistory(replacement_id,previous_status,new_status,changed_by,actor_role,reason,created_at) VALUES(@rhReplacement,@rhPrevious,@rhNext,@rhActor,@rhRole,@rhReason,SYSUTCDATETIME())",
  );
}

const detailSelect=`SELECT c.id,c.buyer_id AS buyerId,c.order_id AS orderId,c.shop_order_id AS shopOrderId,c.order_item_id AS orderItemId,c.shop_id AS shopId,
  c.settlement_id AS settlementId,c.product_id AS productId,c.variant_id AS variantId,c.product_name_snapshot AS productName,
  c.variant_name_snapshot AS variantName,c.unit_price_snapshot AS unitPrice,c.affected_quantity AS affectedQuantity,c.category,c.description,c.status,c.fault_party AS faultParty,
  c.admin_decision_reason AS adminDecisionReason,c.resolution_type AS resolutionType,c.reviewed_at AS reviewedAt,c.resolved_at AS resolvedAt,c.rejected_at AS rejectedAt,c.created_at AS createdAt,c.updated_at AS updatedAt,
  o.order_number AS orderNumber,s.name AS shopName,st.status AS settlementStatus,st.hold_source_type AS settlementHoldSourceType,st.hold_source_id AS settlementHoldSourceId,
  bi.batch_id AS batchId,r.id AS refundId,r.status AS refundStatus,r.merchandise_amount AS refundAmount,
  cr.id AS replacementId,cr.status AS replacementStatus,cr.replacement_quantity AS replacementQuantity,cr.inventory_consumed_at AS replacementInventoryConsumedAt
  FROM dbo.MarketplaceComplaints c JOIN dbo.Orders o ON o.id=c.order_id JOIN dbo.Shops s ON s.id=c.shop_id
  JOIN dbo.ShopOrderSettlements st ON st.id=c.settlement_id LEFT JOIN dbo.SettlementBatchItems bi ON bi.settlement_id=st.id
  LEFT JOIN dbo.Refunds r ON r.complaint_id=c.id LEFT JOIN dbo.ComplaintReplacements cr ON cr.complaint_id=c.id`;

async function detail(id:number,scope:Scope={}){
  const request=(await getPool()).request().input("complaintId",sql.BigInt,id),clauses=["c.id=@complaintId"];
  if(scope.buyerId){request.input("scopeBuyer",sql.Int,scope.buyerId);clauses.push("c.buyer_id=@scopeBuyer");}
  if(scope.sellerId){request.input("scopeSeller",sql.Int,scope.sellerId);clauses.push("EXISTS(SELECT 1 FROM dbo.Shops ownerShop WHERE ownerShop.id=c.shop_id AND ownerShop.owner_user_id=@scopeSeller)");}
  const complaint=(await request.query(`${detailSelect} WHERE ${clauses.join(" AND ")}`)).recordset[0];if(!complaint)throw new AppError(404,"Complaint not found");
  const pool=await getPool();
  const events=(await pool.request().input("eventComplaintId",sql.BigInt,id).query("SELECT id,event_type AS eventType,previous_status AS previousStatus,new_status AS newStatus,previous_fault_party AS previousFaultParty,new_fault_party AS newFaultParty,actor_role AS actorRole,reason,created_at AS createdAt FROM dbo.ComplaintEventHistory WHERE complaint_id=@eventComplaintId ORDER BY created_at,id")).recordset;
  const replacementHistoryRows=complaint.replacementId?(await pool.request().input("detailReplacement",sql.BigInt,complaint.replacementId).query("SELECT id,previous_status AS previousStatus,new_status AS newStatus,actor_role AS actorRole,reason,created_at AS createdAt FROM dbo.ReplacementStatusHistory WHERE replacement_id=@detailReplacement ORDER BY created_at,id")).recordset:[];
  return {...complaint,events,replacementHistory:replacementHistoryRows};
}
async function releaseComplaintHold(tx:Transaction,complaint:{id:number;shopOrderId:number;settlementId:number},adminId:number,reason:string){
  const settlement=(await tx.request().input("releaseSettlement",sql.BigInt,complaint.settlementId).query<{status:string;sourceType:string|null;sourceId:string|null;eligibleAt:Date}>("SELECT status,hold_source_type AS sourceType,hold_source_id AS sourceId,eligible_at AS eligibleAt FROM dbo.ShopOrderSettlements WITH(UPDLOCK,HOLDLOCK) WHERE id=@releaseSettlement")).recordset[0];
  if(!settlement||settlement.status!=="HELD"||settlement.sourceType!=="COMPLAINT"||settlement.sourceId!==String(complaint.id))return;
  const blockers=Number((await tx.request().input("releaseShopOrder",sql.Int,complaint.shopOrderId).input("releaseComplaintId",sql.BigInt,complaint.id).query<{count:number}>(`SELECT COUNT(*) AS count FROM dbo.MarketplaceComplaints WITH(UPDLOCK,HOLDLOCK) WHERE shop_order_id=@releaseShopOrder AND id<>@releaseComplaintId AND fault_party=N'SELLER_FAULT' AND status IN(${activeStatuses})`)).recordset[0].count);
  if(blockers)return;
  const next=settlement.eligibleAt<=new Date()?"ELIGIBLE":"PENDING";
  await tx.request().input("releasedSettlement",sql.BigInt,complaint.settlementId).input("releaseNext",sql.NVarChar(20),next).query("UPDATE dbo.ShopOrderSettlements SET status=@releaseNext,held_at=NULL,hold_reason=NULL,hold_source_type=NULL,hold_source_id=NULL,updated_at=SYSUTCDATETIME() WHERE id=@releasedSettlement");
  await tx.request().input("releasedHistory",sql.BigInt,complaint.settlementId).input("releaseNextHistory",sql.NVarChar(20),next).input("releaseAdmin",sql.Int,adminId).input("releaseReason",sql.NVarChar(500),reason).query("INSERT dbo.SettlementStatusHistory(settlement_id,previous_status,new_status,changed_by,reason,created_at) VALUES(@releasedHistory,N'HELD',@releaseNextHistory,@releaseAdmin,@releaseReason,SYSUTCDATETIME())");
}

export const complaintsService={
  async create(buyerId:number,input:{orderItemId:number;affectedQuantity:number;category:string;description:string}){
    const description=text(input.description,"Description"),pool=await getPool(),tx=pool.transaction();let started=false;
    try{await tx.begin();started=true;
      const row=(await tx.request().input("createBuyer",sql.Int,buyerId).input("createItem",sql.Int,input.orderItemId).query<any>(`SELECT oi.id AS orderItemId,oi.order_id AS orderId,oi.shop_order_id AS shopOrderId,oi.product_id AS productId,oi.variant_id AS variantId,oi.product_name AS productName,oi.variant_name AS variantName,oi.unit_price AS unitPrice,oi.quantity,
        o.order_number AS orderNumber,o.logistics_status AS logisticsStatus,so.shop_id AS shopId,so.status AS shopOrderStatus,so.delivered_at AS deliveredAt,st.id AS settlementId,st.status AS settlementStatus,st.eligible_at AS eligibleAt,
        CASE WHEN SYSUTCDATETIME()<=DATEADD(DAY,7,so.delivered_at) THEN 1 ELSE 0 END AS windowOpen
        FROM dbo.OrderItems oi JOIN dbo.Orders o ON o.id=oi.order_id AND o.user_id=@createBuyer JOIN dbo.ShopOrders so ON so.id=oi.shop_order_id
        JOIN dbo.ShopOrderSettlements st ON st.shop_order_id=so.id WHERE oi.id=@createItem`)).recordset[0];
      if(!row)throw new AppError(404,"Delivered order item not found");
      if(row.logisticsStatus!=="DELIVERED"||row.shopOrderStatus!=="HUB_CHECK_PASSED"||!row.deliveredAt)throw new AppError(409,"Complaint is available only for delivered active ShopOrders");
      if(row.settlementStatus==="PAID"||!row.windowOpen)throw new AppError(409,"Commerce complaint window is closed; please use the existing support ticket workflow");
      if(!Number.isInteger(input.affectedQuantity)||input.affectedQuantity<1||input.affectedQuantity>Number(row.quantity))throw new AppError(400,"Affected quantity is invalid");
      const duplicate=(await tx.request().input("duplicateItem",sql.Int,row.orderItemId).query<{id:number}>("SELECT id FROM dbo.MarketplaceComplaints WITH(UPDLOCK,HOLDLOCK) WHERE order_item_id=@duplicateItem")).recordset[0];
      if(duplicate)throw new AppError(409,`Complaint #${duplicate.id} already exists for this order item`);
      const result=await tx.request().input("buyer",sql.Int,buyerId).input("order",sql.Int,row.orderId).input("shopOrder",sql.Int,row.shopOrderId).input("item",sql.Int,row.orderItemId).input("shop",sql.Int,row.shopId).input("settlement",sql.BigInt,row.settlementId).input("product",sql.Int,row.productId).input("variant",sql.Int,row.variantId).input("productName",sql.NVarChar(200),row.productName).input("variantName",sql.NVarChar(200),row.variantName).input("unitPrice",sql.Decimal(18,2),row.unitPrice).input("quantity",sql.Int,input.affectedQuantity).input("category",sql.NVarChar(30),input.category).input("description",sql.NVarChar(2000),description).query<{id:number}>("INSERT dbo.MarketplaceComplaints(buyer_id,order_id,shop_order_id,order_item_id,shop_id,settlement_id,product_id,variant_id,product_name_snapshot,variant_name_snapshot,unit_price_snapshot,affected_quantity,category,description,status,fault_party,created_at,updated_at) OUTPUT INSERTED.id VALUES(@buyer,@order,@shopOrder,@item,@shop,@settlement,@product,@variant,@productName,@variantName,@unitPrice,@quantity,@category,@description,N'OPEN',N'UNDETERMINED',SYSUTCDATETIME(),SYSUTCDATETIME())");
      const id=result.recordset[0].id;await history(tx,{complaintId:id,event:"CREATED",actorId:buyerId,actorRole:"member",reason:"Buyer submitted complaint",newStatus:"OPEN",newFault:"UNDETERMINED",settlementId:row.settlementId});
      await notify(tx,{recipientId:buyerId,eventKey:`COMPLAINT_CREATED:${id}:BUYER`,type:"COMPLAINT_CREATED",title:"Đã tiếp nhận khiếu nại",message:`GymFit đã tiếp nhận khiếu nại #${id} cho ${row.productName}. Settlement chưa bị giữ khi chưa có kết luận lỗi Seller.`,orderId:row.orderId,shopOrderId:row.shopOrderId,complaintId:id});
      await notifyAdmins(tx,id,row.orderId,row.shopOrderId,`Complaint #${id} cần Admin review. OPEN/UNDETERMINED không tự hold settlement.`);
      await tx.commit();started=false;void emailUsersBestEffort([buyerId],`[GymFit] Complaint #${id} đã được tiếp nhận`,`Complaint #${id} đã được tạo. Settlement không bị giữ cho đến khi Admin kết luận SELLER_FAULT.`,true);return detail(id,{buyerId});}catch(error){if(started)await tx.rollback();throw error;}
  },
  async listBuyer(buyerId:number){return (await (await getPool()).request().input("listBuyer",sql.Int,buyerId).query(`${detailSelect} WHERE c.buyer_id=@listBuyer ORDER BY c.created_at DESC,c.id DESC`)).recordset;},
  async detailBuyer(buyerId:number,id:number){return detail(id,{buyerId});},
  async listSeller(sellerId:number){return (await (await getPool()).request().input("listSeller",sql.Int,sellerId).query(`${detailSelect} WHERE EXISTS(SELECT 1 FROM dbo.Shops ownerShop WHERE ownerShop.id=c.shop_id AND ownerShop.owner_user_id=@listSeller) ORDER BY c.created_at DESC,c.id DESC`)).recordset;},
  async detailSeller(sellerId:number,id:number){return detail(id,{sellerId});},
  async listAdmin(filters:{status?:string;faultParty?:string;search?:string;from?:string;to?:string}){
    const request=(await getPool()).request(),clauses:string[]=[];if(filters.status){request.input("status",sql.NVarChar(30),filters.status);clauses.push("c.status=@status");}if(filters.faultParty){request.input("fault",sql.NVarChar(30),filters.faultParty);clauses.push("c.fault_party=@fault");}if(filters.search){request.input("search",sql.NVarChar(120),`%${filters.search.trim()}%`);clauses.push("(o.order_number LIKE @search OR s.name LIKE @search OR CONVERT(NVARCHAR(30),c.id) LIKE @search OR CONVERT(NVARCHAR(30),c.shop_order_id) LIKE @search)");}if(filters.from){request.input("from",sql.Date,filters.from);clauses.push("c.created_at>=@from");}if(filters.to){request.input("to",sql.Date,filters.to);clauses.push("c.created_at<DATEADD(DAY,1,@to)");}return (await request.query(`${detailSelect}${clauses.length?` WHERE ${clauses.join(" AND ")}`:""} ORDER BY c.created_at DESC,c.id DESC`)).recordset;
  },
  async detailAdmin(id:number){return detail(id);},
  async startReview(id:number,adminId:number,reasonInput:string){const reason=text(reasonInput,"Reason"),pool=await getPool(),tx=pool.transaction();let started=false;try{await tx.begin();started=true;const row=(await tx.request().input("reviewId",sql.BigInt,id).query<any>("SELECT id,status,buyer_id AS buyerId,order_id AS orderId,shop_order_id AS shopOrderId FROM dbo.MarketplaceComplaints WITH(UPDLOCK,HOLDLOCK) WHERE id=@reviewId")).recordset[0];if(!row)throw new AppError(404,"Complaint not found");if(row.status==="UNDER_REVIEW"){await tx.commit();started=false;return detail(id);}if(row.status!=="OPEN")throw new AppError(409,"Only open complaint can enter review");await tx.request().input("reviewId2",sql.BigInt,id).query("UPDATE dbo.MarketplaceComplaints SET status=N'UNDER_REVIEW',reviewed_at=SYSUTCDATETIME(),updated_at=SYSUTCDATETIME() WHERE id=@reviewId2");await history(tx,{complaintId:id,event:"REVIEW_STARTED",actorId:adminId,actorRole:"admin",reason,previousStatus:"OPEN",newStatus:"UNDER_REVIEW"});await notify(tx,{recipientId:row.buyerId,eventKey:`COMPLAINT_REVIEW:${id}`,type:"COMPLAINT_REVIEW",title:"Khiếu nại đang được xem xét",message:`Complaint #${id} đang được Admin xem xét.`,orderId:row.orderId,shopOrderId:row.shopOrderId,complaintId:id});await tx.commit();started=false;return detail(id);}catch(error){if(started)await tx.rollback();throw error;}},
  async decideSellerFault(id:number,adminId:number,input:{reason:string;replacementQuantity:number}){
    const reason=text(input.reason,"Reason"),pool=await getPool(),tx=pool.transaction();let started=false;try{await tx.begin();started=true;
      const row=(await tx.request().input("decisionId",sql.BigInt,id).query<any>("SELECT c.*,s.owner_user_id AS sellerId,st.status AS settlementStatus,st.hold_source_type AS holdSourceType FROM dbo.MarketplaceComplaints c WITH(UPDLOCK,HOLDLOCK) JOIN dbo.ShopOrders so WITH(UPDLOCK,HOLDLOCK) ON so.id=c.shop_order_id JOIN dbo.Shops s ON s.id=c.shop_id JOIN dbo.ShopOrderSettlements st WITH(UPDLOCK,HOLDLOCK) ON st.id=c.settlement_id WHERE c.id=@decisionId")).recordset[0];if(!row)throw new AppError(404,"Complaint not found");
      if(row.fault_party==="SELLER_FAULT"&&row.status==="REPLACEMENT_REQUIRED"){await tx.commit();started=false;return detail(id);}if(row.status!=="UNDER_REVIEW"||row.fault_party!=="UNDETERMINED")throw new AppError(409,"Complaint is not ready for Seller fault decision");if(!Number.isInteger(input.replacementQuantity)||input.replacementQuantity<1||input.replacementQuantity>row.affected_quantity)throw new AppError(400,"Replacement quantity exceeds affected quantity");
      await tx.request().input("decisionId2",sql.BigInt,id).input("decisionReason",sql.NVarChar(1000),reason).query("UPDATE dbo.MarketplaceComplaints SET fault_party=N'SELLER_FAULT',status=N'REPLACEMENT_REQUIRED',admin_decision_reason=@decisionReason,resolution_type=N'REPLACEMENT',updated_at=SYSUTCDATETIME() WHERE id=@decisionId2");
      const replacement=(await tx.request().input("complaint",sql.BigInt,id).input("item",sql.Int,row.order_item_id).input("shopOrder",sql.Int,row.shop_order_id).input("shop",sql.Int,row.shop_id).input("product",sql.Int,row.product_id).input("variant",sql.Int,row.variant_id).input("quantity",sql.Int,input.replacementQuantity).input("admin",sql.Int,adminId).query<{id:number}>("INSERT dbo.ComplaintReplacements(complaint_id,order_item_id,shop_order_id,shop_id,product_id,variant_id,replacement_quantity,status,approved_by,approved_at,created_at,updated_at) OUTPUT INSERTED.id VALUES(@complaint,@item,@shopOrder,@shop,@product,@variant,@quantity,N'REQUIRED',@admin,SYSUTCDATETIME(),SYSUTCDATETIME(),SYSUTCDATETIME())")).recordset[0];
      await replacementHistory(tx,{replacementId:replacement.id,next:"REQUIRED",actorId:adminId,role:"admin",reason:"Replacement approved: "+reason});
      if(row.settlementStatus==="PENDING"||row.settlementStatus==="ELIGIBLE"){await tx.request().input("holdSettlement",sql.BigInt,row.settlement_id).input("holdReason",sql.NVarChar(500),`Seller fault complaint #${id}: ${reason}`).input("holdSource",sql.NVarChar(100),String(id)).query("UPDATE dbo.ShopOrderSettlements SET status=N'HELD',held_at=SYSUTCDATETIME(),hold_reason=@holdReason,hold_source_type=N'COMPLAINT',hold_source_id=@holdSource,updated_at=SYSUTCDATETIME() WHERE id=@holdSettlement");await tx.request().input("holdHistorySettlement",sql.BigInt,row.settlement_id).input("holdPrevious",sql.NVarChar(20),row.settlementStatus).input("holdAdmin",sql.Int,adminId).input("holdHistoryReason",sql.NVarChar(500),`Seller fault complaint #${id}`).query("INSERT dbo.SettlementStatusHistory(settlement_id,previous_status,new_status,changed_by,reason,created_at) VALUES(@holdHistorySettlement,@holdPrevious,N'HELD',@holdAdmin,@holdHistoryReason,SYSUTCDATETIME())");}
      await history(tx,{complaintId:id,event:"FAULT_DECIDED",actorId:adminId,actorRole:"admin",reason,previousStatus:"UNDER_REVIEW",newStatus:"REPLACEMENT_REQUIRED",previousFault:"UNDETERMINED",newFault:"SELLER_FAULT",settlementId:row.settlement_id,replacementId:replacement.id});
      await notify(tx,{recipientId:row.buyer_id,eventKey:`COMPLAINT_SELLER_FAULT:${id}:BUYER`,type:"REPLACEMENT_REQUIRED",title:"Đã phê duyệt hàng thay thế",message:`Replacement cho complaint #${id} đã được phê duyệt.`,orderId:row.order_id,shopOrderId:row.shop_order_id,complaintId:id,replacementId:replacement.id});
      await notify(tx,{recipientId:row.sellerId,eventKey:`COMPLAINT_SELLER_FAULT:${id}:SELLER`,type:"REPLACEMENT_REQUIRED",title:"Yêu cầu cung cấp hàng thay thế",message:`Complaint #${id}: chuẩn bị đúng sản phẩm/variant và số lượng ${input.replacementQuantity}.`,orderId:row.order_id,shopOrderId:row.shop_order_id,complaintId:id,replacementId:replacement.id});
      await tx.commit();started=false;void emailUsersBestEffort([row.buyer_id,row.sellerId],`[GymFit] Replacement cho complaint #${id}`,`Admin đã kết luận SELLER_FAULT và phê duyệt replacement số lượng ${input.replacementQuantity}.`);return detail(id);}catch(error){if(started)await tx.rollback();throw error;}
  },
  async decideBuyerFault(id:number,adminId:number,reasonInput:string){return this.decideNonSeller(id,adminId,"BUYER_FAULT",reasonInput);},
  async decideGymfitFault(id:number,adminId:number,reasonInput:string){return this.decideNonSeller(id,adminId,"GYMFIT_OR_CARRIER",reasonInput);},
  async decideNonSeller(id:number,adminId:number,fault:"BUYER_FAULT"|"GYMFIT_OR_CARRIER",reasonInput:string){
    const reason=text(reasonInput,"Reason"),pool=await getPool(),tx=pool.transaction();let started=false;try{await tx.begin();started=true;const row=(await tx.request().input("nonSellerId",sql.BigInt,id).query<any>("SELECT * FROM dbo.MarketplaceComplaints WITH(UPDLOCK,HOLDLOCK) WHERE id=@nonSellerId")).recordset[0];if(!row)throw new AppError(404,"Complaint not found");const next=fault==="BUYER_FAULT"?"REJECTED":"UNDER_REVIEW";if(row.fault_party===fault&&(row.status===next)){await tx.commit();started=false;return detail(id);}if(row.status!=="UNDER_REVIEW"||row.fault_party!=="UNDETERMINED")throw new AppError(409,"Complaint is not ready for fault decision");await tx.request().input("nonSellerId2",sql.BigInt,id).input("fault",sql.NVarChar(30),fault).input("next",sql.NVarChar(30),next).input("reason",sql.NVarChar(1000),reason).query("UPDATE dbo.MarketplaceComplaints SET fault_party=@fault,status=@next,admin_decision_reason=@reason,resolution_type=CASE WHEN @fault=N'BUYER_FAULT' THEN N'REJECTED' END,rejected_at=CASE WHEN @fault=N'BUYER_FAULT' THEN SYSUTCDATETIME() END,updated_at=SYSUTCDATETIME() WHERE id=@nonSellerId2");if(fault==="BUYER_FAULT")await releaseComplaintHold(tx,{id,shopOrderId:row.shop_order_id,settlementId:row.settlement_id},adminId,`Buyer fault decision for complaint #${id}`);await history(tx,{complaintId:id,event:fault==="BUYER_FAULT"?"REJECTED":"FAULT_DECIDED",actorId:adminId,actorRole:"admin",reason,previousStatus:"UNDER_REVIEW",newStatus:next,previousFault:"UNDETERMINED",newFault:fault,settlementId:row.settlement_id});await notify(tx,{recipientId:row.buyer_id,eventKey:`COMPLAINT_${fault}:${id}`,type:"COMPLAINT_DECISION",title:fault==="BUYER_FAULT"?"Khiếu nại đã bị từ chối":"Đã xác định trách nhiệm GymFit/carrier",message:`Complaint #${id}: ${reason}`,orderId:row.order_id,shopOrderId:row.shop_order_id,complaintId:id});await tx.commit();started=false;return detail(id);}catch(error){if(started)await tx.rollback();throw error;}
  },
  async sellerReady(id:number,sellerId:number){
    const pool=await getPool(),tx=pool.transaction();let started=false;try{await tx.begin();started=true;const row=(await tx.request().input("readyId",sql.BigInt,id).input("readySeller",sql.Int,sellerId).query<any>("SELECT cr.*,c.order_id AS orderId,c.buyer_id AS buyerId,s.owner_user_id AS sellerId FROM dbo.ComplaintReplacements cr WITH(UPDLOCK,HOLDLOCK) JOIN dbo.MarketplaceComplaints c ON c.id=cr.complaint_id JOIN dbo.Shops s ON s.id=cr.shop_id WHERE cr.id=@readyId AND s.owner_user_id=@readySeller")).recordset[0];if(!row)throw new AppError(404,"Replacement not found");if(row.status==="READY_FOR_PICKUP"){await tx.commit();started=false;return detail(row.complaint_id,{sellerId});}if(row.status!=="REQUIRED")throw new AppError(409,"Replacement is not waiting for Seller");
      const inv=(await tx.request().input("readyVariant",sql.Int,row.variant_id).query<any>("SELECT i.id,i.on_hand AS onHand,i.reserved,v.product_id AS productId,p.shop_id AS shopId FROM dbo.Inventory i WITH(UPDLOCK,HOLDLOCK) JOIN dbo.ProductVariants v ON v.id=i.variant_id JOIN dbo.Products p ON p.id=v.product_id WHERE i.variant_id=@readyVariant")).recordset[0];if(!inv||inv.shopId!==row.shop_id||inv.productId!==row.product_id)throw new AppError(409,"Replacement inventory ownership is invalid");const next=Number(inv.onHand)-Number(row.replacement_quantity);if(next<Number(inv.reserved))throw new AppError(409,"Insufficient available inventory for replacement");
      await tx.request().input("readyInventory",sql.Int,inv.id).input("readyQuantity",sql.Int,row.replacement_quantity).query("UPDATE dbo.Inventory SET on_hand=on_hand-@readyQuantity,updated_at=SYSUTCDATETIME() WHERE id=@readyInventory AND on_hand-@readyQuantity>=reserved; IF @@ROWCOUNT<>1 THROW 51022,'Concurrent replacement inventory change.',1;");
      const adjustment=(await tx.request().input("inventory",sql.Int,inv.id).input("variant",sql.Int,row.variant_id).input("delta",sql.Int,-row.replacement_quantity).input("previous",sql.Int,inv.onHand).input("next",sql.Int,next).input("reference",sql.NVarChar(100),String(id)).input("seller",sql.Int,sellerId).query<{id:number}>("DECLARE @a TABLE(id BIGINT); INSERT dbo.InventoryAdjustments(inventory_id,variant_id,adjustment_type,quantity_delta,previous_on_hand,new_on_hand,reason,reference_type,reference_id,performed_by,created_at) OUTPUT INSERTED.id INTO @a VALUES(@inventory,@variant,N'COMPLAINT_REPLACEMENT',@delta,@previous,@next,N'Complaint replacement stock leaves Seller',N'COMPLAINT_REPLACEMENT',@reference,@seller,SYSUTCDATETIME()); SELECT id FROM @a")).recordset[0];
      await tx.request().input("readyId2",sql.BigInt,id).input("adjustment",sql.BigInt,adjustment.id).query("UPDATE dbo.ComplaintReplacements SET status=N'READY_FOR_PICKUP',inventory_consumed_at=SYSUTCDATETIME(),inventory_adjustment_id=@adjustment,ready_for_pickup_at=SYSUTCDATETIME(),updated_at=SYSUTCDATETIME() WHERE id=@readyId2");await replacementHistory(tx,{replacementId:id,previous:"REQUIRED",next:"READY_FOR_PICKUP",actorId:sellerId,role:"seller",reason:"Seller prepared replacement and inventory was consumed"});await history(tx,{complaintId:row.complaint_id,event:"REPLACEMENT_STATUS",actorId:sellerId,actorRole:"seller",reason:"Replacement ready for pickup",replacementId:id});await notify(tx,{recipientId:row.buyerId,eventKey:`REPLACEMENT_READY:${id}:BUYER`,type:"REPLACEMENT_READY",title:"Hàng thay thế đã sẵn sàng",message:`Replacement #${id} đang chờ GymFit nhận từ Seller.`,orderId:row.orderId,shopOrderId:row.shop_order_id,complaintId:row.complaint_id,replacementId:id});await tx.commit();started=false;return detail(row.complaint_id,{sellerId});}catch(error){if(started)await tx.rollback();throw error;}
  },
  async transitionReplacement(id:number,adminId:number,action:ReplacementStatus,reasonInput?:string){
    const reason=reasonInput?.trim(),expected:Partial<Record<ReplacementStatus,ReplacementStatus[]>>={PICKED_UP:["READY_FOR_PICKUP"],IN_TRANSIT_TO_HUB:["PICKED_UP"],RECEIVED_AT_HUB:["IN_TRANSIT_TO_HUB"],HUB_CHECK_PASSED:["RECEIVED_AT_HUB","HUB_CHECK_FAILED"],HUB_CHECK_FAILED:["RECEIVED_AT_HUB"],SHIPPED:["HUB_CHECK_PASSED"],DELIVERED:["SHIPPED"],FAILED:["REQUIRED","HUB_CHECK_FAILED"]};if(!expected[action])throw new AppError(400,"Unsupported replacement action");if((action==="HUB_CHECK_FAILED"||action==="FAILED")&&!reason)throw new AppError(400,"Failure reason is required");
    const pool=await getPool(),tx=pool.transaction();let started=false;try{await tx.begin();started=true;const row=(await tx.request().input("transitionReplacement",sql.BigInt,id).query<any>("SELECT cr.*,c.buyer_id AS buyerId,c.order_id AS orderId,c.settlement_id AS settlementId,c.shop_order_id AS complaintShopOrderId,s.owner_user_id AS sellerId FROM dbo.ComplaintReplacements cr WITH(UPDLOCK,HOLDLOCK) JOIN dbo.MarketplaceComplaints c WITH(UPDLOCK,HOLDLOCK) ON c.id=cr.complaint_id JOIN dbo.Shops s ON s.id=cr.shop_id WHERE cr.id=@transitionReplacement")).recordset[0];if(!row)throw new AppError(404,"Replacement not found");if(row.status===action){await tx.commit();started=false;return detail(row.complaint_id);}if(!expected[action]!.includes(row.status))throw new AppError(409,`Cannot transition replacement from ${row.status} to ${action}`);
      const column:Record<string,string>={PICKED_UP:"picked_up_at",IN_TRANSIT_TO_HUB:"in_transit_to_hub_at",RECEIVED_AT_HUB:"received_at_hub_at",HUB_CHECK_PASSED:"hub_checked_at",HUB_CHECK_FAILED:"hub_checked_at",SHIPPED:"shipped_at",DELIVERED:"delivered_at",FAILED:"failed_at"};await tx.request().input("transitionReplacement2",sql.BigInt,id).input("action",sql.NVarChar(30),action).input("failure",sql.NVarChar(1000),action==="FAILED"?reason:null).query(`UPDATE dbo.ComplaintReplacements SET status=@action,${column[action]}=SYSUTCDATETIME(),failure_reason=@failure,updated_at=SYSUTCDATETIME() WHERE id=@transitionReplacement2`);
      await replacementHistory(tx,{replacementId:id,previous:row.status,next:action,actorId:adminId,role:"admin",reason:reason||`Admin transition to ${action}`});await history(tx,{complaintId:row.complaint_id,event:"REPLACEMENT_STATUS",actorId:adminId,actorRole:"admin",reason:reason||`Replacement ${action}`,replacementId:id,settlementId:row.settlementId});
      if(action==="DELIVERED"){await tx.request().input("resolveComplaint",sql.BigInt,row.complaint_id).query("UPDATE dbo.MarketplaceComplaints SET status=N'RESOLVED',resolution_type=N'REPLACEMENT',resolved_at=SYSUTCDATETIME(),updated_at=SYSUTCDATETIME() WHERE id=@resolveComplaint AND status=N'REPLACEMENT_REQUIRED'");await releaseComplaintHold(tx,{id:row.complaint_id,shopOrderId:row.complaintShopOrderId,settlementId:row.settlementId},adminId,`Replacement delivered for complaint #${row.complaint_id}`);await history(tx,{complaintId:row.complaint_id,event:"RESOLVED",actorId:adminId,actorRole:"admin",reason:"Replacement delivered successfully",previousStatus:"REPLACEMENT_REQUIRED",newStatus:"RESOLVED",replacementId:id,settlementId:row.settlementId});}
      await notify(tx,{recipientId:row.buyerId,eventKey:`REPLACEMENT_${action}:${id}:BUYER`,type:`REPLACEMENT_${action}`.slice(0,50),title:`Replacement ${action}`,message:`Replacement #${id} chuyển trạng thái ${action}.`,orderId:row.orderId,shopOrderId:row.shop_order_id,complaintId:row.complaint_id,replacementId:id});if((action==="HUB_CHECK_FAILED"||action==="FAILED"||action==="DELIVERED")&&row.sellerId)await notify(tx,{recipientId:row.sellerId,eventKey:`REPLACEMENT_${action}:${id}:SELLER`,type:`REPLACEMENT_${action}`.slice(0,50),title:`Replacement ${action}`,message:`Replacement #${id} chuyển trạng thái ${action}.`,orderId:row.orderId,shopOrderId:row.shop_order_id,complaintId:row.complaint_id,replacementId:id});
      await tx.commit();started=false;return detail(row.complaint_id);}catch(error){if(started)await tx.rollback();throw error;}
  },
  async createRefund(id:number,adminId:number,input:{amount?:number;reason:string}){
    const reason=text(input.reason,"Reason"),pool=await getPool(),tx=pool.transaction();let started=false;try{await tx.begin();started=true;const row=(await tx.request().input("refundComplaint",sql.BigInt,id).query<any>("SELECT c.*,o.currency,cr.id AS replacementId,cr.status AS replacementStatus FROM dbo.MarketplaceComplaints c WITH(UPDLOCK,HOLDLOCK) JOIN dbo.Orders o ON o.id=c.order_id LEFT JOIN dbo.ComplaintReplacements cr WITH(UPDLOCK,HOLDLOCK) ON cr.complaint_id=c.id WHERE c.id=@refundComplaint")).recordset[0];if(!row)throw new AppError(404,"Complaint not found");if(row.fault_party!=="SELLER_FAULT"||row.replacementStatus!=="FAILED")throw new AppError(409,"Refund fallback requires a failed Seller-fault replacement");const max=Number(row.unit_price_snapshot)*Number(row.affected_quantity),amount=input.amount===undefined?max:Number(input.amount);if(!Number.isFinite(amount)||amount<=0||amount>max)throw new AppError(400,"Refund amount exceeds affected merchandise snapshot");
      const refund=(await tx.request().input("order",sql.Int,row.order_id).input("shopOrder",sql.Int,row.shop_order_id).input("buyer",sql.Int,row.buyer_id).input("amount",sql.Decimal(18,2),amount).input("currency",sql.Char(3),row.currency).input("reason",sql.NVarChar(500),reason).input("complaint",sql.BigInt,id).query<{id:number}>("INSERT dbo.Refunds(order_id,shop_order_id,buyer_id,merchandise_amount,shipping_amount,currency,status,reason,complaint_id,refund_source_type,created_at,updated_at) OUTPUT INSERTED.id VALUES(@order,@shopOrder,@buyer,@amount,0,@currency,N'PENDING',@reason,@complaint,N'COMPLAINT_RESOLUTION',SYSUTCDATETIME(),SYSUTCDATETIME())")).recordset[0];await tx.request().input("refundComplaint2",sql.BigInt,id).query("UPDATE dbo.MarketplaceComplaints SET resolution_type=N'REFUND',updated_at=SYSUTCDATETIME() WHERE id=@refundComplaint2");await history(tx,{complaintId:id,event:"REFUND_CREATED",actorId:adminId,actorRole:"admin",reason,replacementId:row.replacementId,refundId:refund.id,settlementId:row.settlement_id});await notify(tx,{recipientId:row.buyer_id,eventKey:`COMPLAINT_REFUND:${id}`,type:"COMPLAINT_REFUND",title:"Đã tạo hoàn tiền fallback",message:`Refund ${amount} ${row.currency} cho complaint #${id} đang chờ xử lý thủ công.`,orderId:row.order_id,shopOrderId:row.shop_order_id,complaintId:id,replacementId:row.replacementId,refundId:refund.id});await tx.commit();started=false;return detail(id);}catch(error){if(started)await tx.rollback();throw error;}
  },
  async resolve(id:number,adminId:number,input:{reason:string;resolutionType:"REFUND"|"MANUAL_SUPPORT"}){
    const reason=text(input.reason,"Reason"),pool=await getPool(),tx=pool.transaction();let started=false;try{await tx.begin();started=true;const row=(await tx.request().input("resolveId",sql.BigInt,id).query<any>("SELECT c.*,r.id AS refundId,r.status AS refundStatus FROM dbo.MarketplaceComplaints c WITH(UPDLOCK,HOLDLOCK) LEFT JOIN dbo.Refunds r ON r.complaint_id=c.id WHERE c.id=@resolveId")).recordset[0];if(!row)throw new AppError(404,"Complaint not found");if(row.status==="RESOLVED"){await tx.commit();started=false;return detail(id);}if(row.status!=="UNDER_REVIEW"&&row.status!=="REPLACEMENT_REQUIRED")throw new AppError(409,"Complaint cannot be resolved");if(input.resolutionType==="REFUND"&&(!row.refundId||row.refundStatus!=="COMPLETED"))throw new AppError(409,"Refund must be completed before complaint resolution");if(input.resolutionType==="MANUAL_SUPPORT"&&row.fault_party!=="GYMFIT_OR_CARRIER")throw new AppError(409,"Manual support resolution is for GymFit/carrier fault");await tx.request().input("resolveId2",sql.BigInt,id).input("resolution",sql.NVarChar(30),input.resolutionType).input("reason",sql.NVarChar(1000),reason).query("UPDATE dbo.MarketplaceComplaints SET status=N'RESOLVED',resolution_type=@resolution,admin_decision_reason=COALESCE(admin_decision_reason,@reason),resolved_at=SYSUTCDATETIME(),updated_at=SYSUTCDATETIME() WHERE id=@resolveId2");await releaseComplaintHold(tx,{id,shopOrderId:row.shop_order_id,settlementId:row.settlement_id},adminId,`Complaint #${id} resolved: ${input.resolutionType}`);await history(tx,{complaintId:id,event:"RESOLVED",actorId:adminId,actorRole:"admin",reason,previousStatus:row.status,newStatus:"RESOLVED",settlementId:row.settlement_id,refundId:row.refundId});await notify(tx,{recipientId:row.buyer_id,eventKey:`COMPLAINT_RESOLVED:${id}`,type:"COMPLAINT_RESOLVED",title:"Khiếu nại đã giải quyết",message:`Complaint #${id} đã được giải quyết: ${input.resolutionType}.`,orderId:row.order_id,shopOrderId:row.shop_order_id,complaintId:id,refundId:row.refundId});await tx.commit();started=false;return detail(id);}catch(error){if(started)await tx.rollback();throw error;}
  },
};
